// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.companion.virtual;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ActivityPolicyExemption implements android.os.Parcelable {
    protected ActivityPolicyExemption() {}
}
