// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telephony.ims;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ImsRegistrationAttributes implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int ATTR_EPDG_OVER_CELL_INTERNET = 1;
    public static final int ATTR_REGISTRATION_TYPE_EMERGENCY = 2;
    public static final int ATTR_VIRTUAL_FOR_ANONYMOUS_EMERGENCY_CALL = 4;
    public static android.os.Parcelable.Creator CREATOR;
    public ImsRegistrationAttributes(int p0, int p1, int p2, java.util.Set p3) {}
    public ImsRegistrationAttributes(int p0, int p1, int p2, java.util.Set p3, android.telephony.ims.SipDetails p4) {}
    public ImsRegistrationAttributes(int p0, int p1, int p2, java.util.Set p3, android.telephony.ims.SipDetails p4, java.lang.String p5) {}
    public ImsRegistrationAttributes(android.os.Parcel p0) {}
    public int describeContents() { return 0; }
    public int getAttributeFlags() { return (huskProps.get("AttributeFlags") instanceof Integer ? (Integer) huskProps.get("AttributeFlags") : 0); }
    public java.util.Set getFeatureTags() { return (huskProps.get("FeatureTags") != null ? (java.util.Set) huskProps.get("FeatureTags") : new java.util.HashSet()); }
    public boolean getFlagRegistrationTypeEmergency() { return (huskProps.get("FlagRegistrationTypeEmergency") instanceof Boolean ? (Boolean) huskProps.get("FlagRegistrationTypeEmergency") : false); }
    public boolean getFlagVirtualRegistrationForEmergencyCall() { return (huskProps.get("FlagVirtualRegistrationForEmergencyCall") instanceof Boolean ? (Boolean) huskProps.get("FlagVirtualRegistrationForEmergencyCall") : false); }
    public java.lang.String getPcscfAddress() { return (java.lang.String) huskProps.get("PcscfAddress"); }
    public int getRegistrationTechnology() { return (huskProps.get("RegistrationTechnology") instanceof Integer ? (Integer) huskProps.get("RegistrationTechnology") : 0); }
    public android.telephony.ims.SipDetails getSipDetails() { return (android.telephony.ims.SipDetails) huskProps.get("SipDetails"); }
    public int getTransportType() { return (huskProps.get("TransportType") instanceof Integer ? (Integer) huskProps.get("TransportType") : 0); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    ImsRegistrationAttributes() { this((android.os.Parcel) null); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(int p0) {}
        public android.telephony.ims.ImsRegistrationAttributes build() { android.telephony.ims.ImsRegistrationAttributes x = new android.telephony.ims.ImsRegistrationAttributes(); x.huskProps.putAll(huskProps); return x; }
        public android.telephony.ims.ImsRegistrationAttributes.Builder setFeatureTags(java.util.Set p0) { huskProps.put("FeatureTags", p0); return this; }
        public android.telephony.ims.ImsRegistrationAttributes.Builder setFlagRegistrationTypeEmergency() { return this; }
        public android.telephony.ims.ImsRegistrationAttributes.Builder setFlagVirtualRegistrationForEmergencyCall() { return this; }
        public android.telephony.ims.ImsRegistrationAttributes.Builder setPcscfAddress(java.lang.String p0) { huskProps.put("PcscfAddress", p0); return this; }
        public android.telephony.ims.ImsRegistrationAttributes.Builder setSipDetails(android.telephony.ims.SipDetails p0) { huskProps.put("SipDetails", p0); return this; }
        Builder() { this((int) 0); }
    }
}
