// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telephony.ims;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface RegistrationManager {
    java.util.Map IMS_REG_TO_ACCESS_TYPE_MAP = null;
    int REGISTRATION_STATE_NOT_REGISTERED = 0;
    int REGISTRATION_STATE_REGISTERED = 2;
    int REGISTRATION_STATE_REGISTERING = 1;
    int SUGGESTED_ACTION_NONE = 0;
    int SUGGESTED_ACTION_TRIGGER_CLEAR_RAT_BLOCKS = 4;
    int SUGGESTED_ACTION_TRIGGER_PLMN_BLOCK = 1;
    int SUGGESTED_ACTION_TRIGGER_PLMN_BLOCK_WITH_TIMEOUT = 2;
    int SUGGESTED_ACTION_TRIGGER_RAT_BLOCK = 3;
    int SUGGESTED_ACTION_TRIGGER_THROTTLE_TIME = 5;
    static int getAccessType(int p0) { return 0; }
    static java.lang.String registrationStateToString(int p0) { return null; }
    void getRegistrationState(java.util.concurrent.Executor p0, java.util.function.Consumer p1);
    void getRegistrationTransportType(java.util.concurrent.Executor p0, java.util.function.Consumer p1);
    void registerImsRegistrationCallback(java.util.concurrent.Executor p0, android.telephony.ims.RegistrationManager.RegistrationCallback p1);
    void unregisterImsRegistrationCallback(android.telephony.ims.RegistrationManager.RegistrationCallback p0);
    public static class RegistrationCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public RegistrationCallback() {}
        public android.telephony.ims.aidl.IImsRegistrationCallback getBinder() { return (android.telephony.ims.aidl.IImsRegistrationCallback) huskProps.get("Binder"); }
        public void onRegistered(int p0) {}
        public void onRegistered(android.telephony.ims.ImsRegistrationAttributes p0) {}
        public void onRegistering(int p0) {}
        public void onRegistering(android.telephony.ims.ImsRegistrationAttributes p0) {}
        public void onSubscriberAssociatedUriChanged(android.net.Uri[] p0) {}
        public void onTechnologyChangeFailed(int p0, android.telephony.ims.ImsReasonInfo p1) {}
        public void onUnregistered(android.telephony.ims.ImsReasonInfo p0) {}
        public void onUnregistered(android.telephony.ims.ImsReasonInfo p0, int p1, int p2) {}
        public void onUnregistered(android.telephony.ims.ImsReasonInfo p0, int p1, int p2, int p3) {}
        public void onUnregistered(android.telephony.ims.ImsReasonInfo p0, android.telephony.ims.SipDetails p1) {}
        public void setExecutor(java.util.concurrent.Executor p0) { huskProps.put("Executor", p0); }
    }
}
