// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.graphics;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ImageDecoder implements java.lang.AutoCloseable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int ALLOCATOR_DEFAULT = 0;
    public static final int ALLOCATOR_HARDWARE = 3;
    public static final int ALLOCATOR_SHARED_MEMORY = 2;
    public static final int ALLOCATOR_SOFTWARE = 1;
    public static final int MEMORY_POLICY_DEFAULT = 1;
    public static int MEMORY_POLICY_LOW_RAM;
    public static android.graphics.ImageDecoder.Source createSource(android.content.ContentResolver p0, android.net.Uri p1) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(android.content.ContentResolver p0, android.net.Uri p1, android.content.res.Resources p2) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(android.content.res.AssetManager p0, java.lang.String p1) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(android.content.res.Resources p0, int p1) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(android.content.res.Resources p0, java.io.InputStream p1) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(android.content.res.Resources p0, java.io.InputStream p1, int p2) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(java.io.File p0) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(java.nio.ByteBuffer p0) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(java.util.concurrent.Callable p0) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(byte[] p0) { return null; }
    public static android.graphics.ImageDecoder.Source createSource(byte[] p0, int p1, int p2) { return null; }
    public static android.graphics.Bitmap decodeBitmap(android.graphics.ImageDecoder.Source p0) { return null; }
    public static android.graphics.Bitmap decodeBitmap(android.graphics.ImageDecoder.Source p0, android.graphics.ImageDecoder.OnHeaderDecodedListener p1) { return null; }
    public static android.graphics.drawable.Drawable decodeDrawable(android.graphics.ImageDecoder.Source p0) { return null; }
    public static android.graphics.drawable.Drawable decodeDrawable(android.graphics.ImageDecoder.Source p0, android.graphics.ImageDecoder.OnHeaderDecodedListener p1) { return null; }
    public static android.graphics.ImageDecoder.ImageInfo decodeHeader(android.graphics.ImageDecoder.Source p0) { return null; }
    public static android.graphics.ImageDecoder.OnHeaderDecodedListener getDefaultProcessListener() { return null; }
    public static android.graphics.ImageDecoder.OnHeaderDecodedListener getDefaultThreadListener() { return null; }
    public static boolean isMimeTypeSupported(java.lang.String p0) { return false; }
    public static void setDefaultProcessListener(android.graphics.ImageDecoder.OnHeaderDecodedListener p0) {}
    public static void setDefaultThreadListener(android.graphics.ImageDecoder.OnHeaderDecodedListener p0) {}
    public void close() {}
    protected void finalize() {}
    public int getAllocator() { return (huskProps.get("Allocator") instanceof Integer ? (Integer) huskProps.get("Allocator") : 0); }
    public android.graphics.Rect getCrop() { return (android.graphics.Rect) huskProps.get("Crop"); }
    public int getMemorySizePolicy() { return (huskProps.get("MemorySizePolicy") instanceof Integer ? (Integer) huskProps.get("MemorySizePolicy") : 0); }
    public android.graphics.ImageDecoder.OnPartialImageListener getOnPartialImageListener() { return (android.graphics.ImageDecoder.OnPartialImageListener) huskProps.get("OnPartialImageListener"); }
    public android.graphics.PostProcessor getPostProcessor() { return (android.graphics.PostProcessor) huskProps.get("PostProcessor"); }
    public boolean isDecodeAsAlphaMaskEnabled() { return (huskProps.get("DecodeAsAlphaMaskEnabled") instanceof Boolean ? (Boolean) huskProps.get("DecodeAsAlphaMaskEnabled") : false); }
    public boolean isMutableRequired() { return (huskProps.get("MutableRequired") instanceof Boolean ? (Boolean) huskProps.get("MutableRequired") : false); }
    public boolean isUnpremultipliedRequired() { return (huskProps.get("UnpremultipliedRequired") instanceof Boolean ? (Boolean) huskProps.get("UnpremultipliedRequired") : false); }
    public void setAllocator(int p0) { huskProps.put("Allocator", Integer.valueOf(p0)); }
    public void setCrop(android.graphics.Rect p0) { huskProps.put("Crop", p0); }
    public void setDecodeAsAlphaMaskEnabled(boolean p0) { huskProps.put("DecodeAsAlphaMaskEnabled", Boolean.valueOf(p0)); }
    public void setMemorySizePolicy(int p0) { huskProps.put("MemorySizePolicy", Integer.valueOf(p0)); }
    public void setMutableRequired(boolean p0) { huskProps.put("MutableRequired", Boolean.valueOf(p0)); }
    public void setOnPartialImageListener(android.graphics.ImageDecoder.OnPartialImageListener p0) { huskProps.put("OnPartialImageListener", p0); }
    public void setOutPaddingRect(android.graphics.Rect p0) { huskProps.put("OutPaddingRect", p0); }
    public void setPostProcessor(android.graphics.PostProcessor p0) { huskProps.put("PostProcessor", p0); }
    public void setTargetColorSpace(android.graphics.ColorSpace p0) { huskProps.put("TargetColorSpace", p0); }
    public void setTargetSampleSize(int p0) { huskProps.put("TargetSampleSize", Integer.valueOf(p0)); }
    public void setTargetSize(int p0, int p1) {}
    public void setUnpremultipliedRequired(boolean p0) { huskProps.put("UnpremultipliedRequired", Boolean.valueOf(p0)); }
    protected ImageDecoder() {}
    public static class AssetInputStreamSource extends android.graphics.ImageDecoder.Source {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public AssetInputStreamSource(android.content.res.AssetManager.AssetInputStream p0, android.content.res.Resources p1, android.util.TypedValue p2) { super(); }
        public android.graphics.ImageDecoder createImageDecoder(boolean p0) { return null; }
        public int getDensity() { return (huskProps.get("Density") instanceof Integer ? (Integer) huskProps.get("Density") : 0); }
        public android.content.res.Resources getResources() { return (android.content.res.Resources) huskProps.get("Resources"); }
        AssetInputStreamSource() { this((android.content.res.AssetManager.AssetInputStream) null, (android.content.res.Resources) null, (android.util.TypedValue) null); }
    }
    public static final class DecodeException extends java.io.IOException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int SOURCE_EXCEPTION = 1;
        public static final int SOURCE_INCOMPLETE = 2;
        public static final int SOURCE_MALFORMED_DATA = 3;
        public int getError() { return (huskProps.get("Error") instanceof Integer ? (Integer) huskProps.get("Error") : 0); }
        public android.graphics.ImageDecoder.Source getSource() { return (android.graphics.ImageDecoder.Source) huskProps.get("Source"); }
        protected DecodeException() { super(); }
    }
    public static class ImageInfo {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public android.graphics.ColorSpace getColorSpace() { return (android.graphics.ColorSpace) huskProps.get("ColorSpace"); }
        public java.lang.String getMimeType() { return (java.lang.String) huskProps.get("MimeType"); }
        public android.util.Size getSize() { return (android.util.Size) huskProps.get("Size"); }
        public boolean isAnimated() { return (huskProps.get("Animated") instanceof Boolean ? (Boolean) huskProps.get("Animated") : false); }
        protected ImageInfo() {}
    }
    public interface OnHeaderDecodedListener {
        void onHeaderDecoded(android.graphics.ImageDecoder p0, android.graphics.ImageDecoder.ImageInfo p1, android.graphics.ImageDecoder.Source p2);
    }
    public interface OnPartialImageListener {
        boolean onPartialImage(android.graphics.ImageDecoder.DecodeException p0);
    }
    public static abstract class Source {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected Source() {}
    }
}
