// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.hotspot2.pps;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class HomeSp implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public HomeSp() {}
    public HomeSp(android.net.wifi.hotspot2.pps.HomeSp p0) {}
    public int describeContents() { return 0; }
    public java.lang.String getFqdn() { return (java.lang.String) huskProps.get("Fqdn"); }
    public java.lang.String getFriendlyName() { return (java.lang.String) huskProps.get("FriendlyName"); }
    public java.util.Map getHomeNetworkIds() { return (huskProps.get("HomeNetworkIds") != null ? (java.util.Map) huskProps.get("HomeNetworkIds") : new java.util.HashMap()); }
    public java.lang.String getIconUrl() { return (java.lang.String) huskProps.get("IconUrl"); }
    public long[] getMatchAllOis() { return (long[]) huskProps.get("MatchAllOis"); }
    public long[] getMatchAnyOis() { return (long[]) huskProps.get("MatchAnyOis"); }
    public java.lang.String[] getOtherHomePartners() { return (java.lang.String[]) huskProps.get("OtherHomePartners"); }
    public java.util.Collection getOtherHomePartnersList() { return (huskProps.get("OtherHomePartnersList") != null ? (java.util.Collection) huskProps.get("OtherHomePartnersList") : new java.util.ArrayList()); }
    public long[] getRoamingConsortiumOis() { return (long[]) huskProps.get("RoamingConsortiumOis"); }
    public int getUniqueId() { return (huskProps.get("UniqueId") instanceof Integer ? (Integer) huskProps.get("UniqueId") : 0); }
    public void setFqdn(java.lang.String p0) { huskProps.put("Fqdn", p0); }
    public void setFriendlyName(java.lang.String p0) { huskProps.put("FriendlyName", p0); }
    public void setHomeNetworkIds(java.util.Map p0) { huskProps.put("HomeNetworkIds", p0); }
    public void setIconUrl(java.lang.String p0) { huskProps.put("IconUrl", p0); }
    public void setMatchAllOis(long[] p0) { huskProps.put("MatchAllOis", p0); }
    public void setMatchAnyOis(long[] p0) { huskProps.put("MatchAnyOis", p0); }
    public void setOtherHomePartners(java.lang.String[] p0) { huskProps.put("OtherHomePartners", p0); }
    public void setOtherHomePartnersList(java.util.Collection p0) { huskProps.put("OtherHomePartnersList", p0); }
    public void setRoamingConsortiumOis(long[] p0) { huskProps.put("RoamingConsortiumOis", p0); }
    public boolean validate() { return false; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
