// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.aware;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface IWifiAwareMacAddressProvider extends android.os.IInterface {
}
