// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.content;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class AttributionSource implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public AttributionSource(int p0, int p1, java.lang.String p2, java.lang.String p3) {}
    public AttributionSource(int p0, int p1, java.lang.String p2, java.lang.String p3, android.os.IBinder p4) {}
    public AttributionSource(int p0, int p1, java.lang.String p2, java.lang.String p3, android.os.IBinder p4, java.lang.String[] p5, int p6, android.content.AttributionSource p7) {}
    public AttributionSource(int p0, int p1, java.lang.String p2, java.lang.String p3, java.lang.String[] p4, int p5, android.content.AttributionSource p6) {}
    public AttributionSource(int p0, java.lang.String p1, java.lang.String p2) {}
    public AttributionSource(int p0, java.lang.String p1, java.lang.String p2, int p3) {}
    public AttributionSource(int p0, java.lang.String p1, java.lang.String p2, android.os.IBinder p3) {}
    public AttributionSource(int p0, java.lang.String p1, java.lang.String p2, java.util.Set p3, android.content.AttributionSource p4) {}
    public AttributionSource(android.content.AttributionSource p0, android.content.AttributionSource p1) {}
    public AttributionSource(android.content.AttributionSourceState p0) {}
    public static android.content.AttributionSource myAttributionSource() { return new AttributionSource(); }
    public android.content.AttributionSource.ScopedParcelState asScopedParcelState() { return null; }
    public android.content.AttributionSourceState asState() { return null; }
    public boolean checkCallingUid() { return false; }
    public int describeContents() { return 0; }
    public void enforceCallingPid() {}
    public void enforceCallingUid() {}
    public boolean equalsExceptToken(android.content.AttributionSource p0) { return false; }
    public java.lang.String getAttributionTag() { return (java.lang.String) huskProps.get("AttributionTag"); }
    public int getDeviceId() { return (huskProps.get("DeviceId") instanceof Integer ? (Integer) huskProps.get("DeviceId") : 0); }
    public android.content.AttributionSource getNext() { return (android.content.AttributionSource) huskProps.get("Next"); }
    public java.lang.String getNextAttributionTag() { return (java.lang.String) huskProps.get("NextAttributionTag"); }
    public int getNextDeviceId() { return (huskProps.get("NextDeviceId") instanceof Integer ? (Integer) huskProps.get("NextDeviceId") : 0); }
    public java.lang.String getNextPackageName() { return (java.lang.String) huskProps.get("NextPackageName"); }
    public android.os.IBinder getNextToken() { return (android.os.IBinder) huskProps.get("NextToken"); }
    public int getNextUid() { return (huskProps.get("NextUid") instanceof Integer ? (Integer) huskProps.get("NextUid") : 0); }
    public java.lang.String getPackageName() { return (java.lang.String) huskProps.get("PackageName"); }
    public int getPid() { return (huskProps.get("Pid") instanceof Integer ? (Integer) huskProps.get("Pid") : 0); }
    public java.util.Set getRenouncedPermissions() { return (huskProps.get("RenouncedPermissions") != null ? (java.util.Set) huskProps.get("RenouncedPermissions") : new java.util.HashSet()); }
    public android.os.IBinder getToken() { return (android.os.IBinder) huskProps.get("Token"); }
    public int getUid() { return (huskProps.get("Uid") instanceof Integer ? (Integer) huskProps.get("Uid") : 0); }
    public boolean isTrusted(android.content.Context p0) { return false; }
    public android.content.AttributionSource withDefaultToken() { return this; }
    public android.content.AttributionSource withDeviceId(int p0) { return this; }
    public android.content.AttributionSource withNextAttributionSource(android.content.AttributionSource p0) { return this; }
    public android.content.AttributionSource withPackageName(java.lang.String p0) { return this; }
    public android.content.AttributionSource withPid(int p0) { return this; }
    public android.content.AttributionSource withToken(android.os.IBinder p0) { return this; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    AttributionSource() { this((android.content.AttributionSourceState) null); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(int p0) {}
        public Builder(android.content.AttributionSource p0) {}
        public android.content.AttributionSource build() { return new android.content.AttributionSource(); }
        public android.content.AttributionSource.Builder setAttributionTag(java.lang.String p0) { huskProps.put("AttributionTag", p0); return this; }
        public android.content.AttributionSource.Builder setDeviceId(int p0) { huskProps.put("DeviceId", Integer.valueOf(p0)); return this; }
        public android.content.AttributionSource.Builder setNext(android.content.AttributionSource p0) { huskProps.put("Next", p0); return this; }
        public android.content.AttributionSource.Builder setNextAttributionSource(android.content.AttributionSource p0) { huskProps.put("NextAttributionSource", p0); return this; }
        public android.content.AttributionSource.Builder setPackageName(java.lang.String p0) { huskProps.put("PackageName", p0); return this; }
        public android.content.AttributionSource.Builder setPid(int p0) { huskProps.put("Pid", Integer.valueOf(p0)); return this; }
        public android.content.AttributionSource.Builder setRenouncedPermissions(java.util.Set p0) { huskProps.put("RenouncedPermissions", p0); return this; }
        Builder() { this((int) 0); }
    }
    public static class ScopedParcelState implements java.lang.AutoCloseable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ScopedParcelState(android.content.AttributionSource p0) {}
        public void close() {}
        public android.os.Parcel getParcel() { return (android.os.Parcel) huskProps.get("Parcel"); }
        ScopedParcelState() { this((android.content.AttributionSource) null); }
    }
}
