// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.content;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ReceiverCallNotAllowedException extends android.util.AndroidRuntimeException {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ReceiverCallNotAllowedException(java.lang.String p0) { super(p0); }
}
