// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.content;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class UriPermission implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final long INVALID_TIME = -9223372036854775808L;
    public UriPermission(android.net.Uri p0, int p1, long p2) {}
    public UriPermission(android.os.Parcel p0) {}
    public int describeContents() { return 0; }
    public long getPersistedTime() { return (huskProps.get("PersistedTime") instanceof Long ? (Long) huskProps.get("PersistedTime") : 0L); }
    public android.net.Uri getUri() { return (android.net.Uri) huskProps.get("Uri"); }
    public boolean isReadPermission() { return (huskProps.get("ReadPermission") instanceof Boolean ? (Boolean) huskProps.get("ReadPermission") : false); }
    public boolean isWritePermission() { return (huskProps.get("WritePermission") instanceof Boolean ? (Boolean) huskProps.get("WritePermission") : false); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    UriPermission() { this((android.os.Parcel) null); }
}
