// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.renderscript;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Script extends android.renderscript.BaseObj {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public void bindAllocation(android.renderscript.Allocation p0, int p1) {}
    protected android.renderscript.Script.FieldID createFieldID(int p0, android.renderscript.Element p1) { return null; }
    protected android.renderscript.Script.InvokeID createInvokeID(int p0) { return null; }
    protected android.renderscript.Script.KernelID createKernelID(int p0, int p1, android.renderscript.Element p2, android.renderscript.Element p3) { return null; }
    protected void forEach(int p0, android.renderscript.Allocation p1, android.renderscript.Allocation p2, android.renderscript.FieldPacker p3) {}
    protected void forEach(int p0, android.renderscript.Allocation p1, android.renderscript.Allocation p2, android.renderscript.FieldPacker p3, android.renderscript.Script.LaunchOptions p4) {}
    protected void forEach(int p0, android.renderscript.Allocation[] p1, android.renderscript.Allocation p2, android.renderscript.FieldPacker p3) {}
    protected void forEach(int p0, android.renderscript.Allocation[] p1, android.renderscript.Allocation p2, android.renderscript.FieldPacker p3, android.renderscript.Script.LaunchOptions p4) {}
    public boolean getVarB(int p0) { return false; }
    public double getVarD(int p0) { return 0d; }
    public float getVarF(int p0) { return 0f; }
    public int getVarI(int p0) { return 0; }
    public long getVarJ(int p0) { return 0L; }
    public void getVarV(int p0, android.renderscript.FieldPacker p1) {}
    protected void invoke(int p0) {}
    protected void invoke(int p0, android.renderscript.FieldPacker p1) {}
    protected void reduce(int p0, android.renderscript.Allocation[] p1, android.renderscript.Allocation p2, android.renderscript.Script.LaunchOptions p3) {}
    public void setTimeZone(java.lang.String p0) { huskProps.put("TimeZone", p0); }
    public void setVar(int p0, double p1) {}
    public void setVar(int p0, float p1) {}
    public void setVar(int p0, int p1) {}
    public void setVar(int p0, long p1) {}
    public void setVar(int p0, android.renderscript.BaseObj p1) {}
    public void setVar(int p0, android.renderscript.FieldPacker p1) {}
    public void setVar(int p0, android.renderscript.FieldPacker p1, android.renderscript.Element p2, int[] p3) {}
    public void setVar(int p0, boolean p1) {}
    protected Script() { super(); }
    public static class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected Builder() {}
    }
    public static class FieldBase {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected android.renderscript.Allocation mAllocation;
        protected android.renderscript.Element mElement;
        protected FieldBase() {}
        public android.renderscript.Allocation getAllocation() { return (android.renderscript.Allocation) huskProps.get("Allocation"); }
        public android.renderscript.Element getElement() { return (android.renderscript.Element) huskProps.get("Element"); }
        public android.renderscript.Type getType() { return (android.renderscript.Type) huskProps.get("Type"); }
        protected void init(android.renderscript.RenderScript p0, int p1) {}
        protected void init(android.renderscript.RenderScript p0, int p1, int p2) {}
        public void updateAllocation() {}
    }
    public static final class FieldID extends android.renderscript.BaseObj {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected FieldID() { super(); }
    }
    public static final class InvokeID extends android.renderscript.BaseObj {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected InvokeID() { super(); }
    }
    public static abstract class KernelID extends android.renderscript.BaseObj {
        protected KernelID() { super(); }
    }
    public static final class LaunchOptions {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public LaunchOptions() {}
        public int getXEnd() { return (huskProps.get("XEnd") instanceof Integer ? (Integer) huskProps.get("XEnd") : 0); }
        public int getXStart() { return (huskProps.get("XStart") instanceof Integer ? (Integer) huskProps.get("XStart") : 0); }
        public int getYEnd() { return (huskProps.get("YEnd") instanceof Integer ? (Integer) huskProps.get("YEnd") : 0); }
        public int getYStart() { return (huskProps.get("YStart") instanceof Integer ? (Integer) huskProps.get("YStart") : 0); }
        public int getZEnd() { return (huskProps.get("ZEnd") instanceof Integer ? (Integer) huskProps.get("ZEnd") : 0); }
        public int getZStart() { return (huskProps.get("ZStart") instanceof Integer ? (Integer) huskProps.get("ZStart") : 0); }
        public android.renderscript.Script.LaunchOptions setX(int p0, int p1) { return this; }
        public android.renderscript.Script.LaunchOptions setY(int p0, int p1) { return this; }
        public android.renderscript.Script.LaunchOptions setZ(int p0, int p1) { return this; }
    }
}
