// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.devicelock;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DeviceLockManager {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int DEVICE_LOCK_ROLE_FINANCING = 0;
    public static final int ENROLLMENT_TYPE_FINANCE = 1;
    public static final int ENROLLMENT_TYPE_NONE = 0;
    public static final int ENROLLMENT_TYPE_SUBSIDY = 2;
    public static final java.lang.String EXTRA_DEVICE_LOCK_VERSION = "android.devicelock.extra.DEVICE_LOCK_VERSION";
    public DeviceLockManager(android.content.Context p0, android.devicelock.IDeviceLockService p1) {}
    public void clearDeviceRestrictions(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void getDeviceId(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void getEnrollmentType(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void getKioskApps(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public android.devicelock.IDeviceLockService getService() { return (android.devicelock.IDeviceLockService) huskProps.get("Service"); }
    public void isDeviceLocked(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void lockDevice(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void notifyKioskSetupFinished(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    public void unlockDevice(java.util.concurrent.Executor p0, android.os.OutcomeReceiver p1) {}
    DeviceLockManager() { this((android.content.Context) null, (android.devicelock.IDeviceLockService) null); }
}
