// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.rtt;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class SecureRangingConfig implements android.os.Parcelable {
    protected SecureRangingConfig() {}
}
