// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view.textservice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class SpellCheckerInfo implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public SpellCheckerInfo(android.content.Context p0, android.content.pm.ResolveInfo p1) {}
    public SpellCheckerInfo(android.os.Parcel p0) {}
    public int describeContents() { return 0; }
    public void dump(java.io.PrintWriter p0, java.lang.String p1) {}
    public android.content.ComponentName getComponent() { return (android.content.ComponentName) huskProps.get("Component"); }
    public java.lang.String getId() { return (java.lang.String) huskProps.get("Id"); }
    public java.lang.String getPackageName() { return (java.lang.String) huskProps.get("PackageName"); }
    public android.content.pm.ServiceInfo getServiceInfo() { return (android.content.pm.ServiceInfo) huskProps.get("ServiceInfo"); }
    public java.lang.String getSettingsActivity() { return (java.lang.String) huskProps.get("SettingsActivity"); }
    public android.view.textservice.SpellCheckerSubtype getSubtypeAt(int p0) { return null; }
    public int getSubtypeCount() { return (huskProps.get("SubtypeCount") instanceof Integer ? (Integer) huskProps.get("SubtypeCount") : 0); }
    public android.graphics.drawable.Drawable loadIcon(android.content.pm.PackageManager p0) { return null; }
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    SpellCheckerInfo() { this((android.os.Parcel) null); }
}
