package android.net;
public class LinkAddress { public java.net.InetAddress getAddress() { return null; } public int getPrefixLength() { return 0; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public LinkAddress() {}
    public static android.os.Parcelable.Creator CREATOR;
    public static final long LIFETIME_PERMANENT = 9223372036854775807L;
    public static final long LIFETIME_UNKNOWN = -1L;
    public LinkAddress(java.lang.String p0) { this(); }
    public LinkAddress(java.lang.String p0, int p1, int p2) { this(); }
    public LinkAddress(java.net.InetAddress p0, int p1) { this(); }
    public LinkAddress(java.net.InetAddress p0, int p1, int p2, int p3) { this(); }
    public LinkAddress(java.net.InetAddress p0, int p1, int p2, int p3, long p4, long p5) { this(); }
    public LinkAddress(java.net.InterfaceAddress p0) { this(); }
    public int describeContents() { return 0; }
    public long getDeprecationTime() { return 0L; }
    public long getExpirationTime() { return 0L; }
    public int getFlags() { return 0; }
    public int getNetworkPrefixLength() { return 0; }
    public int getScope() { return 0; }
    public boolean isGlobalPreferred() { return false; }
    public boolean isIPv6() { return false; }
    public boolean isIpv4() { return false; }
    public boolean isIpv6() { return false; }
    public boolean isPreferred() { return false; }
    public boolean isSameAddressAs(android.net.LinkAddress p0) { return false; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    // ---- end of generated members
}
