// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.credentials;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class CreateEntry implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public CreateEntry(android.app.slice.Slice p0) {}
    public int describeContents() { return 0; }
    public android.app.slice.Slice getSlice() { return (android.app.slice.Slice) huskProps.get("Slice"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
