// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class WindowAnimationFrameStats extends android.view.FrameStats implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public WindowAnimationFrameStats() { super(); }
    public int describeContents() { return 0; }
    public void init(long p0, long[] p1) {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
