package android.util;

/** A statsd atom. Nothing collects them here: the builder takes every field and builds an empty event (conscrypt counts TLS
 *  handshakes through this, and a null builder would fail the connection). */
public final class StatsEvent {
    private final int mAtomId;
    private StatsEvent(int atomId) { mAtomId = atomId; }
    public static Builder newBuilder() { return new Builder(); }
    public int getAtomId() { return mAtomId; }
    public byte[] getBytes() { return new byte[0]; }
    public int getNumBytes() { return 0; }
    public void release() {}

    public static final class Builder {
        private int mAtomId;
        private Builder() {}
        public Builder setAtomId(int id) { mAtomId = id; return this; }
        public Builder writeBoolean(boolean v) { return this; }
        public Builder writeInt(int v) { return this; }
        public Builder writeLong(long v) { return this; }
        public Builder writeFloat(float v) { return this; }
        public Builder writeString(String v) { return this; }
        public Builder writeByteArray(byte[] v) { return this; }
        public Builder writeIntArray(int[] v) { return this; }
        public Builder writeLongArray(long[] v) { return this; }
        public Builder writeFloatArray(float[] v) { return this; }
        public Builder writeBooleanArray(boolean[] v) { return this; }
        public Builder writeStringArray(String[] v) { return this; }
        public Builder writeAttributionChain(int[] uids, String[] tags) { return this; }
        public Builder writeKeyValuePairs(SparseIntArray i, SparseLongArray l, SparseArray<String> s, SparseArray<Float> f) { return this; }
        public Builder addBooleanAnnotation(byte id, boolean v) { return this; }
        public Builder addIntAnnotation(byte id, int v) { return this; }
        public Builder usePooledBuffer() { return this; }
        public StatsEvent build() { return new StatsEvent(mAtomId); }
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final int ERROR_ANNOTATION_DOES_NOT_FOLLOW_FIELD = 32;
    public static final int ERROR_ANNOTATION_ID_TOO_LARGE = 128;
    public static final int ERROR_ATOM_ID_INVALID_POSITION = 8192;
    public static final int ERROR_ATTRIBUTION_CHAIN_TOO_LONG = 8;
    public static final int ERROR_ATTRIBUTION_UIDS_TAGS_SIZES_NOT_EQUAL = 4096;
    public static final int ERROR_INVALID_ANNOTATION_ID = 64;
    public static final int ERROR_LIST_TOO_LONG = 16384;
    public static final int ERROR_NO_ATOM_ID = 2;
    public static final int ERROR_NO_TIMESTAMP = 1;
    public static final int ERROR_OVERFLOW = 4;
    public static final int ERROR_TOO_MANY_ANNOTATIONS = 256;
    public static final int ERROR_TOO_MANY_FIELDS = 512;
    public static final int ERROR_TOO_MANY_KEY_VALUE_PAIRS = 16;
    public static final int MAX_ANNOTATION_COUNT = 15;
    public static final int MAX_ATTRIBUTION_NODES = 127;
    public static final int MAX_KEY_VALUE_PAIRS = 127;
    public static final int MAX_NUM_ELEMENTS = 127;
    public static final byte TYPE_ATTRIBUTION_CHAIN = (byte) 9;
    public static final byte TYPE_BOOLEAN = (byte) 5;
    public static final byte TYPE_BYTE_ARRAY = (byte) 6;
    public static final byte TYPE_ERRORS = (byte) 15;
    public static final byte TYPE_FLOAT = (byte) 4;
    public static final byte TYPE_INT = (byte) 0;
    public static final byte TYPE_KEY_VALUE_PAIRS = (byte) 8;
    public static final byte TYPE_LIST = (byte) 3;
    public static final byte TYPE_LONG = (byte) 1;
    public static final byte TYPE_OBJECT = (byte) 7;
    public static final byte TYPE_STRING = (byte) 2;
    // ---- end of generated members
}
