// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.hardware.soundtrigger;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class KeyphraseEnrollmentInfo {
    protected KeyphraseEnrollmentInfo() {}
}
