// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.print;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class PrintJob {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public void cancel() {}
    public android.print.PrintJobId getId() { return (android.print.PrintJobId) huskProps.get("Id"); }
    public android.print.PrintJobInfo getInfo() { return (android.print.PrintJobInfo) huskProps.get("Info"); }
    public boolean isBlocked() { return (huskProps.get("Blocked") instanceof Boolean ? (Boolean) huskProps.get("Blocked") : false); }
    public boolean isCancelled() { return (huskProps.get("Cancelled") instanceof Boolean ? (Boolean) huskProps.get("Cancelled") : false); }
    public boolean isCompleted() { return (huskProps.get("Completed") instanceof Boolean ? (Boolean) huskProps.get("Completed") : false); }
    public boolean isFailed() { return (huskProps.get("Failed") instanceof Boolean ? (Boolean) huskProps.get("Failed") : false); }
    public boolean isQueued() { return (huskProps.get("Queued") instanceof Boolean ? (Boolean) huskProps.get("Queued") : false); }
    public boolean isStarted() { return (huskProps.get("Started") instanceof Boolean ? (Boolean) huskProps.get("Started") : false); }
    public void restart() {}
    protected PrintJob() {}
}
