package android.view.animation;
public class AnticipateInterpolator extends BaseInterpolator {
    private final float k;
    public AnticipateInterpolator() { this(2); }
    public AnticipateInterpolator(float tension) { k = tension; }
    public AnticipateInterpolator(android.content.Context c, android.util.AttributeSet a) { this(2); }
    public float getInterpolation(float t) { return t * t * ((k + 1) * t - k); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public AnticipateInterpolator(android.content.res.Resources p0, android.content.res.Resources.Theme p1, android.util.AttributeSet p2) { this(); }
    public long createNativeInterpolator() { return 0L; }
    // ---- end of generated members
}
