package android.text;
public interface InputType {
    int TYPE_MASK_CLASS = 0xf, TYPE_MASK_VARIATION = 0xff0, TYPE_MASK_FLAGS = 0xfff000, TYPE_NULL = 0, TYPE_CLASS_TEXT = 1, TYPE_TEXT_FLAG_CAP_CHARACTERS = 0x1000,
        TYPE_TEXT_FLAG_CAP_WORDS = 0x2000, TYPE_TEXT_FLAG_CAP_SENTENCES = 0x4000, TYPE_TEXT_FLAG_AUTO_CORRECT = 0x8000, TYPE_TEXT_FLAG_AUTO_COMPLETE = 0x10000,
        TYPE_TEXT_FLAG_MULTI_LINE = 0x20000, TYPE_TEXT_FLAG_IME_MULTI_LINE = 0x40000, TYPE_TEXT_FLAG_NO_SUGGESTIONS = 0x80000, TYPE_TEXT_FLAG_ENABLE_TEXT_CONVERSION_SUGGESTIONS = 0x100000,
        TYPE_TEXT_VARIATION_NORMAL = 0, TYPE_TEXT_VARIATION_URI = 0x10, TYPE_TEXT_VARIATION_EMAIL_ADDRESS = 0x20, TYPE_TEXT_VARIATION_EMAIL_SUBJECT = 0x30,
        TYPE_TEXT_VARIATION_SHORT_MESSAGE = 0x40, TYPE_TEXT_VARIATION_LONG_MESSAGE = 0x50, TYPE_TEXT_VARIATION_PERSON_NAME = 0x60, TYPE_TEXT_VARIATION_POSTAL_ADDRESS = 0x70,
        TYPE_TEXT_VARIATION_PASSWORD = 0x80, TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = 0x90, TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = 0xa0, TYPE_TEXT_VARIATION_FILTER = 0xb0,
        TYPE_TEXT_VARIATION_PHONETIC = 0xc0, TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = 0xd0, TYPE_TEXT_VARIATION_WEB_PASSWORD = 0xe0, TYPE_CLASS_NUMBER = 2,
        TYPE_NUMBER_FLAG_SIGNED = 0x1000, TYPE_NUMBER_FLAG_DECIMAL = 0x2000, TYPE_NUMBER_VARIATION_NORMAL = 0, TYPE_NUMBER_VARIATION_PASSWORD = 0x10, TYPE_CLASS_PHONE = 3,
        TYPE_CLASS_DATETIME = 4, TYPE_DATETIME_VARIATION_NORMAL = 0, TYPE_DATETIME_VARIATION_DATE = 0x10, TYPE_DATETIME_VARIATION_TIME = 0x20;
}
