// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.notification;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface IDispatchCompletionListener extends android.os.IInterface {
}
