// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view.inspector;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface PropertyMapper {
    int mapBoolean(java.lang.String p0, int p1);
    int mapByte(java.lang.String p0, int p1);
    int mapChar(java.lang.String p0, int p1);
    int mapColor(java.lang.String p0, int p1);
    int mapDouble(java.lang.String p0, int p1);
    int mapFloat(java.lang.String p0, int p1);
    int mapGravity(java.lang.String p0, int p1);
    int mapInt(java.lang.String p0, int p1);
    int mapIntEnum(java.lang.String p0, int p1, java.util.function.IntFunction p2);
    int mapIntFlag(java.lang.String p0, int p1, java.util.function.IntFunction p2);
    int mapLong(java.lang.String p0, int p1);
    int mapObject(java.lang.String p0, int p1);
    int mapResourceId(java.lang.String p0, int p1);
    int mapShort(java.lang.String p0, int p1);
    public static class PropertyConflictException extends java.lang.RuntimeException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public PropertyConflictException(java.lang.String p0, java.lang.String p1, java.lang.String p2) { super(); }
        PropertyConflictException() { this((java.lang.String) null, (java.lang.String) null, (java.lang.String) null); }
    }
}
