// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.webkit;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface WebResourceRequest {
    java.lang.String getMethod();
    java.util.Map getRequestHeaders();
    android.net.Uri getUrl();
    boolean hasGesture();
    boolean isForMainFrame();
    boolean isRedirect();
}
