// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.webkit;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class WebResourceError {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public WebResourceError() {}
    public abstract java.lang.CharSequence getDescription();
    public abstract int getErrorCode();
}
