// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.content.pm;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ArchivedActivityInfo {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ArchivedActivityInfo(java.lang.CharSequence p0, android.content.ComponentName p1) {}
    public static byte[] bytesFromBitmap(android.graphics.Bitmap p0) { return null; }
    public static android.graphics.Bitmap drawableToBitmap(android.graphics.drawable.Drawable p0) { return null; }
    public static android.graphics.Bitmap drawableToBitmap(android.graphics.drawable.Drawable p0, int p1) { return null; }
    public android.content.ComponentName getComponentName() { return (android.content.ComponentName) huskProps.get("ComponentName"); }
    public android.graphics.drawable.Drawable getIcon() { return (android.graphics.drawable.Drawable) huskProps.get("Icon"); }
    public java.lang.CharSequence getLabel() { return (java.lang.CharSequence) huskProps.get("Label"); }
    public android.graphics.drawable.Drawable getMonochromeIcon() { return (android.graphics.drawable.Drawable) huskProps.get("MonochromeIcon"); }
    public android.content.pm.ArchivedActivityInfo setComponentName(android.content.ComponentName p0) { huskProps.put("ComponentName", p0); return this; }
    public android.content.pm.ArchivedActivityInfo setIcon(android.graphics.drawable.Drawable p0) { huskProps.put("Icon", p0); return this; }
    public android.content.pm.ArchivedActivityInfo setLabel(java.lang.CharSequence p0) { huskProps.put("Label", p0); return this; }
    public android.content.pm.ArchivedActivityInfo setMonochromeIcon(android.graphics.drawable.Drawable p0) { huskProps.put("MonochromeIcon", p0); return this; }
}
