// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.credentials;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class Credential implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final java.lang.String TYPE_PASSWORD_CREDENTIAL = "android.credentials.TYPE_PASSWORD_CREDENTIAL";
    public Credential(java.lang.String p0, android.os.Bundle p1) {}
    public int describeContents() { return 0; }
    public android.os.Bundle getData() { return (android.os.Bundle) huskProps.get("Data"); }
    public java.lang.String getType() { return (java.lang.String) huskProps.get("Type"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
