// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect.internal.datatypes;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class StepsRecordInternal extends android.health.connect.internal.datatypes.IntervalRecordInternal {
    protected StepsRecordInternal() { super(); }
}
