package android.view;

import android.util.DisplayMetrics;

public class Display {
    public static final int DEFAULT_DISPLAY = 0, INVALID_DISPLAY = -1, STATE_UNKNOWN = 0, STATE_OFF = 1, STATE_ON = 2, FLAG_SECURE = 2, FLAG_ROUND = 16;
    public void getMetrics(DisplayMetrics m) { m.setToDefaults(); }
    public void getRealMetrics(DisplayMetrics m) { m.setToDefaults(); }
    public void getSize(android.graphics.Point p) { p.x = husk.Native.screenWidth(); p.y = husk.Native.screenHeight(); }
    public void getRealSize(android.graphics.Point p) { getSize(p); }
    public void getRectSize(android.graphics.Rect r) { r.set(0, 0, husk.Native.screenWidth(), husk.Native.screenHeight()); }
    public void getCurrentSizeRange(android.graphics.Point small, android.graphics.Point large) { int w = husk.Native.screenWidth(), h = husk.Native.screenHeight(); small.set(Math.min(w, h), Math.min(w, h)); large.set(Math.max(w, h), Math.max(w, h)); }
    public int getWidth() { return husk.Native.screenWidth(); }
    public int getHeight() { return husk.Native.screenHeight(); }
    public int getRotation() { return 0; }
    @Deprecated public int getOrientation() { return 0; }
    public float getRefreshRate() { return 60f; }
    public float[] getSupportedRefreshRates() { return new float[] { 60f }; }
    public int getDisplayId() { return 0; }
    public String getName() { return "Built-in Screen"; }
    public int getState() { return STATE_ON; }
    public int getFlags() { return 0; }
    public boolean isValid() { return true; }
    public boolean isHdr() { return false; }
    public boolean isWideColorGamut() { return false; }
    public int getPixelFormat() { return android.graphics.PixelFormat.RGBA_8888; }
    public long getAppVsyncOffsetNanos() { return 0; }
    public long getPresentationDeadlineNanos() { return 16_666_667L; }
    public DisplayCutout getCutout() { return husk.ViewRoot.cutout(); }
    public HdrCapabilities getHdrCapabilities() { return null; }
    public static final class HdrCapabilities { public int[] getSupportedHdrTypes() { return new int[0]; }
        // ---- generated by tools/compat/fillmembers.py (HdrCapabilities): the platform's members this class does not write (signatures only)
        public HdrCapabilities() {}
        public static android.os.Parcelable.Creator CREATOR;
        public static int[] HDR_TYPES;
        public static final int HDR_TYPE_DOLBY_VISION = 1;
        public static final int HDR_TYPE_HDR10 = 2;
        public static final int HDR_TYPE_HDR10_PLUS = 4;
        public static final int HDR_TYPE_HLG = 3;
        public static final int HDR_TYPE_INVALID = -1;
        public static final float INVALID_LUMINANCE = -1.0f;
        public HdrCapabilities(int[] p0, float p1, float p2, float p3) { this(); }
        public static java.lang.String hdrTypeToString(int p0) { return null; }
        public int describeContents() { return 0; }
        public float getDesiredMaxAverageLuminance() { return 0f; }
        public float getDesiredMaxLuminance() { return 0f; }
        public float getDesiredMinLuminance() { return 0f; }
        public void readFromParcel(android.os.Parcel p0) {}
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        // ---- end of generated members (HdrCapabilities)
    }
    public Mode getMode() { return new Mode(); }
    public Mode[] getSupportedModes() { return new Mode[] { new Mode() }; }
    public static final class Mode {
        public int getModeId() { return 1; } public int getPhysicalWidth() { return husk.Native.screenWidth(); }
        public int getPhysicalHeight() { return husk.Native.screenHeight(); } public float getRefreshRate() { return 60f; }
        public float[] getAlternativeRefreshRates() { return new float[0]; }
        // ---- generated by tools/compat/fillmembers.py (Mode): the platform's members this class does not write (signatures only)
        public Mode() {}
        public static android.os.Parcelable.Creator CREATOR;
        public static android.view.Display.Mode[] EMPTY_ARRAY;
        public static final int FLAG_ANISOTROPY_CORRECTION = 4;
        public static final int FLAG_ARR_RENDER_RATE = 1;
        public static final int FLAG_SIZE_OVERRIDE = 2;
        public static final int INVALID_MODE_ID = -1;
        public Mode(int p0, int p1, float p2) { this(); }
        public Mode(int p0, int p1, int p2, float p3) { this(); }
        public Mode(int p0, int p1, int p2, float p3, float p4, float[] p5, int[] p6) { this(); }
        public Mode(int p0, int p1, int p2, float p3, float[] p4, int[] p5) { this(); }
        public Mode(int p0, int p1, int p2, int p3, int p4, float p5, float p6, float[] p7, int[] p8) { this(); }
        public int describeContents() { return 0; }
        public boolean equalsExceptRefreshRate(android.view.Display.Mode p0) { return false; }
        public int getFlags() { return 0; }
        public int getParentModeId() { return 0; }
        public int[] getSupportedHdrTypes() { return null; }
        public float getVsyncRate() { return 0f; }
        public boolean isRefreshRateSet() { return false; }
        public boolean isResolutionSet() { return false; }
        public boolean isSynthetic() { return false; }
        public boolean matches(int p0, int p1, float p2) { return false; }
        public boolean matchesIfValid(int p0, int p1, float p2) { return false; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        // ---- end of generated members (Mode)
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final int COLOR_MODE_ADOBE_RGB = 8;
    public static final int COLOR_MODE_BT601_525 = 3;
    public static final int COLOR_MODE_BT601_525_UNADJUSTED = 4;
    public static final int COLOR_MODE_BT601_625 = 1;
    public static final int COLOR_MODE_BT601_625_UNADJUSTED = 2;
    public static final int COLOR_MODE_BT709 = 5;
    public static final int COLOR_MODE_DCI_P3 = 6;
    public static final int COLOR_MODE_DEFAULT = 0;
    public static final int COLOR_MODE_DISPLAY_P3 = 9;
    public static final int COLOR_MODE_INVALID = -1;
    public static final int COLOR_MODE_SRGB = 7;
    public static final int DEFAULT_DISPLAY_GROUP = 0;
    public static final int DISPLAY_MODE_ID_FOR_FRAME_RATE_OVERRIDE = 255;
    public static final int FLAG_ALLOWS_CONTENT_MODE_SWITCH = 32768;
    public static final int FLAG_ALWAYS_UNLOCKED = 512;
    public static final int FLAG_CAN_SHOW_WITH_INSECURE_KEYGUARD = 32;
    public static final int FLAG_OWN_DISPLAY_GROUP = 256;
    public static final int FLAG_OWN_FOCUS = 2048;
    public static final int FLAG_PRESENTATION = 8;
    public static final int FLAG_PRIVATE = 4;
    public static final int FLAG_REAR = 8192;
    public static final int FLAG_ROTATES_WITH_CONTENT = 16384;
    public static final int FLAG_SCALING_DISABLED = 1073741824;
    public static final int FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS = 64;
    public static final int FLAG_STEAL_TOP_FOCUS_DISABLED = 4096;
    public static final int FLAG_SUPPORTS_PROTECTED_BUFFERS = 1;
    public static final int FLAG_TOUCH_FEEDBACK_DISABLED = 1024;
    public static final int FLAG_TRUSTED = 128;
    public static final int FRAME_RATE_CATEGORY_HIGH = 1;
    public static final int FRAME_RATE_CATEGORY_NORMAL = 0;
    public static final int INVALID_DISPLAY_GROUP = -1;
    public static final int INVALID_DISPLAY_HEIGHT = -1;
    public static final float INVALID_DISPLAY_REFRESH_RATE = 0.0f;
    public static final int INVALID_DISPLAY_WIDTH = -1;
    public static final int REMOVE_MODE_DESTROY_CONTENT = 1;
    public static final int REMOVE_MODE_MOVE_CONTENT_TO_PRIMARY = 0;
    public static final int STATE_DOZE = 3;
    public static final int STATE_DOZE_SUSPEND = 4;
    public static final int STATE_ON_SUSPEND = 6;
    public static final int STATE_REASON_DEFAULT_POLICY = 1;
    public static final int STATE_REASON_DRAW_WAKE_LOCK = 2;
    public static final int STATE_REASON_DREAM_MANAGER = 5;
    public static final int STATE_REASON_KEY = 6;
    public static final int STATE_REASON_MOTION = 7;
    public static final int STATE_REASON_OFFLOAD = 3;
    public static final int STATE_REASON_TILT = 4;
    public static final int STATE_REASON_UNKNOWN = 0;
    public static final int STATE_VR = 5;
    public static final int TYPE_EXTERNAL = 2;
    public static final int TYPE_INTERNAL = 1;
    public static final int TYPE_MAX = 5;
    public static final int TYPE_OVERLAY = 4;
    public static final int TYPE_UNKNOWN = 0;
    public static final int TYPE_VIRTUAL = 5;
    public static final int TYPE_WIFI = 3;
    public static boolean hasAccess(int p0, int p1, int p2, int p3) { return false; }
    public static boolean isActiveState(int p0) { return false; }
    public static boolean isDozeState(int p0) { return false; }
    public static boolean isHeightValid(int p0) { return false; }
    public static boolean isOffState(int p0) { return false; }
    public static boolean isOnState(int p0) { return false; }
    public static boolean isRefreshRateValid(float p0) { return false; }
    public static boolean isSuspendedState(int p0) { return false; }
    public static boolean isWidthValid(int p0) { return false; }
    public static java.lang.String stateReasonToString(int p0) { return null; }
    public static java.lang.String stateToString(int p0) { return null; }
    public static java.lang.String typeToString(int p0) { return null; }
    public boolean canHostTasks() { return false; }
    public boolean canStealTopFocus() { return false; }
    public void clearUserPreferredDisplayMode() {}
    public float getBrightnessDefault() { return 0f; }
    public int getColorMode() { return 0; }
    public int getCommittedState() { return 0; }
    public android.view.Display.Mode getDefaultMode() { return null; }
    public android.hardware.display.DeviceProductInfo getDeviceProductInfo() { return null; }
    public float getHdrSdrRatio() { return 0f; }
    public float getHighestHdrSdrRatio() { return 0f; }
    public int getInstallOrientation() { return 0; }
    public int getLayerStack() { return 0; }
    public int getMaximumSizeDimension() { return 0; }
    public float getMinSizeDimensionDp() { return 0f; }
    public android.hardware.OverlayProperties getOverlaySupport() { return null; }
    public java.lang.String getOwnerPackageName() { return null; }
    public int getOwnerUid() { return 0; }
    public android.graphics.ColorSpace getPreferredWideGamutColorSpace() { return null; }
    public int getRemoveMode() { return 0; }
    public int[] getReportedHdrTypes() { return null; }
    public android.view.RoundedCorner getRoundedCorner(int p0) { return null; }
    public android.view.DisplayShape getShape() { return null; }
    public float getSuggestedFrameRate(int p0) { return 0f; }
    public int[] getSupportedColorModes() { return null; }
    public float[] getSupportedRefreshRatesLegacy() { return null; }
    public android.graphics.ColorSpace[] getSupportedWideColorGamut() { return null; }
    public android.view.Display.Mode getSystemPreferredDisplayMode() { return null; }
    public android.view.Display.Mode[] getSystemSupportedModes() { return null; }
    public int getType() { return 0; }
    public java.lang.String getUniqueId() { return null; }
    public android.view.Display.Mode getUserPreferredDisplayMode() { return (android.view.Display.Mode) huskFill.get("UserPreferredDisplayMode"); }
    public boolean hasAccess(int p0) { return false; }
    public boolean hasArrSupport() { return false; }
    public boolean isHdrSdrRatioAvailable() { return false; }
    public boolean isInternal() { return false; }
    public boolean isMinimalPostProcessingSupported() { return false; }
    public boolean isPublicPresentation() { return false; }
    public boolean isTrusted() { return false; }
    public void registerHdrSdrRatioChangedListener(java.util.concurrent.Executor p0, java.util.function.Consumer p1) {}
    public void requestColorMode(int p0) {}
    public void resetUserPreferredDisplayMode() {}
    public void setUserPreferredDisplayMode(android.view.Display.Mode p0) { huskFill.put("UserPreferredDisplayMode", p0); }
    public void setUserPreferredDisplayMode(android.view.Display.Mode p0, boolean p1) {}
    public void unregisterHdrSdrRatioChangedListener(java.util.function.Consumer p0) {}
    // ---- end of generated members
}
