package android.view;
public class DragEvent {
    public static final int ACTION_DRAG_STARTED = 1, ACTION_DRAG_LOCATION = 2, ACTION_DROP = 3, ACTION_DRAG_ENDED = 4, ACTION_DRAG_ENTERED = 5, ACTION_DRAG_EXITED = 6;
    public int getAction() { return 0; } public float getX() { return 0; } public float getY() { return 0; }
    public android.content.ClipData getClipData() { return null; } public android.content.ClipDescription getClipDescription() { return null; }
    public Object getLocalState() { return null; } public boolean getResult() { return false; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static android.os.Parcelable.Creator CREATOR;
    public static java.lang.String actionToString(int p0) { return null; }
    public static android.view.DragEvent obtain(android.view.DragEvent p0) { return null; }
    public int describeContents() { return 0; }
    public int getDisplayId() { return 0; }
    public int getDragFlags() { return 0; }
    public android.view.SurfaceControl getDragSurface() { return null; }
    public float getOffsetX() { return 0f; }
    public float getOffsetY() { return 0f; }
    public void recycle() {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    // ---- end of generated members
}
