package android.view;
public class HapticFeedbackConstants {
    public static final int LONG_PRESS = 0, VIRTUAL_KEY = 1, KEYBOARD_TAP = 3, CLOCK_TICK = 4, CONTEXT_CLICK = 6, KEYBOARD_PRESS = 3, KEYBOARD_RELEASE = 7,
        VIRTUAL_KEY_RELEASE = 8, TEXT_HANDLE_MOVE = 9, GESTURE_START = 12, GESTURE_END = 13, CONFIRM = 16, REJECT = 17, TOGGLE_ON = 21, TOGGLE_OFF = 22,
        FLAG_IGNORE_VIEW_SETTING = 1, FLAG_IGNORE_GLOBAL_SETTING = 2;
}
