package android.view;
public final class SurfaceControl implements android.os.Parcelable {
    public static class Transaction implements java.io.Closeable { public void apply() {} public void apply(boolean sync) {} public void close() {} public Transaction setVisibility(SurfaceControl s, boolean v) { return this; } public Transaction setAlpha(SurfaceControl s, float a) { return this; } public Transaction setLayer(SurfaceControl s, int z) { return this; } public Transaction setBufferSize(SurfaceControl s, int w, int h) { return this; } public Transaction reparent(SurfaceControl s, SurfaceControl p) { return this; } public Transaction merge(Transaction o) { return this; }
        // ---- generated by tools/compat/fillmembers.py (Transaction): the platform's members this class does not write (signatures only)
        public static android.os.Parcelable.Creator CREATOR;
        public long mNativeObject;
        public static android.os.IBinder getDefaultApplyToken() { return null; }
        public static void sendSurfaceFlushJankData(android.view.SurfaceControl p0) {}
        public static void setDefaultApplyToken(android.os.IBinder p0) {}
        public android.view.SurfaceControl.Transaction addTransactionCompletedListener(java.util.concurrent.Executor p0, java.util.function.Consumer p1) { return this; }
        public android.view.SurfaceControl.Transaction addWindowInfosReportedListener(java.lang.Runnable p0) { return this; }
        public void applyAsyncUnsafe() {}
        protected void applyResizedSurfaces() {}
        protected void checkPreconditions(android.view.SurfaceControl p0) {}
        public void clear() {}
        public android.view.SurfaceControl.Transaction clearFrameRate(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction clearTrustedPresentationCallback(android.view.SurfaceControl p0) { return this; }
        public int describeContents() { return 0; }
        public long getId() { return 0L; }
        public android.view.SurfaceControl.Transaction hide(android.view.SurfaceControl p0) { return this; }
        protected void notifyReparentedSurfaces() {}
        public android.view.SurfaceControl.Transaction remove(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction removeCurrentInputFocus(int p0) { return this; }
        public void sanitize(int p0, int p1) {}
        public android.view.SurfaceControl.Transaction setAnimationTransaction() { return this; }
        public android.view.SurfaceControl.Transaction setBackgroundBlurRadius(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setBackgroundBlurScale(android.view.SurfaceControl p0, float p1) { return this; }
        public android.view.SurfaceControl.Transaction setBlurRegions(android.view.SurfaceControl p0, float[][] p1) { return this; }
        public android.view.SurfaceControl.Transaction setBuffer(android.view.SurfaceControl p0, android.graphics.GraphicBuffer p1) { return this; }
        public android.view.SurfaceControl.Transaction setBuffer(android.view.SurfaceControl p0, android.hardware.HardwareBuffer p1) { return this; }
        public android.view.SurfaceControl.Transaction setBuffer(android.view.SurfaceControl p0, android.hardware.HardwareBuffer p1, android.hardware.SyncFence p2) { return this; }
        public android.view.SurfaceControl.Transaction setBuffer(android.view.SurfaceControl p0, android.hardware.HardwareBuffer p1, android.hardware.SyncFence p2, java.util.function.Consumer p3) { return this; }
        public android.view.SurfaceControl.Transaction setBufferTransform(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setCachingHint(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setCanOccludePresentation(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setClientDrawnCornerRadius(android.view.SurfaceControl p0, float p1, float p2, float p3, float p4, android.graphics.RectF p5) { return this; }
        public android.view.SurfaceControl.Transaction setColor(android.view.SurfaceControl p0, float[] p1) { return this; }
        public android.view.SurfaceControl.Transaction setColorSpace(android.view.SurfaceControl p0, android.graphics.ColorSpace p1) { return this; }
        public android.view.SurfaceControl.Transaction setColorSpaceAgnostic(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setColorTransform(android.view.SurfaceControl p0, float[] p1, float[] p2) { return this; }
        public android.view.SurfaceControl.Transaction setContentPriority(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setCornerRadius(android.view.SurfaceControl p0, float p1) { return this; }
        public android.view.SurfaceControl.Transaction setCornerRadius(android.view.SurfaceControl p0, float p1, float p2, float p3, float p4) { return this; }
        public android.view.SurfaceControl.Transaction setCrop(android.view.SurfaceControl p0, float p1, float p2, float p3, float p4) { return this; }
        public android.view.SurfaceControl.Transaction setCrop(android.view.SurfaceControl p0, android.graphics.Rect p1) { return this; }
        public android.view.SurfaceControl.Transaction setDamageRegion(android.view.SurfaceControl p0, android.graphics.Region p1) { return this; }
        public android.view.SurfaceControl.Transaction setDataSpace(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setDefaultFrameRateCompatibility(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setDesiredHdrHeadroom(android.view.SurfaceControl p0, float p1) { return this; }
        public android.view.SurfaceControl.Transaction setDesiredPresentTimeNanos(long p0) { return this; }
        public android.view.SurfaceControl.Transaction setDestinationFrame(android.view.SurfaceControl p0, int p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setDestinationFrame(android.view.SurfaceControl p0, android.graphics.Rect p1) { return this; }
        public android.view.SurfaceControl.Transaction setDimmingEnabled(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setDisplayDecoration(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setDisplayFlags(android.os.IBinder p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setDisplayLayerStack(android.os.IBinder p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setDisplayProjection(android.os.IBinder p0, int p1, android.graphics.Rect p2, android.graphics.Rect p3) { return this; }
        public android.view.SurfaceControl.Transaction setDisplaySize(android.os.IBinder p0, int p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setDisplaySurface(android.os.IBinder p0, android.view.Surface p1) { return this; }
        public android.view.SurfaceControl.Transaction setDropInputMode(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setEdgeExtensionEffect(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setExtendedRangeBrightness(android.view.SurfaceControl p0, float p1, float p2) { return this; }
        public android.view.SurfaceControl.Transaction setFixedTransformHint(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setFocusedWindow(android.os.IBinder p0, java.lang.String p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setFrameRate(android.view.SurfaceControl p0, float p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setFrameRate(android.view.SurfaceControl p0, float p1, int p2, int p3) { return this; }
        public android.view.SurfaceControl.Transaction setFrameRateCategory(android.view.SurfaceControl p0, int p1, boolean p2) { return this; }
        public android.view.SurfaceControl.Transaction setFrameRateSelectionPriority(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setFrameRateSelectionStrategy(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setFrameTimeline(long p0) { return this; }
        public android.view.SurfaceControl.Transaction setFrameTimelineVsync(long p0) { return this; }
        public android.view.SurfaceControl.Transaction setGeometry(android.view.SurfaceControl p0, android.graphics.Rect p1, android.graphics.Rect p2, int p3) { return this; }
        public android.view.SurfaceControl.Transaction setLayerStack(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setMatrix(android.view.SurfaceControl p0, float p1, float p2, float p3, float p4) { return this; }
        public android.view.SurfaceControl.Transaction setMatrix(android.view.SurfaceControl p0, android.graphics.Matrix p1, float[] p2) { return this; }
        public android.view.SurfaceControl.Transaction setMetadata(android.view.SurfaceControl p0, int p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setMetadata(android.view.SurfaceControl p0, int p1, android.os.Parcel p2) { return this; }
        public android.view.SurfaceControl.Transaction setOpaque(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setPosition(android.view.SurfaceControl p0, float p1, float p2) { return this; }
        public android.view.SurfaceControl.Transaction setRecoverableFromBufferStuffing(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction setRelativeLayer(android.view.SurfaceControl p0, android.view.SurfaceControl p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setScale(android.view.SurfaceControl p0, float p1, float p2) { return this; }
        public android.view.SurfaceControl.Transaction setSecure(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setShadowRadius(android.view.SurfaceControl p0, float p1) { return this; }
        public android.view.SurfaceControl.Transaction setSkipScreenshot(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setStretchEffect(android.view.SurfaceControl p0, float p1, float p2, float p3, float p4, float p5, float p6, float p7, float p8, float p9, float p10) { return this; }
        public android.view.SurfaceControl.Transaction setSystemContentPriority(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setTransparentRegionHint(android.view.SurfaceControl p0, android.graphics.Region p1) { return this; }
        public android.view.SurfaceControl.Transaction setTrustedOverlay(android.view.SurfaceControl p0, int p1) { return this; }
        public android.view.SurfaceControl.Transaction setTrustedOverlay(android.view.SurfaceControl p0, boolean p1) { return this; }
        public android.view.SurfaceControl.Transaction setWindowCrop(android.view.SurfaceControl p0, int p1, int p2) { return this; }
        public android.view.SurfaceControl.Transaction setWindowCrop(android.view.SurfaceControl p0, android.graphics.Rect p1) { return this; }
        public android.view.SurfaceControl.Transaction show(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction unsetBuffer(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction unsetColor(android.view.SurfaceControl p0) { return this; }
        public android.view.SurfaceControl.Transaction unsetFixedTransformHint(android.view.SurfaceControl p0) { return this; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        // ---- end of generated members (Transaction)
    }
    public static class Builder { public Builder setName(String n) { return this; } public Builder setBufferSize(int w, int h) { return this; } public Builder setParent(SurfaceControl p) { return this; } public Builder setFormat(int f) { return this; } public Builder setOpaque(boolean o) { return this; } public Builder setHidden(boolean h) { return this; } public SurfaceControl build() { return new SurfaceControl(); }
        // ---- generated by tools/compat/fillmembers.py (Builder): the platform's members this class does not write (signatures only)
        public android.view.SurfaceControl.Builder setBLASTLayer() { return this; }
        public android.view.SurfaceControl.Builder setCallsite(java.lang.String p0) { return this; }
        public android.view.SurfaceControl.Builder setColorLayer() { return this; }
        public android.view.SurfaceControl.Builder setContainerLayer() { return this; }
        public android.view.SurfaceControl.Builder setEffectLayer() { return this; }
        public android.view.SurfaceControl.Builder setFlags(int p0) { return this; }
        public android.view.SurfaceControl.Builder setLocalOwnerView(android.view.View p0) { return this; }
        public android.view.SurfaceControl.Builder setMetadata(int p0, int p1) { return this; }
        public android.view.SurfaceControl.Builder setProtected(boolean p0) { return this; }
        public android.view.SurfaceControl.Builder setSecure(boolean p0) { return this; }
        // ---- end of generated members (Builder)
    }
    public boolean isValid() { return true; }
    public void release() {}
    public int describeContents() { return 0; }
    public void writeToParcel(android.os.Parcel p, int f) {}
    public static final Creator<SurfaceControl> CREATOR = new Creator<SurfaceControl>() { public SurfaceControl createFromParcel(android.os.Parcel p) { return new SurfaceControl(); } public SurfaceControl[] newArray(int n) { return new SurfaceControl[n]; } };
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public SurfaceControl() {}
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final int BUFFER_TRANSFORM_IDENTITY = 0;
    public static final int BUFFER_TRANSFORM_MIRROR_HORIZONTAL = 1;
    public static final int BUFFER_TRANSFORM_MIRROR_HORIZONTAL_ROTATE_90 = 5;
    public static final int BUFFER_TRANSFORM_MIRROR_VERTICAL = 2;
    public static final int BUFFER_TRANSFORM_MIRROR_VERTICAL_ROTATE_90 = 6;
    public static final int BUFFER_TRANSFORM_ROTATE_180 = 3;
    public static final int BUFFER_TRANSFORM_ROTATE_270 = 7;
    public static final int BUFFER_TRANSFORM_ROTATE_90 = 4;
    public static final int CACHING_DISABLED = 0;
    public static final int CACHING_ENABLED = 1;
    public static final int CAN_OCCLUDE_PRESENTATION = 4096;
    public static final int CURSOR_WINDOW = 8192;
    public static final int DISPLAY_DECORATION = 512;
    public static final int DISPLAY_RECEIVES_INPUT = 1;
    public static final int ENABLE_BACKPRESSURE = 256;
    public static final int FRAME_RATE_SELECTION_STRATEGY_OVERRIDE_CHILDREN = 1;
    public static final int FRAME_RATE_SELECTION_STRATEGY_PROPAGATE = 0;
    public static final int FRAME_RATE_SELECTION_STRATEGY_SELF = 2;
    public static final int FX_SURFACE_BLAST = 262144;
    public static final int FX_SURFACE_CONTAINER = 524288;
    public static final int FX_SURFACE_EFFECT = 131072;
    public static final int FX_SURFACE_MASK = 983040;
    public static final int FX_SURFACE_NORMAL = 0;
    public static final int HIDDEN = 4;
    public static final int IGNORE_DESTINATION_FRAME = 1024;
    public static final int LAYER_IS_REFRESH_RATE_INDICATOR = 2048;
    public static final int METADATA_ACCESSIBILITY_ID = 5;
    public static final int METADATA_GAME_MODE = 8;
    public static final int METADATA_MOUSE_CURSOR = 4;
    public static final int METADATA_OWNER_PID = 6;
    public static final int METADATA_OWNER_UID = 1;
    public static final int METADATA_TASK_ID = 3;
    public static final int METADATA_WINDOW_TYPE = 2;
    public static final int NON_PREMULTIPLIED = 256;
    public static final int NO_COLOR_FILL = 16384;
    public static final int OPAQUE = 1024;
    public static final int POWER_MODE_DOZE = 1;
    public static final int POWER_MODE_DOZE_SUSPEND = 3;
    public static final int POWER_MODE_NORMAL = 2;
    public static final int POWER_MODE_OFF = 0;
    public static final int POWER_MODE_ON_SUSPEND = 4;
    public static final int PROTECTED_APP = 2048;
    public static final int RECOVERABLE_FROM_BUFFER_STUFFING = 8192;
    public static final int SECURE = 128;
    public static final int SKIP_SCREENSHOT = 64;
    public SurfaceControl(android.view.SurfaceControl p0, java.lang.String p1) { this(); }
    public static boolean bootFinished() { return false; }
    public static boolean clearAnimationFrameStats() { return false; }
    public static void clearBootDisplayMode(android.os.IBinder p0) {}
    public static void closeTransaction() {}
    public static boolean getAnimationFrameStats(android.view.WindowAnimationFrameStats p0) { return false; }
    public static boolean getBootDisplayModeSupport() { return false; }
    public static android.graphics.ColorSpace[] getCompositionColorSpaces() { return null; }
    public static boolean getDisplayBrightnessSupport(android.os.IBinder p0) { return false; }
    public static int getGPUContextPriority() { return 0; }
    public static int getMaxPictureProfiles() { return 0; }
    public static android.hardware.OverlayProperties getOverlaySupport() { return null; }
    public static boolean getProtectedContentSupport() { return false; }
    public static android.view.SurfaceControl mirrorSurface(android.view.SurfaceControl p0) { return null; }
    public static android.view.SurfaceControl mirrorSurface(android.view.SurfaceControl p0, android.view.SurfaceControl p1) { return null; }
    public static void notifyShutdown() {}
    public static void openTransaction() {}
    public static int rotationToBufferTransform(int p0) { return 0; }
    public static boolean setActiveColorMode(android.os.IBinder p0, int p1) { return false; }
    public static void setAutoLowLatencyMode(android.os.IBinder p0, boolean p1) {}
    public static void setBootDisplayMode(android.os.IBinder p0, int p1) {}
    public static void setDebugUsageAfterRelease(boolean p0) {}
    public static boolean setDisplayBrightness(android.os.IBinder p0, float p1) { return false; }
    public static boolean setDisplayBrightness(android.os.IBinder p0, float p1, float p2, float p3, float p4) { return false; }
    public static void setDisplayPowerMode(android.os.IBinder p0, int p1) {}
    public static boolean setDisplayedContentSamplingEnabled(android.os.IBinder p0, boolean p1, int p2, int p3) { return false; }
    public static void setGameContentType(android.os.IBinder p0, boolean p1) {}
    public static void setGlobalShadowSettings(float[] p0, float[] p1, float p2, float p3, float p4) {}
    public boolean clearContentFrameStats() { return false; }
    public void copyFrom(android.view.SurfaceControl p0, java.lang.String p1) {}
    public void disconnect() {}
    public void dumpDebug(android.util.proto.ProtoOutputStream p0, long p1) {}
    public android.view.Choreographer getChoreographer() { return null; }
    public android.view.Choreographer getChoreographer(android.os.Looper p0) { return null; }
    public boolean getContentFrameStats(android.view.WindowContentFrameStats p0) { return false; }
    public int getHeight() { return 0; }
    public int getLayerId() { return 0; }
    public android.view.View getLocalOwnerView() { return null; }
    public int getTransformHint() { return (huskFill.get("TransformHint") instanceof Integer ? (Integer) huskFill.get("TransformHint") : 0); }
    public int getWidth() { return 0; }
    public boolean hasChoreographer() { return false; }
    public boolean isSameSurface(android.view.SurfaceControl p0) { return false; }
    public void readFromParcel(android.os.Parcel p0) {}
    public void resize(int p0, int p1) {}
    public void setTransformHint(int p0) { huskFill.put("TransformHint", Integer.valueOf(p0)); }
    public void setUnreleasedWarningCallSite(java.lang.String p0) {}
    // ---- end of generated members
}
