// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.hardware.camera2.params;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DeviceStateSensorOrientationMap {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final long FOLDED = 4L;
    public static long NORMAL;
    public DeviceStateSensorOrientationMap(long[] p0) {}
    public int getSensorOrientation(long p0) { return 0; }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.hardware.camera2.params.DeviceStateSensorOrientationMap.Builder addOrientationForState(long p0, long p1) { return this; }
        public android.hardware.camera2.params.DeviceStateSensorOrientationMap build() { return null; }
    }
}
