// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telephony.mbms;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DownloadProgressListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public DownloadProgressListener() {}
    public void onProgressUpdated(android.telephony.mbms.DownloadRequest p0, android.telephony.mbms.FileInfo p1, int p2, int p3, int p4, int p5) {}
}
