package android.media.session;
public final class MediaController { public MediaController(android.content.Context c, android.media.session.MediaSession.Token token) {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public void adjustVolume(int p0, int p1) {}
    public boolean controlsSameSession(android.media.session.MediaController p0) { return false; }
    public boolean dispatchMediaButtonEvent(android.view.KeyEvent p0) { return false; }
    public android.os.Bundle getExtras() { return null; }
    public long getFlags() { return 0L; }
    public android.os.Handler getHandlerForCallback(android.media.session.MediaController.Callback p0) { return null; }
    public android.media.MediaMetadata getMetadata() { return null; }
    public java.lang.String getPackageName() { return null; }
    public android.media.session.MediaController.PlaybackInfo getPlaybackInfo() { return null; }
    public android.media.session.PlaybackState getPlaybackState() { return null; }
    public java.util.List getQueue() { return new java.util.ArrayList(); }
    public java.lang.CharSequence getQueueTitle() { return null; }
    public int getRatingType() { return 0; }
    public android.app.PendingIntent getSessionActivity() { return null; }
    public android.os.Bundle getSessionInfo() { return null; }
    public android.media.session.MediaSession.Token getSessionToken() { return null; }
    public java.lang.String getTag() { return null; }
    public android.media.session.MediaController.TransportControls getTransportControls() { return null; }
    public void registerCallback(android.media.session.MediaController.Callback p0) {}
    public void registerCallback(android.media.session.MediaController.Callback p0, android.os.Handler p1) {}
    public void sendCommand(java.lang.String p0, android.os.Bundle p1, android.os.ResultReceiver p2) {}
    public void setVolumeTo(int p0, int p1) {}
    public void unregisterCallback(android.media.session.MediaController.Callback p0) {}
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static abstract class Callback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Callback() {}
        public void onAudioInfoChanged(android.media.session.MediaController.PlaybackInfo p0) {}
        public void onExtrasChanged(android.os.Bundle p0) {}
        public void onMetadataChanged(android.media.MediaMetadata p0) {}
        public void onPlaybackStateChanged(android.media.session.PlaybackState p0) {}
        public void onQueueChanged(java.util.List p0) {}
        public void onQueueTitleChanged(java.lang.CharSequence p0) {}
        public void onSessionDestroyed() {}
        public void onSessionEvent(java.lang.String p0, android.os.Bundle p1) {}
    }
    public static final class PlaybackInfo implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public static final int PLAYBACK_TYPE_LOCAL = 1;
        public static final int PLAYBACK_TYPE_REMOTE = 2;
        public PlaybackInfo(int p0, int p1, int p2, int p3, android.media.AudioAttributes p4, java.lang.String p5) {}
        public int describeContents() { return 0; }
        public android.media.AudioAttributes getAudioAttributes() { return (android.media.AudioAttributes) huskProps.get("AudioAttributes"); }
        public int getCurrentVolume() { return (huskProps.get("CurrentVolume") instanceof Integer ? (Integer) huskProps.get("CurrentVolume") : 0); }
        public int getMaxVolume() { return (huskProps.get("MaxVolume") instanceof Integer ? (Integer) huskProps.get("MaxVolume") : 0); }
        public int getPlaybackType() { return (huskProps.get("PlaybackType") instanceof Integer ? (Integer) huskProps.get("PlaybackType") : 0); }
        public int getVolumeControl() { return (huskProps.get("VolumeControl") instanceof Integer ? (Integer) huskProps.get("VolumeControl") : 0); }
        public java.lang.String getVolumeControlId() { return (java.lang.String) huskProps.get("VolumeControlId"); }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        PlaybackInfo() { this((int) 0, (int) 0, (int) 0, (int) 0, (android.media.AudioAttributes) null, (java.lang.String) null); }
    }
    public static final class TransportControls {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public void fastForward() {}
        public void pause() {}
        public void play() {}
        public void playFromMediaId(java.lang.String p0, android.os.Bundle p1) {}
        public void playFromSearch(java.lang.String p0, android.os.Bundle p1) {}
        public void playFromUri(android.net.Uri p0, android.os.Bundle p1) {}
        public void prepare() {}
        public void prepareFromMediaId(java.lang.String p0, android.os.Bundle p1) {}
        public void prepareFromSearch(java.lang.String p0, android.os.Bundle p1) {}
        public void prepareFromUri(android.net.Uri p0, android.os.Bundle p1) {}
        public void rewind() {}
        public void seekTo(long p0) {}
        public void sendCustomAction(android.media.session.PlaybackState.CustomAction p0, android.os.Bundle p1) {}
        public void sendCustomAction(java.lang.String p0, android.os.Bundle p1) {}
        public void setPlaybackSpeed(float p0) { huskProps.put("PlaybackSpeed", Float.valueOf(p0)); }
        public void setRating(android.media.Rating p0) { huskProps.put("Rating", p0); }
        public void skipToNext() {}
        public void skipToPrevious() {}
        public void skipToQueueItem(long p0) {}
        public void stop() {}
        protected TransportControls() {}
    }
    // ---- end of generated nested classes
}
