package android.text.method;
import android.text.Editable;
import android.view.KeyEvent;
import android.view.View;
public abstract class MetaKeyKeyListener {
    public static final int META_SHIFT_ON = 1, META_ALT_ON = 2, META_SYM_ON = 4, META_CAP_LOCKED = 256, META_ALT_LOCKED = 512, META_SYM_LOCKED = 1024;
    public boolean onKeyDown(View v, Editable c, int code, KeyEvent e) { return false; }
    public boolean onKeyUp(View v, Editable c, int code, KeyEvent e) { return false; }
    public void clearMetaKeyState(View v, Editable c, int s) {}
    public static void resetMetaState(android.text.Spannable t) {}
    public static int getMetaState(CharSequence t) { return 0; }
    public static int getMetaState(CharSequence t, int m) { return 0; }
    public static long resetLockedMeta(long s) { return s; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final int META_SELECTING = 2048;
    public static long adjustMetaAfterKeypress(long p0) { return 0L; }
    public static void adjustMetaAfterKeypress(android.text.Spannable p0) {}
    public static void clearMetaKeyState(android.text.Editable p0, int p1) {}
    public static int getMetaState(long p0) { return 0; }
    public static int getMetaState(long p0, int p1) { return 0; }
    public static int getMetaState(java.lang.CharSequence p0, int p1, android.view.KeyEvent p2) { return 0; }
    public static int getMetaState(java.lang.CharSequence p0, android.view.KeyEvent p1) { return 0; }
    public static long handleKeyDown(long p0, int p1, android.view.KeyEvent p2) { return 0L; }
    public static long handleKeyUp(long p0, int p1, android.view.KeyEvent p2) { return 0L; }
    public static boolean isMetaTracker(java.lang.CharSequence p0, java.lang.Object p1) { return false; }
    public static boolean isSelectingMetaTracker(java.lang.CharSequence p0, java.lang.Object p1) { return false; }
    protected static void resetLockedMeta(android.text.Spannable p0) {}
    public static void startSelecting(android.view.View p0, android.text.Spannable p1) {}
    public static void stopSelecting(android.view.View p0, android.text.Spannable p1) {}
    public long clearMetaKeyState(long p0, int p1) { return 0L; }
    // ---- end of generated members
}
