package android.text.method;
public class ScrollingMovementMethod extends BaseMovementMethod {
    private static ScrollingMovementMethod sInstance;
    public static MovementMethod getInstance() { if (sInstance == null) sInstance = new ScrollingMovementMethod(); return sInstance; }
    private float mLastY;
    @Override public boolean onTouchEvent(android.widget.TextView w, android.text.Spannable t, android.view.MotionEvent e) {
        if (e.getActionMasked() == android.view.MotionEvent.ACTION_DOWN) { mLastY = e.getY(); return true; }
        if (e.getActionMasked() == android.view.MotionEvent.ACTION_MOVE) {
            int dy = (int) (mLastY - e.getY()); mLastY = e.getY();
            int max = Math.max(0, w.getLayout() == null ? 0 : w.getLayout().getHeight() - (w.getHeight() - w.getTotalPaddingTop() - w.getTotalPaddingBottom()));
            w.scrollTo(w.getScrollX(), Math.max(0, Math.min(max, w.getScrollY() + dy)));
            return true;
        }
        return false;
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    protected boolean bottom(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean down(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean end(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean home(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean left(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean lineEnd(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean lineStart(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean pageDown(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean pageUp(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean right(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean top(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    protected boolean up(android.widget.TextView p0, android.text.Spannable p1) { return false; }
    // ---- end of generated members
}
