// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.common;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class AppInstallFilters implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final java.lang.String PACKAGE_NAMES_FIELD_NAME = "package_names";
    public static android.adservices.common.AppInstallFilters fromJson(org.json.JSONObject p0) { return new AppInstallFilters(); }
    public int describeContents() { return 0; }
    public java.util.Set getPackageNames() { return (huskProps.get("PackageNames") != null ? (java.util.Set) huskProps.get("PackageNames") : new java.util.HashSet()); }
    public int getSizeInBytes() { return (huskProps.get("SizeInBytes") instanceof Integer ? (Integer) huskProps.get("SizeInBytes") : 0); }
    public org.json.JSONObject toJson() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected AppInstallFilters() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.adservices.common.AppInstallFilters build() { android.adservices.common.AppInstallFilters x = new android.adservices.common.AppInstallFilters(); x.huskProps.putAll(huskProps); return x; }
        public android.adservices.common.AppInstallFilters.Builder setPackageNames(java.util.Set p0) { huskProps.put("PackageNames", p0); return this; }
    }
}
