// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.p2p;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class WifiP2pDiscoveryConfig implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public int describeContents() { return 0; }
    public int getFrequencyMhz() { return (huskProps.get("FrequencyMhz") instanceof Integer ? (Integer) huskProps.get("FrequencyMhz") : 0); }
    public int getScanType() { return (huskProps.get("ScanType") instanceof Integer ? (Integer) huskProps.get("ScanType") : 0); }
    public java.util.List getVendorData() { return (huskProps.get("VendorData") != null ? (java.util.List) huskProps.get("VendorData") : new java.util.ArrayList()); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected WifiP2pDiscoveryConfig() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(int p0) {}
        public android.net.wifi.p2p.WifiP2pDiscoveryConfig build() { return new android.net.wifi.p2p.WifiP2pDiscoveryConfig(); }
        public android.net.wifi.p2p.WifiP2pDiscoveryConfig.Builder setFrequencyMhz(int p0) { huskProps.put("FrequencyMhz", Integer.valueOf(p0)); return this; }
        public android.net.wifi.p2p.WifiP2pDiscoveryConfig.Builder setVendorData(java.util.List p0) { huskProps.put("VendorData", p0); return this; }
        Builder() { this((int) 0); }
    }
}
