// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.p2p;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class WifiP2pInfo implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public boolean groupFormed;
    public java.net.InetAddress groupOwnerAddress;
    public boolean isGroupOwner;
    public WifiP2pInfo() {}
    public WifiP2pInfo(android.net.wifi.p2p.WifiP2pInfo p0) {}
    public int describeContents() { return 0; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
