package android.content;

public abstract class BroadcastReceiver {
    public static class PendingResult {
        public final void setResultCode(int c) {} public final int getResultCode() { return 0; }
        public final void setResultData(String d) {} public final String getResultData() { return null; }
        public final void setResult(int c, String d, android.os.Bundle e) {} public final void finish() {}
        public final void abortBroadcast() {} public final boolean getAbortBroadcast() { return false; }
        public final android.os.Bundle getResultExtras(boolean make) { return make ? new android.os.Bundle() : null; }
        // ---- generated by tools/compat/fillmembers.py (PendingResult): the platform's members this class does not write (signatures only)
        public PendingResult() {}
        public static final int TYPE_COMPONENT = 0;
        public static final int TYPE_REGISTERED = 1;
        public static final int TYPE_UNREGISTERED = 2;
        public PendingResult(int p0, java.lang.String p1, android.os.Bundle p2, int p3, boolean p4, boolean p5, android.os.IBinder p6, int p7, int p8) { this(); }
        public PendingResult(int p0, java.lang.String p1, android.os.Bundle p2, int p3, boolean p4, boolean p5, boolean p6, android.os.IBinder p7, int p8, int p9, int p10, java.lang.String p11) { this(); }
        public static boolean guessAssumeDelivered(int p0, boolean p1) { return false; }
        public void clearAbortBroadcast() {}
        public int getSendingUserId() { return 0; }
        public java.lang.String getSentFromPackage() { return null; }
        public int getSentFromUid() { return 0; }
        public void setExtrasClassLoader(java.lang.ClassLoader p0) {}
        public void setResultExtras(android.os.Bundle p0) {}
        // ---- end of generated members (PendingResult)
    }
    private PendingResult mPending;
    private boolean mOrdered, mInitialSticky;
    public BroadcastReceiver() {}
    public abstract void onReceive(Context c, Intent i);
    public final PendingResult goAsync() { PendingResult p = mPending != null ? mPending : new PendingResult(); mPending = null; return p; }
    public final void setResultCode(int c) {} public final int getResultCode() { return 0; }
    public final void setResultData(String d) {} public final String getResultData() { return null; }
    public final void setResult(int c, String d, android.os.Bundle e) {}
    public final android.os.Bundle getResultExtras(boolean make) { return make ? new android.os.Bundle() : null; }
    public final void setResultExtras(android.os.Bundle b) {}
    public final void abortBroadcast() {} public final void clearAbortBroadcast() {} public final boolean getAbortBroadcast() { return false; }
    public final boolean isOrderedBroadcast() { return mOrdered; }
    public final boolean isInitialStickyBroadcast() { return mInitialSticky; }
    public final void setOrderedHint(boolean b) { mOrdered = b; }
    public final void setDebugUnregister(boolean b) {}
    public final boolean getDebugUnregister() { return false; }
    public android.os.IBinder peekService(Context c, Intent s) { return null; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public android.content.BroadcastReceiver.PendingResult getPendingResult() { return (android.content.BroadcastReceiver.PendingResult) huskFill.get("PendingResult"); }
    public android.os.UserHandle getSendingUser() { return null; }
    public void setPendingResult(android.content.BroadcastReceiver.PendingResult p0) { huskFill.put("PendingResult", p0); }
    // ---- end of generated members
}
