// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telephony.ims.aidl;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface IImsMmTelFeature extends android.os.IInterface {
}
