// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ConnectivityDiagnosticsManager {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static java.util.Map sCallbacks;
    public ConnectivityDiagnosticsManager(android.content.Context p0, android.net.IConnectivityManager p1) {}
    public static boolean persistableBundleEquals(android.os.PersistableBundle p0, android.os.PersistableBundle p1) { return false; }
    public void registerConnectivityDiagnosticsCallback(android.net.NetworkRequest p0, java.util.concurrent.Executor p1, android.net.ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback p2) {}
    public void unregisterConnectivityDiagnosticsCallback(android.net.ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback p0) {}
    ConnectivityDiagnosticsManager() { this((android.content.Context) null, (android.net.IConnectivityManager) null); }
    public static abstract class ConnectivityDiagnosticsBinder extends android.net.IConnectivityDiagnosticsCallback.Stub {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ConnectivityDiagnosticsBinder(android.net.ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback p0, java.util.concurrent.Executor p1) { super(); }
        public void onConnectivityReportAvailable(android.net.ConnectivityDiagnosticsManager.ConnectivityReport p0) {}
        public void onDataStallSuspected(android.net.ConnectivityDiagnosticsManager.DataStallReport p0) {}
        public void onNetworkConnectivityReported(android.net.Network p0, boolean p1) {}
        ConnectivityDiagnosticsBinder() { this((android.net.ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback) null, (java.util.concurrent.Executor) null); }
    }
    public static abstract class ConnectivityDiagnosticsCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ConnectivityDiagnosticsCallback() {}
        public void onConnectivityReportAvailable(android.net.ConnectivityDiagnosticsManager.ConnectivityReport p0) {}
        public void onDataStallSuspected(android.net.ConnectivityDiagnosticsManager.DataStallReport p0) {}
        public void onNetworkConnectivityReported(android.net.Network p0, boolean p1) {}
    }
    public static final class ConnectivityReport implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public static final java.lang.String KEY_NETWORK_PROBES_ATTEMPTED_BITMASK = "networkProbesAttempted";
        public static final java.lang.String KEY_NETWORK_PROBES_SUCCEEDED_BITMASK = "networkProbesSucceeded";
        public static final java.lang.String KEY_NETWORK_VALIDATION_RESULT = "networkValidationResult";
        public static final int NETWORK_PROBE_DNS = 4;
        public static final int NETWORK_PROBE_FALLBACK = 32;
        public static final int NETWORK_PROBE_HTTP = 8;
        public static final int NETWORK_PROBE_HTTPS = 16;
        public static final int NETWORK_PROBE_PRIVATE_DNS = 64;
        public static final int NETWORK_VALIDATION_RESULT_INVALID = 0;
        public static final int NETWORK_VALIDATION_RESULT_PARTIALLY_VALID = 2;
        public static final int NETWORK_VALIDATION_RESULT_SKIPPED = 3;
        public static final int NETWORK_VALIDATION_RESULT_VALID = 1;
        public ConnectivityReport(android.net.Network p0, long p1, android.net.LinkProperties p2, android.net.NetworkCapabilities p3, android.os.PersistableBundle p4) {}
        public int describeContents() { return 0; }
        public android.os.PersistableBundle getAdditionalInfo() { return (android.os.PersistableBundle) huskProps.get("AdditionalInfo"); }
        public android.net.LinkProperties getLinkProperties() { return (android.net.LinkProperties) huskProps.get("LinkProperties"); }
        public android.net.Network getNetwork() { return (android.net.Network) huskProps.get("Network"); }
        public android.net.NetworkCapabilities getNetworkCapabilities() { return (android.net.NetworkCapabilities) huskProps.get("NetworkCapabilities"); }
        public long getReportTimestamp() { return (huskProps.get("ReportTimestamp") instanceof Long ? (Long) huskProps.get("ReportTimestamp") : 0L); }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        ConnectivityReport() { this((android.net.Network) null, (long) 0L, (android.net.LinkProperties) null, (android.net.NetworkCapabilities) null, (android.os.PersistableBundle) null); }
    }
    public static final class DataStallReport implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public static final int DETECTION_METHOD_DNS_EVENTS = 1;
        public static final int DETECTION_METHOD_TCP_METRICS = 2;
        public static final java.lang.String KEY_DNS_CONSECUTIVE_TIMEOUTS = "dnsConsecutiveTimeouts";
        public static final java.lang.String KEY_TCP_METRICS_COLLECTION_PERIOD_MILLIS = "tcpMetricsCollectionPeriodMillis";
        public static final java.lang.String KEY_TCP_PACKET_FAIL_RATE = "tcpPacketFailRate";
        public DataStallReport(android.net.Network p0, long p1, int p2, android.net.LinkProperties p3, android.net.NetworkCapabilities p4, android.os.PersistableBundle p5) {}
        public int describeContents() { return 0; }
        public int getDetectionMethod() { return (huskProps.get("DetectionMethod") instanceof Integer ? (Integer) huskProps.get("DetectionMethod") : 0); }
        public android.net.LinkProperties getLinkProperties() { return (android.net.LinkProperties) huskProps.get("LinkProperties"); }
        public android.net.Network getNetwork() { return (android.net.Network) huskProps.get("Network"); }
        public android.net.NetworkCapabilities getNetworkCapabilities() { return (android.net.NetworkCapabilities) huskProps.get("NetworkCapabilities"); }
        public long getReportTimestamp() { return (huskProps.get("ReportTimestamp") instanceof Long ? (Long) huskProps.get("ReportTimestamp") : 0L); }
        public android.os.PersistableBundle getStallDetails() { return (android.os.PersistableBundle) huskProps.get("StallDetails"); }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        DataStallReport() { this((android.net.Network) null, (long) 0L, (int) 0, (android.net.LinkProperties) null, (android.net.NetworkCapabilities) null, (android.os.PersistableBundle) null); }
    }
}
