// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DhcpInfo implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public int dns1;
    public int dns2;
    public int gateway;
    public int ipAddress;
    public int leaseDuration;
    public int netmask;
    public int serverAddress;
    public DhcpInfo() {}
    public DhcpInfo(android.net.DhcpInfo p0) {}
    public int describeContents() { return 0; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
