// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class NetworkTemplate implements android.os.Parcelable {
    protected NetworkTemplate() {}
}
