// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.measurement;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DeletionRequest {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int DELETION_MODE_ALL = 0;
    public static final int DELETION_MODE_EXCLUDE_INTERNAL_DATA = 1;
    public static final int MATCH_BEHAVIOR_DELETE = 0;
    public static final int MATCH_BEHAVIOR_PRESERVE = 1;
    public int getDeletionMode() { return (huskProps.get("DeletionMode") instanceof Integer ? (Integer) huskProps.get("DeletionMode") : 0); }
    public java.util.List getDomainUris() { return (huskProps.get("DomainUris") != null ? (java.util.List) huskProps.get("DomainUris") : new java.util.ArrayList()); }
    public java.time.Instant getEnd() { return (java.time.Instant) huskProps.get("End"); }
    public int getMatchBehavior() { return (huskProps.get("MatchBehavior") instanceof Integer ? (Integer) huskProps.get("MatchBehavior") : 0); }
    public java.util.List getOriginUris() { return (huskProps.get("OriginUris") != null ? (java.util.List) huskProps.get("OriginUris") : new java.util.ArrayList()); }
    public java.time.Instant getStart() { return (java.time.Instant) huskProps.get("Start"); }
    protected DeletionRequest() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.adservices.measurement.DeletionRequest build() { return new android.adservices.measurement.DeletionRequest(); }
        public android.adservices.measurement.DeletionRequest.Builder setDeletionMode(int p0) { huskProps.put("DeletionMode", Integer.valueOf(p0)); return this; }
        public android.adservices.measurement.DeletionRequest.Builder setDomainUris(java.util.List p0) { huskProps.put("DomainUris", p0); return this; }
        public android.adservices.measurement.DeletionRequest.Builder setEnd(java.time.Instant p0) { huskProps.put("End", p0); return this; }
        public android.adservices.measurement.DeletionRequest.Builder setMatchBehavior(int p0) { huskProps.put("MatchBehavior", Integer.valueOf(p0)); return this; }
        public android.adservices.measurement.DeletionRequest.Builder setOriginUris(java.util.List p0) { huskProps.put("OriginUris", p0); return this; }
        public android.adservices.measurement.DeletionRequest.Builder setStart(java.time.Instant p0) { huskProps.put("Start", p0); return this; }
    }
}
