// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.bluetooth.le;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class TransportDiscoveryData implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public TransportDiscoveryData(int p0, java.util.List p1) {}
    public TransportDiscoveryData(byte[] p0) {}
    public int describeContents() { return 0; }
    public java.util.List getTransportBlocks() { return (huskProps.get("TransportBlocks") != null ? (java.util.List) huskProps.get("TransportBlocks") : new java.util.ArrayList()); }
    public int getTransportDataType() { return (huskProps.get("TransportDataType") instanceof Integer ? (Integer) huskProps.get("TransportDataType") : 0); }
    public byte[] toByteArray() { return null; }
    public int totalBytes() { return 0; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    TransportDiscoveryData() { this((byte[]) null); }
}
