// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telecom;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class Conferenceable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    protected Conferenceable() {}
}
