package android.graphics.drawable;

import android.graphics.*;
import android.graphics.drawable.shapes.Shape;

public class ShapeDrawable extends Drawable {
    private Shape mShape; private final Paint mPaint = new Paint(Paint.ANTI_ALIAS_FLAG); private int mW = -1, mH = -1; private Rect mPadding;
    public ShapeDrawable() {}
    public ShapeDrawable(Shape s) { mShape = s; }
    public Shape getShape() { return mShape; }
    public void setShape(Shape s) { mShape = s; onBoundsChange(getBounds()); invalidateSelf(); }
    public Paint getPaint() { return mPaint; }
    public void setIntrinsicWidth(int w) { mW = w; } public void setIntrinsicHeight(int h) { mH = h; }
    public void setPadding(int l, int t, int r, int b) { mPadding = new Rect(l, t, r, b); }
    public void setPadding(Rect p) { mPadding = p; }
    @Override public int getIntrinsicWidth() { return mW; }
    @Override public int getIntrinsicHeight() { return mH; }
    @Override public boolean getPadding(Rect p) { if (mPadding != null) { p.set(mPadding); return true; } return super.getPadding(p); }
    private ShaderFactory mShaderFactory;
    public ShaderFactory getShaderFactory() { return mShaderFactory; }
    /** The shader the paint draws with, remade for each size (a drawable drawn into the shape, Duolingo's buttons). */
    public void setShaderFactory(ShaderFactory f) { mShaderFactory = f; updateShader(getBounds()); invalidateSelf(); }
    private void updateShader(Rect b) { if (mShaderFactory != null && b.width() > 0 && b.height() > 0) mPaint.setShader(mShaderFactory.resize(b.width(), b.height())); }
    public void setXfermode(Xfermode x) { mPaint.setXfermode(x); invalidateSelf(); }
    @Override protected void onBoundsChange(Rect b) { if (mShape != null) mShape.resize(b.width(), b.height()); updateShader(b); }
    /** Draws the shape: subclasses override this to draw it their way. */
    protected void onDraw(Shape shape, Canvas c, Paint p) { shape.draw(c, p); }
    /* the drawable's alpha scales the paint's own when drawing, as Android's does: setting it must not make a transparent paint opaque */
    private int mAlpha = 255;
    @Override public void setAlpha(int a) { mAlpha = a & 0xff; invalidateSelf(); }
    @Override public int getAlpha() { return mAlpha; }
    @Override public void draw(Canvas c) {
        Rect b = getBounds();
        mPaint.setColorFilter(huskTintFilter());
        int prev = mPaint.getAlpha();
        mPaint.setAlpha(prev * (mAlpha + (mAlpha >> 7)) >> 8);
        c.save(); c.translate(b.left, b.top);
        if (mShape != null) onDraw(mShape, c, mPaint); else c.drawRect(0, 0, b.width(), b.height(), mPaint);
        c.restore();
        mPaint.setAlpha(prev);
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public void clearMutated() {}
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static abstract class ShaderFactory {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ShaderFactory() {}
        public abstract android.graphics.Shader resize(int p0, int p1);
    }
    // ---- end of generated nested classes
}
