// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view.inputmethod;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class SelectRangeGesture extends android.view.inputmethod.PreviewableHandwritingGesture implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public int describeContents() { return 0; }
    public int getGranularity() { return (huskProps.get("Granularity") instanceof Integer ? (Integer) huskProps.get("Granularity") : 0); }
    public android.graphics.RectF getSelectionEndArea() { return (android.graphics.RectF) huskProps.get("SelectionEndArea"); }
    public android.graphics.RectF getSelectionStartArea() { return (android.graphics.RectF) huskProps.get("SelectionStartArea"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected SelectRangeGesture() { super(); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.view.inputmethod.SelectRangeGesture build() { return new android.view.inputmethod.SelectRangeGesture(); }
        public android.view.inputmethod.SelectRangeGesture.Builder setFallbackText(java.lang.String p0) { huskProps.put("FallbackText", p0); return this; }
        public android.view.inputmethod.SelectRangeGesture.Builder setGranularity(int p0) { huskProps.put("Granularity", Integer.valueOf(p0)); return this; }
        public android.view.inputmethod.SelectRangeGesture.Builder setSelectionEndArea(android.graphics.RectF p0) { huskProps.put("SelectionEndArea", p0); return this; }
        public android.view.inputmethod.SelectRangeGesture.Builder setSelectionStartArea(android.graphics.RectF p0) { huskProps.put("SelectionStartArea", p0); return this; }
    }
}
