package android.widget;

import android.content.Context;
import android.util.AttributeSet;

/** A date chooser (here the wheel picker). */
public class CalendarView extends FrameLayout {
    public interface OnDateChangeListener { void onSelectedDayChange(CalendarView view, int year, int month, int dayOfMonth); }
    private final DatePicker mPicker;
    private OnDateChangeListener mListener;
    public CalendarView(Context c) { this(c, null); }
    public CalendarView(Context c, AttributeSet a) { this(c, a, 0); }
    public CalendarView(Context c, AttributeSet a, int s) { this(c, a, s, 0); }
    public CalendarView(Context c, AttributeSet a, int s, int r) {
        super(c, a, s, r);
        mPicker = new DatePicker(c);
        mPicker.setOnDateChangedListener((v, y, m, d) -> { if (mListener != null) mListener.onSelectedDayChange(this, y, m, d); });
        addView(mPicker);
    }
    public void setOnDateChangeListener(OnDateChangeListener l) { mListener = l; }
    public long getDate() { java.util.Calendar c = java.util.Calendar.getInstance(); c.set(mPicker.getYear(), mPicker.getMonth(), mPicker.getDayOfMonth()); return c.getTimeInMillis(); }
    public void setDate(long d) { setDate(d, false, false); }
    public void setDate(long d, boolean animate, boolean center) { java.util.Calendar c = java.util.Calendar.getInstance(); c.setTimeInMillis(d); mPicker.updateDate(c.get(java.util.Calendar.YEAR), c.get(java.util.Calendar.MONTH), c.get(java.util.Calendar.DAY_OF_MONTH)); }
    public long getMinDate() { return mPicker.getMinDate(); } public void setMinDate(long d) { mPicker.setMinDate(d); }
    public long getMaxDate() { return mPicker.getMaxDate(); } public void setMaxDate(long d) { mPicker.setMaxDate(d); }
    public void setFirstDayOfWeek(int d) {} public int getFirstDayOfWeek() { return mPicker.getFirstDayOfWeek(); }
    public void setShowWeekNumber(boolean s) {} public boolean getShowWeekNumber() { return false; }
    public void setDateTextAppearance(int r) {} public void setWeekDayTextAppearance(int r) {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public boolean getBoundsForDate(long p0, android.graphics.Rect p1) { return false; }
    public int getDateTextAppearance() { return 0; }
    public int getFocusedMonthDateColor() { return (huskFill.get("FocusedMonthDateColor") instanceof Integer ? (Integer) huskFill.get("FocusedMonthDateColor") : 0); }
    public android.graphics.drawable.Drawable getSelectedDateVerticalBar() { return (android.graphics.drawable.Drawable) huskFill.get("SelectedDateVerticalBar"); }
    public int getSelectedWeekBackgroundColor() { return (huskFill.get("SelectedWeekBackgroundColor") instanceof Integer ? (Integer) huskFill.get("SelectedWeekBackgroundColor") : 0); }
    public int getShownWeekCount() { return (huskFill.get("ShownWeekCount") instanceof Integer ? (Integer) huskFill.get("ShownWeekCount") : 0); }
    public int getUnfocusedMonthDateColor() { return (huskFill.get("UnfocusedMonthDateColor") instanceof Integer ? (Integer) huskFill.get("UnfocusedMonthDateColor") : 0); }
    public int getWeekDayTextAppearance() { return 0; }
    public int getWeekNumberColor() { return (huskFill.get("WeekNumberColor") instanceof Integer ? (Integer) huskFill.get("WeekNumberColor") : 0); }
    public int getWeekSeparatorLineColor() { return (huskFill.get("WeekSeparatorLineColor") instanceof Integer ? (Integer) huskFill.get("WeekSeparatorLineColor") : 0); }
    public void setFocusedMonthDateColor(int p0) { huskFill.put("FocusedMonthDateColor", Integer.valueOf(p0)); }
    public void setSelectedDateVerticalBar(int p0) { huskFill.put("SelectedDateVerticalBar", Integer.valueOf(p0)); }
    public void setSelectedDateVerticalBar(android.graphics.drawable.Drawable p0) { huskFill.put("SelectedDateVerticalBar", p0); }
    public void setSelectedWeekBackgroundColor(int p0) { huskFill.put("SelectedWeekBackgroundColor", Integer.valueOf(p0)); }
    public void setShownWeekCount(int p0) { huskFill.put("ShownWeekCount", Integer.valueOf(p0)); }
    public void setUnfocusedMonthDateColor(int p0) { huskFill.put("UnfocusedMonthDateColor", Integer.valueOf(p0)); }
    public void setWeekNumberColor(int p0) { huskFill.put("WeekNumberColor", Integer.valueOf(p0)); }
    public void setWeekSeparatorLineColor(int p0) { huskFill.put("WeekSeparatorLineColor", Integer.valueOf(p0)); }
    // ---- end of generated members
}
