package android.text.style;
public interface LineBackgroundSpan extends ParagraphStyle {
    void drawBackground(android.graphics.Canvas c, android.graphics.Paint p, int left, int right, int top, int baseline, int bottom, CharSequence text, int start, int end, int lineNumber);
    class Standard implements LineBackgroundSpan { private final int mColor; public Standard(int c) { mColor = c; } public int getColor() { return mColor; } public void drawBackground(android.graphics.Canvas c, android.graphics.Paint p, int l, int r, int t, int b2, int b, CharSequence tx, int s, int e, int n) { int o = p.getColor(); p.setColor(mColor); c.drawRect(l, t, r, b, p); p.setColor(o); }
        // ---- generated by tools/compat/fillmembers.py (Standard): the platform's members this class does not write (signatures only)
        public int describeContents() { return 0; }
        public int getSpanTypeId() { return 0; }
        public int getSpanTypeIdInternal() { return 0; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        public void writeToParcelInternal(android.os.Parcel p0, int p1) {}
        // ---- end of generated members (Standard)
    }
}
