package android.text.style;
public class SuggestionSpan extends CharacterStyle implements android.text.ParcelableSpan {
    public static final int FLAG_EASY_CORRECT = 1, FLAG_MISSPELLED = 2, FLAG_AUTO_CORRECTION = 4, FLAG_GRAMMAR_ERROR = 8, SUGGESTIONS_MAX_SIZE = 5;
    public static final String ACTION_SUGGESTION_PICKED = "android.text.style.SUGGESTION_PICKED";
    private final String[] mSuggestions; private final int mFlags;
    public SuggestionSpan(android.content.Context c, String[] s, int f) { mSuggestions = s; mFlags = f; }
    public SuggestionSpan(java.util.Locale l, String[] s, int f) { mSuggestions = s; mFlags = f; }
    public SuggestionSpan(android.content.Context c, java.util.Locale l, String[] s, int f, Class<?> n) { mSuggestions = s; mFlags = f; }
    public String[] getSuggestions() { return mSuggestions; } public int getFlags() { return mFlags; } public void setFlags(int f) {}
    @Override public void updateDrawState(android.text.TextPaint tp) {}
    public int getSpanTypeId() { return 19; } public int describeContents() { return 0; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static android.os.Parcelable.Creator CREATOR;
    public static final java.lang.String SUGGESTION_SPAN_PICKED_AFTER = "after";
    public static final java.lang.String SUGGESTION_SPAN_PICKED_BEFORE = "before";
    public static final java.lang.String SUGGESTION_SPAN_PICKED_HASHCODE = "hashcode";
    public int getAutoCorrectionUnderlineColor() { return 0; }
    public float getAutoCorrectionUnderlineThickness() { return 0f; }
    public int getEasyCorrectUnderlineColor() { return 0; }
    public float getEasyCorrectUnderlineThickness() { return 0f; }
    public int getGrammarErrorUnderlineColor() { return 0; }
    public float getGrammarErrorUnderlineThickness() { return 0f; }
    public java.lang.String getLocale() { return null; }
    public java.util.Locale getLocaleObject() { return null; }
    public int getMisspelledUnderlineColor() { return 0; }
    public float getMisspelledUnderlineThickness() { return 0f; }
    public java.lang.String getNotificationTargetClassName() { return null; }
    public int getSpanTypeIdInternal() { return 0; }
    public int getUnderlineColor() { return 0; }
    public void notifySelection(android.content.Context p0, java.lang.String p1, int p2) {}
    public void writeToParcelInternal(android.os.Parcel p0, int p1) {}
    // ---- end of generated members
}
