// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.drm;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DrmEvent {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String DRM_INFO_OBJECT = "drm_info_object";
    public static final java.lang.String DRM_INFO_STATUS_OBJECT = "drm_info_status_object";
    public static final int TYPE_ALL_RIGHTS_REMOVED = 1001;
    public static final int TYPE_DRM_INFO_PROCESSED = 1002;
    protected DrmEvent(int p0, int p1, java.lang.String p2) {}
    protected DrmEvent(int p0, int p1, java.lang.String p2, java.util.HashMap p3) {}
    public java.lang.Object getAttribute(java.lang.String p0) { return null; }
    public java.lang.String getMessage() { return (java.lang.String) huskProps.get("Message"); }
    public int getType() { return (huskProps.get("Type") instanceof Integer ? (Integer) huskProps.get("Type") : 0); }
    public int getUniqueId() { return (huskProps.get("UniqueId") instanceof Integer ? (Integer) huskProps.get("UniqueId") : 0); }
}
