package android.content.pm;
public class ActivityInfo extends ComponentInfo implements android.os.Parcelable {
    public static final int SCREEN_ORIENTATION_UNSET = -2, SCREEN_ORIENTATION_UNSPECIFIED = -1, SCREEN_ORIENTATION_LANDSCAPE = 0, SCREEN_ORIENTATION_PORTRAIT = 1,
        SCREEN_ORIENTATION_USER = 2, SCREEN_ORIENTATION_BEHIND = 3, SCREEN_ORIENTATION_SENSOR = 4, SCREEN_ORIENTATION_NOSENSOR = 5, SCREEN_ORIENTATION_SENSOR_LANDSCAPE = 6,
        SCREEN_ORIENTATION_SENSOR_PORTRAIT = 7, SCREEN_ORIENTATION_REVERSE_LANDSCAPE = 8, SCREEN_ORIENTATION_REVERSE_PORTRAIT = 9,
        SCREEN_ORIENTATION_FULL_SENSOR = 10, SCREEN_ORIENTATION_USER_LANDSCAPE = 11, SCREEN_ORIENTATION_USER_PORTRAIT = 12, SCREEN_ORIENTATION_FULL_USER = 13, SCREEN_ORIENTATION_LOCKED = 14;
    public static final int LAUNCH_MULTIPLE = 0, LAUNCH_SINGLE_TOP = 1, LAUNCH_SINGLE_TASK = 2, LAUNCH_SINGLE_INSTANCE = 3, LAUNCH_SINGLE_INSTANCE_PER_TASK = 4;
    public static final int CONFIG_MCC = 1, CONFIG_MNC = 2, CONFIG_LOCALE = 4, CONFIG_TOUCHSCREEN = 8, CONFIG_KEYBOARD = 16, CONFIG_KEYBOARD_HIDDEN = 32, CONFIG_NAVIGATION = 64,
        CONFIG_ORIENTATION = 128, CONFIG_SCREEN_LAYOUT = 256, CONFIG_UI_MODE = 512, CONFIG_SCREEN_SIZE = 1024, CONFIG_SMALLEST_SCREEN_SIZE = 2048, CONFIG_DENSITY = 4096,
        CONFIG_LAYOUT_DIRECTION = 8192, CONFIG_COLOR_MODE = 16384, CONFIG_GRAMMATICAL_GENDER = 32768, CONFIG_FONT_WEIGHT_ADJUSTMENT = 0x10000000, CONFIG_FONT_SCALE = 0x40000000;
    public static final int FLAG_MULTIPROCESS = 1, FLAG_FINISH_ON_TASK_LAUNCH = 2, FLAG_CLEAR_TASK_ON_LAUNCH = 4, FLAG_ALWAYS_RETAIN_TASK_STATE = 8, FLAG_STATE_NOT_NEEDED = 16,
        FLAG_EXCLUDE_FROM_RECENTS = 32, FLAG_ALLOW_TASK_REPARENTING = 64, FLAG_NO_HISTORY = 128, FLAG_FINISH_ON_CLOSE_SYSTEM_DIALOGS = 256, FLAG_HARDWARE_ACCELERATED = 512,
        FLAG_IMMERSIVE = 0x800, FLAG_RELINQUISH_TASK_IDENTITY = 0x1000, FLAG_AUTO_REMOVE_FROM_RECENTS = 0x2000, FLAG_RESUME_WHILE_PAUSING = 0x4000, FLAG_SINGLE_USER = 0x40000000;
    public static final int UIOPTION_SPLIT_ACTION_BAR_WHEN_NARROW = 1, DOCUMENT_LAUNCH_NONE = 0, PERSIST_ROOT_ONLY = 0, COLOR_MODE_DEFAULT = 0;
    public int theme, launchMode, documentLaunchMode, persistableMode, maxRecents, screenOrientation = SCREEN_ORIENTATION_UNSPECIFIED, configChanges, softInputMode, uiOptions,
        flags, colorMode, rotationAnimation = -1, lockTaskLaunchMode;
    public String permission, taskAffinity, targetActivity, parentActivityName;
    public ActivityInfo() {}
    public ActivityInfo(ActivityInfo o) { super(o); theme = o.theme; launchMode = o.launchMode; screenOrientation = o.screenOrientation; configChanges = o.configChanges; flags = o.flags; parentActivityName = o.parentActivityName; }
    public final int getThemeResource() { return theme != 0 ? theme : applicationInfo.theme; }
    public int describeContents() { return 0; }
    public static final class WindowLayout { public final int width = -1, height = -1, gravity = 0; public final float widthFraction = -1, heightFraction = -1;
        // ---- generated by tools/compat/fillmembers.py (WindowLayout): the platform's members this class does not write (signatures only)
        public WindowLayout() {}
        public int minHeight;
        public int minWidth;
        public java.lang.String windowLayoutAffinity;
        public WindowLayout(int p0, float p1, int p2, float p3, int p4, int p5, int p6) { this(); }
        public WindowLayout(int p0, float p1, int p2, float p3, int p4, int p5, int p6, java.lang.String p7) { this(); }
        public WindowLayout(android.os.Parcel p0) { this(); }
        public boolean hasSpecifiedSize() { return false; }
        public void writeToParcel(android.os.Parcel p0) {}
        // ---- end of generated members (WindowLayout)
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final long ALWAYS_SANDBOX_DISPLAY_APIS = 185004937L;
    public static final int COLOR_MODE_A8 = 4;
    public static final int COLOR_MODE_HDR = 2;
    public static final int COLOR_MODE_HDR10 = 3;
    public static final int COLOR_MODE_WIDE_COLOR_GAMUT = 1;
    public static final int CONFIG_ASSETS_PATHS = -2147483648;
    public static int[] CONFIG_NATIVE_BITS;
    public static final int CONFIG_RESOURCES_UNUSED = 134217728;
    public static final int CONFIG_WINDOW_CONFIGURATION = 536870912;
    public static final int CONTENT_URI_PERMISSION_NONE = 0;
    public static final int CONTENT_URI_PERMISSION_READ = 1;
    public static final int CONTENT_URI_PERMISSION_READ_AND_WRITE = 4;
    public static final int CONTENT_URI_PERMISSION_READ_OR_WRITE = 3;
    public static final int CONTENT_URI_PERMISSION_WRITE = 2;
    public static android.os.Parcelable.Creator CREATOR;
    public static final int DOCUMENT_LAUNCH_ALWAYS = 2;
    public static final int DOCUMENT_LAUNCH_INTO_EXISTING = 1;
    public static final int DOCUMENT_LAUNCH_NEVER = 3;
    public static final int FLAG_ALLOW_EMBEDDED = -2147483648;
    public static final int FLAG_ALLOW_UNTRUSTED_ACTIVITY_EMBEDDING = 268435456;
    public static final int FLAG_ALWAYS_FOCUSABLE = 262144;
    public static final int FLAG_CAN_DISPLAY_ON_REMOTE_DEVICES = 65536;
    public static final int FLAG_ENABLE_VR_MODE = 32768;
    public static final int FLAG_IMPLICITLY_VISIBLE_TO_INSTANT_APP = 2097152;
    public static final int FLAG_INHERIT_SHOW_WHEN_LOCKED = 1;
    public static final int FLAG_PREFER_MINIMAL_POST_PROCESSING = 33554432;
    public static final int FLAG_SHOW_FOR_ALL_USERS = 1024;
    public static final int FLAG_SHOW_WHEN_LOCKED = 8388608;
    public static final int FLAG_SUPPORTS_PICTURE_IN_PICTURE = 4194304;
    public static final int FLAG_SYSTEM_USER_ONLY = 536870912;
    public static final int FLAG_TURN_SCREEN_ON = 16777216;
    public static final int FLAG_VISIBLE_TO_INSTANT_APP = 1048576;
    public static final long FORCE_NON_RESIZE_APP = 181136395L;
    public static final long FORCE_RESIZE_APP = 174042936L;
    public static final long INSETS_DECOUPLED_CONFIGURATION_ENFORCED = 151861875L;
    public static final int LOCK_TASK_LAUNCH_MODE_ALWAYS = 2;
    public static final int LOCK_TASK_LAUNCH_MODE_DEFAULT = 0;
    public static final int LOCK_TASK_LAUNCH_MODE_IF_ALLOWLISTED = 3;
    public static final int LOCK_TASK_LAUNCH_MODE_NEVER = 1;
    public static final long NEVER_SANDBOX_DISPLAY_APIS = 184838306L;
    public static final long OVERRIDE_ANY_ORIENTATION = 265464455L;
    public static final long OVERRIDE_ANY_ORIENTATION_TO_USER = 310816437L;
    public static final long OVERRIDE_AUTO_RESTART_ON_DISPLAY_MOVE = 427878712L;
    public static final long OVERRIDE_CAMERA_COMPAT_DISABLE_FORCE_ROTATION = 263959004L;
    public static final long OVERRIDE_CAMERA_COMPAT_DISABLE_REFRESH = 264304459L;
    public static final long OVERRIDE_CAMERA_COMPAT_DISABLE_SIMULATE_REQUESTED_ORIENTATION = 398195815L;
    public static final long OVERRIDE_CAMERA_COMPAT_ENABLE_FREEFORM_WINDOWING_TREATMENT = 314961188L;
    public static final long OVERRIDE_CAMERA_COMPAT_ENABLE_REFRESH_VIA_PAUSE = 264301586L;
    public static final long OVERRIDE_ENABLE_COMPAT_FAKE_FOCUS = 263259275L;
    public static final long OVERRIDE_ENABLE_COMPAT_IGNORE_ORIENTATION_REQUEST_WHEN_LOOP_DETECTED = 273509367L;
    public static final long OVERRIDE_ENABLE_COMPAT_IGNORE_REQUESTED_ORIENTATION = 254631730L;
    public static final long OVERRIDE_ENABLE_INSETS_DECOUPLED_CONFIGURATION = 327313645L;
    public static final long OVERRIDE_EXCLUDE_CAPTION_INSETS_FROM_APP_BOUNDS = 388014743L;
    public static final long OVERRIDE_LANDSCAPE_ORIENTATION_TO_REVERSE_LANDSCAPE = 266124927L;
    public static final long OVERRIDE_MIN_ASPECT_RATIO = 174042980L;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_EXCLUDE_PORTRAIT_FULLSCREEN = 218959984L;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_LARGE = 180326787L;
    public static final float OVERRIDE_MIN_ASPECT_RATIO_LARGE_VALUE = 1.7777777910232544f;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_MEDIUM = 180326845L;
    public static final float OVERRIDE_MIN_ASPECT_RATIO_MEDIUM_VALUE = 1.5f;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_ONLY_FOR_CAMERA = 325586858L;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_PORTRAIT_ONLY = 203647190L;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_SMALL = 349045028L;
    public static final float OVERRIDE_MIN_ASPECT_RATIO_SMALL_VALUE = 1.3333333730697632f;
    public static final long OVERRIDE_MIN_ASPECT_RATIO_TO_ALIGN_WITH_SPLIT_SCREEN = 208648326L;
    public static final long OVERRIDE_MOUSE_TO_TOUCH = 413207127L;
    public static final long OVERRIDE_ORIENTATION_ONLY_FOR_CAMERA = 265456536L;
    public static final long OVERRIDE_RESPECT_REQUESTED_ORIENTATION = 236283604L;
    public static final long OVERRIDE_SANDBOX_VIEW_BOUNDS_APIS = 237531167L;
    public static final long OVERRIDE_UNDEFINED_ORIENTATION_TO_NOSENSOR = 265451093L;
    public static final long OVERRIDE_UNDEFINED_ORIENTATION_TO_PORTRAIT = 265452344L;
    public static final long OVERRIDE_USE_DISPLAY_LANDSCAPE_NATURAL_ORIENTATION = 255940284L;
    public static final int PERSIST_ACROSS_REBOOTS = 2;
    public static final int PERSIST_NEVER = 1;
    public static final int PRIVATE_FLAG_DISABLE_ON_BACK_INVOKED_CALLBACK = 8;
    public static final int PRIVATE_FLAG_ENABLE_ON_BACK_INVOKED_CALLBACK = 4;
    public static final int PRIVATE_FLAG_HOME_TRANSITION_SOUND = 2;
    public static final int RESIZE_MODE_FORCE_RESIZABLE_LANDSCAPE_ONLY = 5;
    public static final int RESIZE_MODE_FORCE_RESIZABLE_PORTRAIT_ONLY = 6;
    public static final int RESIZE_MODE_FORCE_RESIZABLE_PRESERVE_ORIENTATION = 7;
    public static final int RESIZE_MODE_FORCE_RESIZEABLE = 4;
    public static final int RESIZE_MODE_RESIZEABLE = 2;
    public static final int RESIZE_MODE_RESIZEABLE_AND_PIPABLE_DEPRECATED = 3;
    public static final int RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION = 1;
    public static final int RESIZE_MODE_UNRESIZEABLE = 0;
    public static final int SIZE_CHANGES_SUPPORTED_METADATA = 2;
    public static final int SIZE_CHANGES_SUPPORTED_OVERRIDE = 3;
    public static final int SIZE_CHANGES_UNSUPPORTED_METADATA = 0;
    public static final int SIZE_CHANGES_UNSUPPORTED_OVERRIDE = 1;
    public static final long UNIVERSAL_RESIZABLE_BY_DEFAULT = 357141415L;
    public java.lang.String launchToken;
    public int privateFlags;
    public java.lang.String requestedVrComponent;
    public int requireContentUriPermissionFromCaller;
    public java.lang.String requiredDisplayCategory;
    public int resizeMode;
    public boolean supportsSizeChanges;
    public android.content.pm.ActivityInfo.WindowLayout windowLayout;
    public static int activityInfoConfigJavaToNative(int p0) { return 0; }
    public static int activityInfoConfigNativeToJava(int p0) { return 0; }
    public static java.lang.String colorModeToString(int p0) { return null; }
    public static boolean isFixedOrientation(int p0) { return false; }
    public static boolean isFixedOrientationLandscape(int p0) { return false; }
    public static boolean isFixedOrientationPortrait(int p0) { return false; }
    public static boolean isPreserveOrientationMode(int p0) { return false; }
    public static boolean isRequiredContentUriPermissionRead(int p0) { return false; }
    public static boolean isRequiredContentUriPermissionWrite(int p0) { return false; }
    public static boolean isResizeableMode(int p0) { return false; }
    public static boolean isTranslucentOrFloating(android.content.res.TypedArray p0) { return false; }
    public static java.lang.String launchModeToString(int p0) { return null; }
    public static java.lang.String lockTaskLaunchModeToString(int p0) { return null; }
    public static java.lang.String requiredContentUriPermissionToShortString(int p0) { return null; }
    public static java.lang.String resizeModeToString(int p0) { return null; }
    public static int reverseOrientation(int p0) { return 0; }
    public static java.lang.String screenOrientationToString(int p0) { return null; }
    public static java.lang.String sizeChangesSupportModeToString(int p0) { return null; }
    public void dump(android.util.Printer p0, java.lang.String p1) {}
    public void dump(android.util.Printer p0, java.lang.String p1, int p2) {}
    public java.util.Set getKnownActivityEmbeddingCerts() { return (huskFill.get("KnownActivityEmbeddingCerts") != null ? (java.util.Set) huskFill.get("KnownActivityEmbeddingCerts") : new java.util.HashSet()); }
    public float getManifestMinAspectRatio() { return 0f; }
    public float getMaxAspectRatio() { return (huskFill.get("MaxAspectRatio") instanceof Float ? (Float) huskFill.get("MaxAspectRatio") : 0f); }
    public float getMinAspectRatio() { return (huskFill.get("MinAspectRatio") instanceof Float ? (Float) huskFill.get("MinAspectRatio") : 0f); }
    public int getRealConfigChanged() { return 0; }
    public boolean hasFixedAspectRatio() { return false; }
    public boolean hasOnBackInvokedCallbackEnabled() { return false; }
    public boolean isChangeEnabled(long p0) { return false; }
    public boolean isFixedOrientation() { return false; }
    public boolean isOnBackInvokedCallbackEnabled() { return false; }
    public void setKnownActivityEmbeddingCerts(java.util.Set p0) { huskFill.put("KnownActivityEmbeddingCerts", p0); }
    public void setMaxAspectRatio(float p0) { huskFill.put("MaxAspectRatio", Float.valueOf(p0)); }
    public void setMinAspectRatio(float p0) { huskFill.put("MinAspectRatio", Float.valueOf(p0)); }
    public boolean shouldCheckMinWidthHeightForMultiWindow() { return false; }
    public boolean supportsPictureInPicture() { return false; }
    // ---- end of generated members
}
