package android.content.pm;
public class PackageInstaller { public java.util.List<SessionInfo> getMySessions() { return new java.util.ArrayList<>(); } public static class SessionInfo {
    // ---- generated by tools/compat/fillmembers.py (SessionInfo): the platform's members this class does not write (signatures only)
    public SessionInfo() {}
    public static android.os.Parcelable.Creator CREATOR;
    public static final int INVALID_ID = -1;
    public static final int SESSION_ACTIVATION_FAILED = 2;
    public static final int SESSION_CONFLICT = 4;
    public static final int SESSION_NO_ERROR = 0;
    public static final int SESSION_UNKNOWN_ERROR = 3;
    public static final int SESSION_VERIFICATION_FAILED = 1;
    public static final int STAGED_SESSION_ACTIVATION_FAILED = 2;
    public static final int STAGED_SESSION_CONFLICT = 4;
    public static final int STAGED_SESSION_NO_ERROR = 0;
    public static final int STAGED_SESSION_UNKNOWN = 3;
    public static final int STAGED_SESSION_VERIFICATION_FAILED = 1;
    public boolean active;
    public android.graphics.Bitmap appIcon;
    public java.lang.CharSequence appLabel;
    public java.lang.String appPackageName;
    public boolean applicationEnabledSettingPersistent;
    public int autoRevokePermissionsMode;
    public int[] childSessionIds;
    public long createdMillis;
    public boolean forceQueryable;
    public java.lang.String[] grantedRuntimePermissions;
    public int installFlags;
    public int installLocation;
    public int installReason;
    public int installScenario;
    public java.lang.String installerAttributionTag;
    public java.lang.String installerPackageName;
    public int installerUid;
    public boolean isAutoInstallingDependenciesEnabled;
    public boolean isCommitted;
    public boolean isMultiPackage;
    public boolean isPreapprovalRequested;
    public boolean isSessionApplied;
    public boolean isSessionFailed;
    public boolean isSessionReady;
    public boolean isStaged;
    public int mode;
    public int originatingUid;
    public android.net.Uri originatingUri;
    public int packageSource;
    public int parentSessionId;
    public int pendingUserActionReason;
    public float progress;
    public android.net.Uri referrerUri;
    public int requireUserAction;
    public java.lang.String resolvedBaseCodePath;
    public int rollbackDataPolicy;
    public int rollbackImpactLevel;
    public long rollbackLifetimeMillis;
    public boolean sealed;
    public int sessionId;
    public long sizeBytes;
    public long updatedMillis;
    public int userId;
    public java.util.List whitelistedRestrictedPermissions;
    public SessionInfo(android.os.Parcel p0) { this(); }
    public android.content.Intent createDetailsIntent() { return null; }
    public int describeContents() { return 0; }
    public boolean getAllocateAggressive() { return false; }
    public boolean getAllowDowngrade() { return false; }
    public android.graphics.Bitmap getAppIcon() { return null; }
    public java.lang.CharSequence getAppLabel() { return null; }
    public java.lang.String getAppPackageName() { return null; }
    public int getAutoRevokePermissionsMode() { return 0; }
    public int[] getChildSessionIds() { return null; }
    public long getCreatedMillis() { return 0L; }
    public android.content.Intent getDetailsIntent() { return null; }
    public boolean getDontKillApp() { return false; }
    public boolean getEnableRollback() { return false; }
    public java.lang.String[] getGrantedRuntimePermissions() { return null; }
    public boolean getInstallAsFullApp(boolean p0) { return false; }
    public boolean getInstallAsInstantApp(boolean p0) { return false; }
    public boolean getInstallAsVirtualPreload() { return false; }
    public int getInstallLocation() { return 0; }
    public int getInstallReason() { return 0; }
    public java.lang.String getInstallerAttributionTag() { return null; }
    public java.lang.String getInstallerPackageName() { return null; }
    public int getInstallerUid() { return 0; }
    public int getMode() { return 0; }
    public int getOriginatingUid() { return 0; }
    public android.net.Uri getOriginatingUri() { return null; }
    public int getPackageSource() { return 0; }
    public int getParentSessionId() { return 0; }
    public int getPendingUserActionReason() { return 0; }
    public float getProgress() { return 0f; }
    public android.net.Uri getReferrerUri() { return null; }
    public boolean getRequestDowngrade() { return false; }
    public int getRequireUserAction() { return 0; }
    public java.lang.String getResolvedBaseApkPath() { return null; }
    public int getRollbackDataPolicy() { return 0; }
    public int getSessionId() { return 0; }
    public long getSize() { return 0L; }
    public int getStagedSessionErrorCode() { return 0; }
    public java.lang.String getStagedSessionErrorMessage() { return null; }
    public long getUpdatedMillis() { return 0L; }
    public android.os.UserHandle getUser() { return null; }
    public java.util.Set getWhitelistedRestrictedPermissions() { return new java.util.HashSet(); }
    public boolean hasParentSessionId() { return false; }
    public boolean isActive() { return false; }
    public boolean isApplicationEnabledSettingPersistent() { return false; }
    public boolean isAutoInstallDependenciesEnabled() { return false; }
    public boolean isCommitted() { return false; }
    public boolean isForceQueryable() { return false; }
    public boolean isMultiPackage() { return false; }
    public boolean isOpen() { return false; }
    public boolean isPreApprovalRequested() { return false; }
    public boolean isRequestUpdateOwnership() { return false; }
    public boolean isSealed() { return false; }
    public boolean isStaged() { return false; }
    public boolean isStagedSessionActive() { return false; }
    public boolean isStagedSessionApplied() { return false; }
    public boolean isStagedSessionFailed() { return false; }
    public boolean isStagedSessionReady() { return false; }
    public boolean isUnarchival() { return false; }
    public void setSessionErrorCode(int p0, java.lang.String p1) {}
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    // ---- end of generated members (SessionInfo)
}     // ---- generated by tools/compat/genstubs.py: signatures only
    public static abstract class SessionCallback {
        protected SessionCallback() {}
        // ---- generated by tools/compat/fillmembers.py (SessionCallback): the platform's members this class does not write (signatures only)
        public void onActiveChanged(int p0, boolean p1) {}
        public void onBadgingChanged(int p0) {}
        public void onCreated(int p0) {}
        public void onFinished(int p0, boolean p1) {}
        public void onProgressChanged(int p0, float p1) {}
        // ---- end of generated members (SessionCallback)
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final java.lang.String ACTION_CONFIRM_DEVELOPER_VERIFICATION = "android.content.pm.action.CONFIRM_DEVELOPER_VERIFICATION";
    public static final java.lang.String ACTION_CONFIRM_INSTALL = "android.content.pm.action.CONFIRM_INSTALL";
    public static final java.lang.String ACTION_CONFIRM_PRE_APPROVAL = "android.content.pm.action.CONFIRM_PRE_APPROVAL";
    public static final java.lang.String ACTION_INSTALL_DEPENDENCY = "android.content.pm.action.INSTALL_DEPENDENCY";
    public static final java.lang.String ACTION_SESSION_COMMITTED = "android.content.pm.action.SESSION_COMMITTED";
    public static final java.lang.String ACTION_SESSION_DETAILS = "android.content.pm.action.SESSION_DETAILS";
    public static final java.lang.String ACTION_SESSION_UPDATED = "android.content.pm.action.SESSION_UPDATED";
    public static final int DATA_LOADER_TYPE_INCREMENTAL = 2;
    public static final int DATA_LOADER_TYPE_NONE = 0;
    public static final int DATA_LOADER_TYPE_STREAMING = 1;
    public static final int DEVELOPER_VERIFICATION_FAILED_REASON_DEVELOPER_BLOCKED = 2;
    public static final int DEVELOPER_VERIFICATION_FAILED_REASON_NETWORK_UNAVAILABLE = 1;
    public static final int DEVELOPER_VERIFICATION_FAILED_REASON_UNKNOWN = 0;
    public static final int DEVELOPER_VERIFICATION_POLICY_BLOCK_FAIL_CLOSED = 3;
    public static final int DEVELOPER_VERIFICATION_POLICY_BLOCK_FAIL_OPEN = 1;
    public static final int DEVELOPER_VERIFICATION_POLICY_BLOCK_FAIL_WARN = 2;
    public static final int DEVELOPER_VERIFICATION_POLICY_NONE = 0;
    public static final int DEVELOPER_VERIFICATION_USER_RESPONSE_ABORT = 1;
    public static final int DEVELOPER_VERIFICATION_USER_RESPONSE_ERROR = 0;
    public static final int DEVELOPER_VERIFICATION_USER_RESPONSE_INSTALL_ANYWAY = 3;
    public static final int DEVELOPER_VERIFICATION_USER_RESPONSE_RETRY = 2;
    public static final boolean ENABLE_REVOCABLE_FD = false;
    public static final java.lang.String EXTRA_CALLBACK = "android.content.pm.extra.CALLBACK";
    public static final java.lang.String EXTRA_DATA_LOADER_TYPE = "android.content.pm.extra.DATA_LOADER_TYPE";
    public static final java.lang.String EXTRA_DELETE_FLAGS = "android.content.pm.extra.DELETE_FLAGS";
    public static final java.lang.String EXTRA_DEVELOPER_VERIFICATION_EXTENSION_RESPONSE = "android.content.pm.extra.DEVELOPER_VERIFICATION_EXTENSION_RESPONSE";
    public static final java.lang.String EXTRA_DEVELOPER_VERIFICATION_FAILURE_REASON = "android.content.pm.extra.DEVELOPER_VERIFICATION_FAILURE_REASON";
    public static final java.lang.String EXTRA_DEVELOPER_VERIFICATION_LITE_PERFORMED = "android.content.pm.extra.DEVELOPER_VERIFICATION_LITE_PERFORMED";
    public static final java.lang.String EXTRA_INSTALL_CONSTRAINTS = "android.content.pm.extra.INSTALL_CONSTRAINTS";
    public static final java.lang.String EXTRA_INSTALL_CONSTRAINTS_RESULT = "android.content.pm.extra.INSTALL_CONSTRAINTS_RESULT";
    public static final java.lang.String EXTRA_LEGACY_BUNDLE = "android.content.pm.extra.LEGACY_BUNDLE";
    public static final java.lang.String EXTRA_LEGACY_STATUS = "android.content.pm.extra.LEGACY_STATUS";
    public static final java.lang.String EXTRA_OTHER_PACKAGE_NAME = "android.content.pm.extra.OTHER_PACKAGE_NAME";
    public static final java.lang.String EXTRA_PACKAGE_NAME = "android.content.pm.extra.PACKAGE_NAME";
    public static final java.lang.String EXTRA_PACKAGE_NAMES = "android.content.pm.extra.PACKAGE_NAMES";
    public static final java.lang.String EXTRA_PRE_APPROVAL = "android.content.pm.extra.PRE_APPROVAL";
    public static final java.lang.String EXTRA_RESOLVED_BASE_PATH = "android.content.pm.extra.RESOLVED_BASE_PATH";
    public static final java.lang.String EXTRA_SESSION = "android.content.pm.extra.SESSION";
    public static final java.lang.String EXTRA_SESSION_ID = "android.content.pm.extra.SESSION_ID";
    public static final java.lang.String EXTRA_STATUS = "android.content.pm.extra.STATUS";
    public static final java.lang.String EXTRA_STATUS_MESSAGE = "android.content.pm.extra.STATUS_MESSAGE";
    public static final java.lang.String EXTRA_STORAGE_PATH = "android.content.pm.extra.STORAGE_PATH";
    public static final java.lang.String EXTRA_UNARCHIVE_ALL_USERS = "android.content.pm.extra.UNARCHIVE_ALL_USERS";
    public static final java.lang.String EXTRA_UNARCHIVE_ID = "android.content.pm.extra.UNARCHIVE_ID";
    public static final java.lang.String EXTRA_UNARCHIVE_PACKAGE_NAME = "android.content.pm.extra.UNARCHIVE_PACKAGE_NAME";
    public static final java.lang.String EXTRA_UNARCHIVE_STATUS = "android.content.pm.extra.UNARCHIVE_STATUS";
    public static final java.lang.String EXTRA_WARNINGS = "android.content.pm.extra.WARNINGS";
    public static final int LOCATION_DATA_APP = 0;
    public static final int LOCATION_MEDIA_DATA = 2;
    public static final int LOCATION_MEDIA_OBB = 1;
    public static final int PACKAGE_SOURCE_DOWNLOADED_FILE = 4;
    public static final int PACKAGE_SOURCE_LOCAL_FILE = 3;
    public static final int PACKAGE_SOURCE_OTHER = 1;
    public static final int PACKAGE_SOURCE_STORE = 2;
    public static final int PACKAGE_SOURCE_UNSPECIFIED = 0;
    public static final int REASON_CONFIRM_PACKAGE_CHANGE = 0;
    public static final int REASON_OWNERSHIP_CHANGED = 1;
    public static final int REASON_REMIND_OWNERSHIP = 2;
    public static final int STATUS_FAILURE = 1;
    public static final int STATUS_FAILURE_ABORTED = 3;
    public static final int STATUS_FAILURE_BLOCKED = 2;
    public static final int STATUS_FAILURE_CONFLICT = 5;
    public static final int STATUS_FAILURE_INCOMPATIBLE = 7;
    public static final int STATUS_FAILURE_INVALID = 4;
    public static final int STATUS_FAILURE_STORAGE = 6;
    public static final int STATUS_FAILURE_TIMEOUT = 8;
    public static final int STATUS_PENDING_STREAMING = -2;
    public static final int STATUS_PENDING_USER_ACTION = -1;
    public static final int STATUS_SUCCESS = 0;
    public static final int UNARCHIVAL_ERROR_INSTALLER_DISABLED = 4;
    public static final int UNARCHIVAL_ERROR_INSTALLER_UNINSTALLED = 5;
    public static final int UNARCHIVAL_ERROR_INSUFFICIENT_STORAGE = 2;
    public static final int UNARCHIVAL_ERROR_NO_CONNECTIVITY = 3;
    public static final int UNARCHIVAL_ERROR_USER_ACTION_NEEDED = 1;
    public static final int UNARCHIVAL_GENERIC_ERROR = 100;
    public static final int UNARCHIVAL_OK = 0;
    public static final int UNARCHIVAL_STATUS_UNSET = -1;
    public void abandonSession(int p0) {}
    public void addSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}
    public void addSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0, android.os.Handler p1) {}
    public android.content.pm.PackageInstaller.SessionInfo getActiveStagedSession() { return null; }
    public java.util.List getActiveStagedSessions() { return new java.util.ArrayList(); }
    public java.util.List getAllSessions() { return new java.util.ArrayList(); }
    public int getDeveloperVerificationPolicy() { return (huskFill.get("DeveloperVerificationPolicy") instanceof Integer ? (Integer) huskFill.get("DeveloperVerificationPolicy") : 0); }
    public java.lang.String getDeveloperVerificationPolicyDelegatePackage() { return null; }
    public android.content.ComponentName getDeveloperVerificationServiceProvider() { return null; }
    public android.content.pm.PackageInstaller.SessionInfo getSessionInfo(int p0) { return null; }
    public java.util.List getStagedSessions() { return new java.util.ArrayList(); }
    public void installExistingPackage(java.lang.String p0, int p1, android.content.IntentSender p2) {}
    public void registerSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}
    public void registerSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0, android.os.Handler p1) {}
    public void removeSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}
    public void reportUnarchivalStatus(int p0, int p1, long p2, android.app.PendingIntent p3) {}
    public void requestArchive(java.lang.String p0, android.content.IntentSender p1) {}
    public void requestUnarchive(java.lang.String p0, android.content.IntentSender p1) {}
    public boolean setDeveloperVerificationPolicy(int p0) { return false; }
    public void setDeveloperVerificationUserResponse(int p0, int p1) {}
    public void setPermissionsResult(int p0, boolean p1) {}
    public void uninstall(android.content.pm.VersionedPackage p0, int p1, android.content.IntentSender p2) {}
    public void uninstall(android.content.pm.VersionedPackage p0, android.content.IntentSender p1) {}
    public void uninstall(java.lang.String p0, int p1, android.content.IntentSender p2) {}
    public void uninstall(java.lang.String p0, android.content.IntentSender p1) {}
    public void uninstallExistingPackage(java.lang.String p0, android.content.IntentSender p1) {}
    public void unregisterSessionCallback(android.content.pm.PackageInstaller.SessionCallback p0) {}
    public void updateSessionAppIcon(int p0, android.graphics.Bitmap p1) {}
    public void updateSessionAppLabel(int p0, java.lang.CharSequence p1) {}
    // ---- end of generated members
}
