package android.animation;
public class StateListAnimator implements Cloneable {
    public void addState(int[] specs, Animator a) {}
    public void jumpToCurrentState() {}
    @Override public StateListAnimator clone() { return new StateListAnimator(); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public void appendChangingConfigurations(int p0) {}
    public int getChangingConfigurations() { return (huskFill.get("ChangingConfigurations") instanceof Integer ? (Integer) huskFill.get("ChangingConfigurations") : 0); }
    public android.animation.Animator getRunningAnimator() { return null; }
    public android.view.View getTarget() { return (android.view.View) huskFill.get("Target"); }
    public java.util.ArrayList getTuples() { return new java.util.ArrayList(); }
    public void setChangingConfigurations(int p0) { huskFill.put("ChangingConfigurations", Integer.valueOf(p0)); }
    public void setState(int[] p0) {}
    public void setTarget(android.view.View p0) { huskFill.put("Target", p0); }
    // ---- end of generated members
}
