// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telephony.data;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class TrafficDescriptor implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public TrafficDescriptor(java.lang.String p0, byte[] p1) {}
    public int describeContents() { return 0; }
    public java.lang.String getDataNetworkName() { return (java.lang.String) huskProps.get("DataNetworkName"); }
    public byte[] getOsAppId() { return (byte[]) huskProps.get("OsAppId"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.telephony.data.TrafficDescriptor build() { return null; }
        public android.telephony.data.TrafficDescriptor.Builder setDataNetworkName(java.lang.String p0) { huskProps.put("DataNetworkName", p0); return this; }
        public android.telephony.data.TrafficDescriptor.Builder setOsAppId(byte[] p0) { huskProps.put("OsAppId", p0); return this; }
    }
    public static final class OsAppId {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static java.util.UUID ANDROID_OS_ID;
        public OsAppId(java.util.UUID p0, java.lang.String p1) {}
        public OsAppId(java.util.UUID p0, java.lang.String p1, int p2) {}
        public OsAppId(byte[] p0) {}
        public java.lang.String getAppId() { return (java.lang.String) huskProps.get("AppId"); }
        public byte[] getBytes() { return (byte[]) huskProps.get("Bytes"); }
        public int getDifferentiator() { return (huskProps.get("Differentiator") instanceof Integer ? (Integer) huskProps.get("Differentiator") : 0); }
        public java.util.UUID getOsId() { return (java.util.UUID) huskProps.get("OsId"); }
    }
}
