// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.backup;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class BackupAgent extends android.content.ContextWrapper {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int FLAG_CLIENT_SIDE_ENCRYPTION_ENABLED = 1;
    public static final int FLAG_CROSS_PLATFORM_DATA_TRANSFER_IOS = 8;
    public static final int FLAG_DEVICE_TO_DEVICE_TRANSFER = 2;
    public static final int FLAG_FAKE_CLIENT_SIDE_ENCRYPTION_ENABLED = -2147483648;
    public static final int FLAG_SKIP_RESTORE_FOR_LAUNCHED_APPS = 4;
    public static final int RESULT_ERROR = -1;
    public static final int RESULT_SUCCESS = 0;
    public static final int TYPE_DIRECTORY = 2;
    public static final int TYPE_EOF = 0;
    public static final int TYPE_FILE = 1;
    public static final int TYPE_SYMLINK = 3;
    public BackupAgent() { super((android.content.Context) null); }
    public void attach(android.content.Context p0) {}
    public void clearBackupRestoreEventLogger() {}
    public void fullBackupFile(java.io.File p0, android.app.backup.FullBackupDataOutput p1) {}
    protected void fullBackupFileTree(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.util.Set p3, android.util.ArraySet p4, android.app.backup.FullBackupDataOutput p5) {}
    public android.app.backup.BackupRestoreEventLogger getBackupRestoreEventLogger() { return (android.app.backup.BackupRestoreEventLogger) huskProps.get("BackupRestoreEventLogger"); }
    public android.app.backup.BackupAgent.IncludeExcludeRules getIncludeExcludeRules(android.app.backup.FullBackup.BackupScheme p0) { return null; }
    public abstract void onBackup(android.os.ParcelFileDescriptor p0, android.app.backup.BackupDataOutput p1, android.os.ParcelFileDescriptor p2);
    public android.os.IBinder onBind() { return null; }
    public void onCreate() {}
    public void onCreate(android.os.UserHandle p0) {}
    public void onCreate(android.os.UserHandle p0, int p1) {}
    public void onCreate(android.os.UserHandle p0, int p1, int p2) {}
    public void onDestroy() {}
    public long onEstimateFullBackupBytes(long p0, int p1) { return 0L; }
    public void onFullBackup(android.app.backup.FullBackupDataOutput p0) {}
    public void onQuotaExceeded(long p0, long p1) {}
    public abstract void onRestore(android.app.backup.BackupDataInput p0, int p1, android.os.ParcelFileDescriptor p2);
    public void onRestore(android.app.backup.BackupDataInput p0, long p1, android.os.ParcelFileDescriptor p2) {}
    public void onRestore(android.app.backup.BackupDataInput p0, long p1, android.os.ParcelFileDescriptor p2, java.util.Set p3) {}
    public void onRestoreFile(android.app.backup.FullRestoreDataInput p0) {}
    protected void onRestoreFile(android.os.ParcelFileDescriptor p0, long p1, int p2, java.lang.String p3, java.lang.String p4, long p5, long p6, long p7, int p8, java.lang.String p9) {}
    public void onRestoreFile(android.os.ParcelFileDescriptor p0, long p1, java.io.File p2, int p3, long p4, long p5) {}
    public void onRestoreFinished() {}
    public static class IncludeExcludeRules {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public IncludeExcludeRules(java.util.Map p0, java.util.Set p1) {}
        public static android.app.backup.BackupAgent.IncludeExcludeRules emptyRules() { return new IncludeExcludeRules(); }
        IncludeExcludeRules() { this((java.util.Map) null, (java.util.Set) null); }
    }
}
