// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.graphics.pdf.content;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class PdfPageTextContent implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public PdfPageTextContent(java.lang.String p0) {}
    public PdfPageTextContent(java.lang.String p0, java.util.List p1) {}
    public int describeContents() { return 0; }
    public java.util.List getBounds() { return (huskProps.get("Bounds") != null ? (java.util.List) huskProps.get("Bounds") : new java.util.ArrayList()); }
    public java.lang.String getText() { return (java.lang.String) huskProps.get("Text"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    PdfPageTextContent() { this((java.lang.String) null); }
}
