// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.graphics.fonts;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class FontStyle {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int FONT_SLANT_ITALIC = 1;
    public static final int FONT_SLANT_UPRIGHT = 0;
    public static final int FONT_WEIGHT_BLACK = 900;
    public static final int FONT_WEIGHT_BOLD = 700;
    public static final int FONT_WEIGHT_EXTRA_BOLD = 800;
    public static final int FONT_WEIGHT_EXTRA_LIGHT = 200;
    public static final int FONT_WEIGHT_LIGHT = 300;
    public static final int FONT_WEIGHT_MAX = 1000;
    public static final int FONT_WEIGHT_MEDIUM = 500;
    public static final int FONT_WEIGHT_MIN = 1;
    public static final int FONT_WEIGHT_NORMAL = 400;
    public static final int FONT_WEIGHT_SEMI_BOLD = 600;
    public static final int FONT_WEIGHT_THIN = 100;
    public static final int FONT_WEIGHT_UNSPECIFIED = -1;
    public FontStyle() {}
    public FontStyle(int p0, int p1) {}
    public int getMatchScore(android.graphics.fonts.FontStyle p0) { return 0; }
    public int getSlant() { return (huskProps.get("Slant") instanceof Integer ? (Integer) huskProps.get("Slant") : 0); }
    public int getWeight() { return (huskProps.get("Weight") instanceof Integer ? (Integer) huskProps.get("Weight") : 0); }
}
