// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.os;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class LimitExceededException extends java.lang.IllegalStateException {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public LimitExceededException() { super(); }
    public LimitExceededException(java.lang.String p0) { super(); }
}
