// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.os;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ProfilingResult implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final int ERROR_FAILED_EXECUTING = 4;
    public static final int ERROR_FAILED_INVALID_REQUEST = 7;
    public static final int ERROR_FAILED_NO_DISK_SPACE = 6;
    public static final int ERROR_FAILED_POST_PROCESSING = 5;
    public static final int ERROR_FAILED_PROFILING_IN_PROGRESS = 3;
    public static final int ERROR_FAILED_RATE_LIMIT_PROCESS = 2;
    public static final int ERROR_FAILED_RATE_LIMIT_SYSTEM = 1;
    public static final int ERROR_NONE = 0;
    public static final int ERROR_UNKNOWN = 8;
    public ProfilingResult(int p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, int p4) {}
    public ProfilingResult(android.os.Parcel p0) {}
    public int describeContents() { return 0; }
    public int getErrorCode() { return (huskProps.get("ErrorCode") instanceof Integer ? (Integer) huskProps.get("ErrorCode") : 0); }
    public java.lang.String getErrorMessage() { return (java.lang.String) huskProps.get("ErrorMessage"); }
    public java.lang.String getResultFilePath() { return (java.lang.String) huskProps.get("ResultFilePath"); }
    public java.lang.String getTag() { return (java.lang.String) huskProps.get("Tag"); }
    public int getTriggerType() { return (huskProps.get("TriggerType") instanceof Integer ? (Integer) huskProps.get("TriggerType") : 0); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    ProfilingResult() { this((android.os.Parcel) null); }
}
