// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.os;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ServiceSpecificException extends java.lang.RuntimeException {
    protected ServiceSpecificException() { super(); }
}
