// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.preference;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ListPreference extends android.preference.DialogPreference {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ListPreference(android.content.Context p0) { super(p0); }
    public ListPreference(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public ListPreference(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public ListPreference(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public int findIndexOfValue(java.lang.String p0) { return 0; }
    public java.lang.CharSequence[] getEntries() { return (java.lang.CharSequence[]) huskProps.get("Entries"); }
    public java.lang.CharSequence getEntry() { return (java.lang.CharSequence) huskProps.get("Entry"); }
    public java.lang.CharSequence[] getEntryValues() { return (java.lang.CharSequence[]) huskProps.get("EntryValues"); }
    public java.lang.CharSequence getSummary() { return (java.lang.CharSequence) huskProps.get("Summary"); }
    public java.lang.String getValue() { return (java.lang.String) huskProps.get("Value"); }
    public void onDialogClosed(boolean p0) {}
    public java.lang.Object onGetDefaultValue(android.content.res.TypedArray p0, int p1) { return null; }
    public void onPrepareDialogBuilder(android.app.AlertDialog.Builder p0) {}
    public void onRestoreInstanceState(android.os.Parcelable p0) {}
    public android.os.Parcelable onSaveInstanceState() { return null; }
    public void onSetInitialValue(boolean p0, java.lang.Object p1) {}
    public void setEntries(int p0) { huskProps.put("Entries", Integer.valueOf(p0)); }
    public void setEntries(java.lang.CharSequence[] p0) { huskProps.put("Entries", p0); }
    public void setEntryValues(int p0) { huskProps.put("EntryValues", Integer.valueOf(p0)); }
    public void setEntryValues(java.lang.CharSequence[] p0) { huskProps.put("EntryValues", p0); }
    public void setSummary(java.lang.CharSequence p0) { huskProps.put("Summary", p0); }
    public void setValue(java.lang.String p0) { huskProps.put("Value", p0); }
    public void setValueIndex(int p0) { huskProps.put("ValueIndex", Integer.valueOf(p0)); }
}
