// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.preference;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Preference implements java.lang.Comparable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int DEFAULT_ORDER = 2147483647;
    public Preference(android.content.Context p0) {}
    public Preference(android.content.Context p0, android.util.AttributeSet p1) {}
    public Preference(android.content.Context p0, android.util.AttributeSet p1, int p2) {}
    public Preference(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) {}
    protected boolean callChangeListener(java.lang.Object p0) { return false; }
    public int compareTo(android.preference.Preference p0) { return 0; }
    public int compareTo(java.lang.Object p0) { return 0; }
    protected android.preference.Preference findPreferenceInHierarchy(java.lang.String p0) { return this; }
    public android.content.Context getContext() { return (android.content.Context) huskProps.get("Context"); }
    public java.lang.String getDependency() { return (java.lang.String) huskProps.get("Dependency"); }
    public android.content.SharedPreferences.Editor getEditor() { return (android.content.SharedPreferences.Editor) huskProps.get("Editor"); }
    public android.os.Bundle getExtras() { return (android.os.Bundle) huskProps.get("Extras"); }
    public java.lang.String getFragment() { return (java.lang.String) huskProps.get("Fragment"); }
    public android.graphics.drawable.Drawable getIcon() { return (android.graphics.drawable.Drawable) huskProps.get("Icon"); }
    public android.content.Intent getIntent() { return (android.content.Intent) huskProps.get("Intent"); }
    public java.lang.String getKey() { return (java.lang.String) huskProps.get("Key"); }
    public int getLayoutResource() { return (huskProps.get("LayoutResource") instanceof Integer ? (Integer) huskProps.get("LayoutResource") : 0); }
    public android.preference.Preference.OnPreferenceChangeListener getOnPreferenceChangeListener() { return (android.preference.Preference.OnPreferenceChangeListener) huskProps.get("OnPreferenceChangeListener"); }
    public android.preference.Preference.OnPreferenceClickListener getOnPreferenceClickListener() { return (android.preference.Preference.OnPreferenceClickListener) huskProps.get("OnPreferenceClickListener"); }
    public int getOrder() { return (huskProps.get("Order") instanceof Integer ? (Integer) huskProps.get("Order") : 0); }
    public android.preference.PreferenceGroup getParent() { return (android.preference.PreferenceGroup) huskProps.get("Parent"); }
    protected boolean getPersistedBoolean(boolean p0) { return false; }
    protected float getPersistedFloat(float p0) { return 0f; }
    protected int getPersistedInt(int p0) { return 0; }
    protected long getPersistedLong(long p0) { return 0L; }
    protected java.lang.String getPersistedString(java.lang.String p0) { return null; }
    public java.util.Set getPersistedStringSet(java.util.Set p0) { return new java.util.HashSet(); }
    public android.preference.PreferenceDataStore getPreferenceDataStore() { return (android.preference.PreferenceDataStore) huskProps.get("PreferenceDataStore"); }
    public android.preference.PreferenceManager getPreferenceManager() { return (android.preference.PreferenceManager) huskProps.get("PreferenceManager"); }
    public android.content.SharedPreferences getSharedPreferences() { return (android.content.SharedPreferences) huskProps.get("SharedPreferences"); }
    public boolean getShouldDisableView() { return (huskProps.get("ShouldDisableView") instanceof Boolean ? (Boolean) huskProps.get("ShouldDisableView") : false); }
    public java.lang.CharSequence getSummary() { return (java.lang.CharSequence) huskProps.get("Summary"); }
    public java.lang.CharSequence getTitle() { return (java.lang.CharSequence) huskProps.get("Title"); }
    public int getTitleRes() { return (huskProps.get("TitleRes") instanceof Integer ? (Integer) huskProps.get("TitleRes") : 0); }
    public android.view.View getView(android.view.View p0, android.view.ViewGroup p1) { return null; }
    public int getWidgetLayoutResource() { return (huskProps.get("WidgetLayoutResource") instanceof Integer ? (Integer) huskProps.get("WidgetLayoutResource") : 0); }
    public boolean hasKey() { return false; }
    public boolean isEnabled() { return (huskProps.get("Enabled") instanceof Boolean ? (Boolean) huskProps.get("Enabled") : false); }
    public boolean isIconSpaceReserved() { return (huskProps.get("IconSpaceReserved") instanceof Boolean ? (Boolean) huskProps.get("IconSpaceReserved") : false); }
    public boolean isPersistent() { return (huskProps.get("Persistent") instanceof Boolean ? (Boolean) huskProps.get("Persistent") : false); }
    public boolean isRecycleEnabled() { return (huskProps.get("RecycleEnabled") instanceof Boolean ? (Boolean) huskProps.get("RecycleEnabled") : false); }
    public boolean isSelectable() { return (huskProps.get("Selectable") instanceof Boolean ? (Boolean) huskProps.get("Selectable") : false); }
    public boolean isSingleLineTitle() { return (huskProps.get("SingleLineTitle") instanceof Boolean ? (Boolean) huskProps.get("SingleLineTitle") : false); }
    protected void notifyChanged() {}
    public void notifyDependencyChange(boolean p0) {}
    protected void notifyHierarchyChanged() {}
    protected void onAttachedToActivity() {}
    protected void onAttachedToHierarchy(android.preference.PreferenceManager p0) {}
    protected void onBindView(android.view.View p0) {}
    protected void onClick() {}
    protected android.view.View onCreateView(android.view.ViewGroup p0) { return null; }
    public void onDependencyChanged(android.preference.Preference p0, boolean p1) {}
    protected java.lang.Object onGetDefaultValue(android.content.res.TypedArray p0, int p1) { return null; }
    public boolean onKey(android.view.View p0, int p1, android.view.KeyEvent p2) { return false; }
    public void onParentChanged(android.preference.Preference p0, boolean p1) {}
    protected void onPrepareForRemoval() {}
    protected void onRestoreInstanceState(android.os.Parcelable p0) {}
    protected android.os.Parcelable onSaveInstanceState() { return null; }
    protected void onSetInitialValue(boolean p0, java.lang.Object p1) {}
    public android.os.Bundle peekExtras() { return null; }
    public void performClick(android.preference.PreferenceScreen p0) {}
    protected boolean persistBoolean(boolean p0) { return false; }
    protected boolean persistFloat(float p0) { return false; }
    protected boolean persistInt(int p0) { return false; }
    protected boolean persistLong(long p0) { return false; }
    protected boolean persistString(java.lang.String p0) { return false; }
    public boolean persistStringSet(java.util.Set p0) { return false; }
    public void restoreHierarchyState(android.os.Bundle p0) {}
    public void saveHierarchyState(android.os.Bundle p0) {}
    public void setDefaultValue(java.lang.Object p0) { huskProps.put("DefaultValue", p0); }
    public void setDependency(java.lang.String p0) { huskProps.put("Dependency", p0); }
    public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
    public void setFragment(java.lang.String p0) { huskProps.put("Fragment", p0); }
    public void setIcon(int p0) { huskProps.put("Icon", Integer.valueOf(p0)); }
    public void setIcon(android.graphics.drawable.Drawable p0) { huskProps.put("Icon", p0); }
    public void setIconSpaceReserved(boolean p0) { huskProps.put("IconSpaceReserved", Boolean.valueOf(p0)); }
    public void setIntent(android.content.Intent p0) { huskProps.put("Intent", p0); }
    public void setKey(java.lang.String p0) { huskProps.put("Key", p0); }
    public void setLayoutResource(int p0) { huskProps.put("LayoutResource", Integer.valueOf(p0)); }
    public void setOnPreferenceChangeListener(android.preference.Preference.OnPreferenceChangeListener p0) { huskProps.put("OnPreferenceChangeListener", p0); }
    public void setOnPreferenceClickListener(android.preference.Preference.OnPreferenceClickListener p0) { huskProps.put("OnPreferenceClickListener", p0); }
    public void setOrder(int p0) { huskProps.put("Order", Integer.valueOf(p0)); }
    public void setPersistent(boolean p0) { huskProps.put("Persistent", Boolean.valueOf(p0)); }
    public void setPreferenceDataStore(android.preference.PreferenceDataStore p0) { huskProps.put("PreferenceDataStore", p0); }
    public void setRecycleEnabled(boolean p0) { huskProps.put("RecycleEnabled", Boolean.valueOf(p0)); }
    public void setSelectable(boolean p0) { huskProps.put("Selectable", Boolean.valueOf(p0)); }
    public void setShouldDisableView(boolean p0) { huskProps.put("ShouldDisableView", Boolean.valueOf(p0)); }
    public void setSingleLineTitle(boolean p0) { huskProps.put("SingleLineTitle", Boolean.valueOf(p0)); }
    public void setSummary(int p0) { huskProps.put("Summary", Integer.valueOf(p0)); }
    public void setSummary(java.lang.CharSequence p0) { huskProps.put("Summary", p0); }
    public void setTitle(int p0) { huskProps.put("Title", Integer.valueOf(p0)); }
    public void setTitle(java.lang.CharSequence p0) { huskProps.put("Title", p0); }
    public void setWidgetLayoutResource(int p0) { huskProps.put("WidgetLayoutResource", Integer.valueOf(p0)); }
    public boolean shouldCommit() { return false; }
    public boolean shouldDisableDependents() { return false; }
    protected boolean shouldPersist() { return false; }
    public static class BaseSavedState extends android.view.AbsSavedState {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public BaseSavedState(android.os.Parcel p0) { super(p0); }
        public BaseSavedState(android.os.Parcelable p0) { super(p0); }
    }
    public interface OnPreferenceChangeListener {
        boolean onPreferenceChange(android.preference.Preference p0, java.lang.Object p1);
    }
    public interface OnPreferenceClickListener {
        boolean onPreferenceClick(android.preference.Preference p0);
    }
}
