// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.adselection;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class AdSelectionFromOutcomesConfig implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public int describeContents() { return 0; }
    public java.util.List getAdSelectionIds() { return (huskProps.get("AdSelectionIds") != null ? (java.util.List) huskProps.get("AdSelectionIds") : new java.util.ArrayList()); }
    public android.net.Uri getSelectionLogicUri() { return (android.net.Uri) huskProps.get("SelectionLogicUri"); }
    public android.adservices.common.AdSelectionSignals getSelectionSignals() { return (android.adservices.common.AdSelectionSignals) huskProps.get("SelectionSignals"); }
    public android.adservices.common.AdTechIdentifier getSeller() { return (android.adservices.common.AdTechIdentifier) huskProps.get("Seller"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected AdSelectionFromOutcomesConfig() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.adservices.adselection.AdSelectionFromOutcomesConfig build() { android.adservices.adselection.AdSelectionFromOutcomesConfig x = new android.adservices.adselection.AdSelectionFromOutcomesConfig(); x.huskProps.putAll(huskProps); return x; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setAdSelectionIds(java.util.List p0) { huskProps.put("AdSelectionIds", p0); return this; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSelectionLogicUri(android.net.Uri p0) { huskProps.put("SelectionLogicUri", p0); return this; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSelectionSignals(android.adservices.common.AdSelectionSignals p0) { huskProps.put("SelectionSignals", p0); return this; }
        public android.adservices.adselection.AdSelectionFromOutcomesConfig.Builder setSeller(android.adservices.common.AdTechIdentifier p0) { huskProps.put("Seller", p0); return this; }
    }
}
