// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.adselection;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class RemoveAdCounterHistogramOverrideRequest {
    protected RemoveAdCounterHistogramOverrideRequest() {}
}
