// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.usage;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class EventStats implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public long mBeginTimeStamp;
    public int mCount;
    public long mEndTimeStamp;
    public int mEventType;
    public long mLastEventTime;
    public long mTotalTime;
    public EventStats() {}
    public EventStats(android.app.usage.EventStats p0) {}
    public void add(android.app.usage.EventStats p0) {}
    public int describeContents() { return 0; }
    public int getCount() { return (huskProps.get("Count") instanceof Integer ? (Integer) huskProps.get("Count") : 0); }
    public int getEventType() { return (huskProps.get("EventType") instanceof Integer ? (Integer) huskProps.get("EventType") : 0); }
    public long getFirstTimeStamp() { return (huskProps.get("FirstTimeStamp") instanceof Long ? (Long) huskProps.get("FirstTimeStamp") : 0L); }
    public long getLastEventTime() { return (huskProps.get("LastEventTime") instanceof Long ? (Long) huskProps.get("LastEventTime") : 0L); }
    public long getLastTimeStamp() { return (huskProps.get("LastTimeStamp") instanceof Long ? (Long) huskProps.get("LastTimeStamp") : 0L); }
    public long getTotalTime() { return (huskProps.get("TotalTime") instanceof Long ? (Long) huskProps.get("TotalTime") : 0L); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
