// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.usage;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface IUsageStatsManager extends android.os.IInterface {
}
