// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class EventUrlProvider {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public EventUrlProvider(android.adservices.ondevicepersonalization.aidl.IDataAccessService p0) {}
    public android.net.Uri createEventTrackingUrlWithRedirect(android.os.PersistableBundle p0, android.net.Uri p1) { return null; }
    public android.net.Uri createEventTrackingUrlWithResponse(android.os.PersistableBundle p0, byte[] p1, java.lang.String p2) { return null; }
    EventUrlProvider() { this((android.adservices.ondevicepersonalization.aidl.IDataAccessService) null); }
}
