// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class FederatedComputeInput {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public java.lang.String getPopulationName() { return (java.lang.String) huskProps.get("PopulationName"); }
    protected FederatedComputeInput() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.adservices.ondevicepersonalization.FederatedComputeInput build() { return new android.adservices.ondevicepersonalization.FederatedComputeInput(); }
        public android.adservices.ondevicepersonalization.FederatedComputeInput.Builder setPopulationName(java.lang.String p0) { huskProps.put("PopulationName", p0); return this; }
    }
}
