// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class OnDevicePersonalizationException extends java.lang.Exception {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int ERROR_INFERENCE_FAILED = 9;
    public static final int ERROR_INFERENCE_MODEL_NOT_FOUND = 8;
    public static final int ERROR_INVALID_TRAINING_MANIFEST = 7;
    public static final int ERROR_ISOLATED_SERVICE_FAILED = 1;
    public static final int ERROR_ISOLATED_SERVICE_LOADING_FAILED = 3;
    public static final int ERROR_ISOLATED_SERVICE_MANIFEST_PARSING_FAILED = 4;
    public static final int ERROR_ISOLATED_SERVICE_TIMEOUT = 5;
    public static final int ERROR_PERSONALIZATION_DISABLED = 2;
    public static final int ERROR_SCHEDULE_TRAINING_FAILED = 6;
    public OnDevicePersonalizationException(int p0) { super(); }
    public OnDevicePersonalizationException(int p0, java.lang.String p1) { super(); }
    public OnDevicePersonalizationException(int p0, java.lang.String p1, java.lang.Throwable p2) { super(); }
    public OnDevicePersonalizationException(int p0, java.lang.Throwable p1) { super(); }
    public static boolean isValidErrorCode(int p0) { return false; }
    public int getErrorCode() { return (huskProps.get("ErrorCode") instanceof Integer ? (Integer) huskProps.get("ErrorCode") : 0); }
    OnDevicePersonalizationException() { this((int) 0); }
}
