// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class RenderInput {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public RenderInput(int p0, int p1, android.adservices.ondevicepersonalization.RenderingConfig p2) {}
    public RenderInput(android.adservices.ondevicepersonalization.RenderInputParcel p0) {}
    public int getHeight() { return (huskProps.get("Height") instanceof Integer ? (Integer) huskProps.get("Height") : 0); }
    public android.adservices.ondevicepersonalization.RenderingConfig getRenderingConfig() { return (android.adservices.ondevicepersonalization.RenderingConfig) huskProps.get("RenderingConfig"); }
    public int getWidth() { return (huskProps.get("Width") instanceof Integer ? (Integer) huskProps.get("Width") : 0); }
    RenderInput() { this((android.adservices.ondevicepersonalization.RenderInputParcel) null); }
}
