// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class UserData implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public int describeContents() { return 0; }
    public java.util.Map getAppInfos() { return (huskProps.get("AppInfos") != null ? (java.util.Map) huskProps.get("AppInfos") : new java.util.HashMap()); }
    public long getAvailableStorageBytes() { return (huskProps.get("AvailableStorageBytes") instanceof Long ? (Long) huskProps.get("AvailableStorageBytes") : 0L); }
    public int getBatteryPercentage() { return (huskProps.get("BatteryPercentage") instanceof Integer ? (Integer) huskProps.get("BatteryPercentage") : 0); }
    public java.lang.String getCarrier() { return (java.lang.String) huskProps.get("Carrier"); }
    public int getDataNetworkType() { return (huskProps.get("DataNetworkType") instanceof Integer ? (Integer) huskProps.get("DataNetworkType") : 0); }
    public android.net.NetworkCapabilities getNetworkCapabilities() { return (android.net.NetworkCapabilities) huskProps.get("NetworkCapabilities"); }
    public int getOrientation() { return (huskProps.get("Orientation") instanceof Integer ? (Integer) huskProps.get("Orientation") : 0); }
    public java.time.Duration getTimezoneUtcOffset() { return (java.time.Duration) huskProps.get("TimezoneUtcOffset"); }
    public int getTimezoneUtcOffsetMins() { return (huskProps.get("TimezoneUtcOffsetMins") instanceof Integer ? (Integer) huskProps.get("TimezoneUtcOffsetMins") : 0); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected UserData() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.adservices.ondevicepersonalization.UserData.Builder addAppInfo(java.lang.String p0, android.adservices.ondevicepersonalization.AppInfo p1) { return this; }
        public android.adservices.ondevicepersonalization.UserData build() { android.adservices.ondevicepersonalization.UserData x = new android.adservices.ondevicepersonalization.UserData(); x.huskProps.putAll(huskProps); return x; }
        public android.adservices.ondevicepersonalization.UserData.Builder setAppInfos(java.util.Map p0) { huskProps.put("AppInfos", p0); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setAvailableStorageBytes(long p0) { huskProps.put("AvailableStorageBytes", Long.valueOf(p0)); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setBatteryPercentage(int p0) { huskProps.put("BatteryPercentage", Integer.valueOf(p0)); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setCarrier(java.lang.String p0) { huskProps.put("Carrier", p0); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setDataNetworkType(int p0) { huskProps.put("DataNetworkType", Integer.valueOf(p0)); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setNetworkCapabilities(android.net.NetworkCapabilities p0) { huskProps.put("NetworkCapabilities", p0); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setOrientation(int p0) { huskProps.put("Orientation", Integer.valueOf(p0)); return this; }
        public android.adservices.ondevicepersonalization.UserData.Builder setTimezoneUtcOffsetMins(int p0) { huskProps.put("TimezoneUtcOffsetMins", Integer.valueOf(p0)); return this; }
    }
}
