// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.people;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ConversationChannel implements android.os.Parcelable {
    protected ConversationChannel() {}
}
