// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.util;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class MutableChar {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public char value;
    public MutableChar(char p0) {}
}
