// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.bluetooth;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class BluetoothCsipSetCoordinator implements android.bluetooth.BluetoothProfile, java.lang.AutoCloseable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_CSIS_CONNECTION_STATE_CHANGED = "android.bluetooth.action.CSIS_CONNECTION_STATE_CHANGED";
    public static final java.lang.String ACTION_CSIS_DEVICE_AVAILABLE = "android.bluetooth.action.CSIS_DEVICE_AVAILABLE";
    public static final java.lang.String ACTION_CSIS_SET_MEMBER_AVAILABLE = "android.bluetooth.action.CSIS_SET_MEMBER_AVAILABLE";
    public static final java.lang.String EXTRA_CSIS_GROUP_ID = "android.bluetooth.extra.CSIS_GROUP_ID";
    public static final java.lang.String EXTRA_CSIS_GROUP_SIZE = "android.bluetooth.extra.CSIS_GROUP_SIZE";
    public static final java.lang.String EXTRA_CSIS_GROUP_TYPE_UUID = "android.bluetooth.extra.CSIS_GROUP_TYPE_UUID";
    public static final int GROUP_ID_INVALID = -1;
    public void close() {}
    protected void finalize() {}
    public android.bluetooth.BluetoothAdapter getAdapter() { return (android.bluetooth.BluetoothAdapter) huskProps.get("Adapter"); }
    public java.util.List getAllGroupIds(android.os.ParcelUuid p0) { return new java.util.ArrayList(); }
    public java.util.List getConnectedDevices() { return (huskProps.get("ConnectedDevices") != null ? (java.util.List) huskProps.get("ConnectedDevices") : new java.util.ArrayList()); }
    public int getConnectionPolicy(android.bluetooth.BluetoothDevice p0) { return 0; }
    public int getConnectionState(android.bluetooth.BluetoothDevice p0) { return 0; }
    public java.util.List getDevicesMatchingConnectionStates(int[] p0) { return new java.util.ArrayList(); }
    public java.util.Map getGroupUuidMapByDevice(android.bluetooth.BluetoothDevice p0) { return new java.util.HashMap(); }
    public java.util.UUID lockGroup(int p0, java.util.concurrent.Executor p1, android.bluetooth.BluetoothCsipSetCoordinator.ClientLockCallback p2) { return null; }
    public void onServiceConnected(android.os.IBinder p0) {}
    public void onServiceDisconnected() {}
    public boolean setConnectionPolicy(android.bluetooth.BluetoothDevice p0, int p1) { return false; }
    public boolean unlockGroup(java.util.UUID p0) { return false; }
    protected BluetoothCsipSetCoordinator() {}
    public interface ClientLockCallback {
        void onGroupLockSet(int p0, int p1, boolean p2);
    }
}
