package android.graphics;

/** A canvas a RenderNode records into: here an ordinary canvas on the node's bitmap. */
public class BaseRecordingCanvas extends Canvas {
    BaseRecordingCanvas(Bitmap b) { super(b); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public void drawColor(long p0, android.graphics.BlendMode p1) {}
    public void drawDoubleRoundRect(android.graphics.RectF p0, float[] p1, android.graphics.RectF p2, float[] p3, android.graphics.Paint p4) {}
    public void drawMesh(android.graphics.Mesh p0, android.graphics.BlendMode p1, android.graphics.Paint p2) {}
    public void drawPatch(android.graphics.NinePatch p0, android.graphics.Rect p1, android.graphics.Paint p2) {}
    public void drawPatch(android.graphics.NinePatch p0, android.graphics.RectF p1, android.graphics.Paint p2) {}
    public void drawRegion(android.graphics.Region p0, android.graphics.Paint p1) {}
    public void drawTextRun(android.graphics.text.MeasuredText p0, int p1, int p2, int p3, int p4, float p5, float p6, boolean p7, android.graphics.Paint p8) {}
    public void punchHole(float p0, float p1, float p2, float p3, float p4, float p5, float p6) {}
    // ---- end of generated members
}
