package android.graphics;
/** Approximated: a multiply by the colour, the addition left out. */
public class LightingColorFilter extends ColorFilter {
    public LightingColorFilter(int mul, int add) { color = 0xFF000000 | mul; mode = 13; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public int getColorAdd() { return (huskFill.get("ColorAdd") instanceof Integer ? (Integer) huskFill.get("ColorAdd") : 0); }
    public int getColorMultiply() { return (huskFill.get("ColorMultiply") instanceof Integer ? (Integer) huskFill.get("ColorMultiply") : 0); }
    public void setColorAdd(int p0) { huskFill.put("ColorAdd", Integer.valueOf(p0)); }
    public void setColorMultiply(int p0) { huskFill.put("ColorMultiply", Integer.valueOf(p0)); }
    // ---- end of generated members
}
