package android.app;
public class AlarmManager {
    public static final int RTC_WAKEUP = 0, RTC = 1, ELAPSED_REALTIME_WAKEUP = 2, ELAPSED_REALTIME = 3;
    public static final long INTERVAL_FIFTEEN_MINUTES = 900000, INTERVAL_HALF_HOUR = 1800000, INTERVAL_HOUR = 3600000, INTERVAL_HALF_DAY = 43200000, INTERVAL_DAY = 86400000;
    public static final String ACTION_NEXT_ALARM_CLOCK_CHANGED = "android.app.action.NEXT_ALARM_CLOCK_CHANGED", ACTION_SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED = "android.app.action.SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED";
    public interface OnAlarmListener { void onAlarm(); }
    public static class AlarmClockInfo implements android.os.Parcelable { public AlarmClockInfo(long t, PendingIntent p) {} public long getTriggerTime() { return 0; } public int describeContents() { return 0; }
        // ---- generated by tools/compat/fillmembers.py (AlarmClockInfo): the platform's members this class does not write (signatures only)
        public static android.os.Parcelable.Creator CREATOR;
        public void dumpDebug(android.util.proto.ProtoOutputStream p0, long p1) {}
        public android.app.PendingIntent getShowIntent() { return null; }
        // ---- end of generated members (AlarmClockInfo)
    }
    private final android.os.Handler mHandler = new android.os.Handler(android.os.Looper.getMainLooper());
    private long delay(int type, long at) { long now = type == RTC || type == RTC_WAKEUP ? System.currentTimeMillis() : android.os.SystemClock.elapsedRealtime(); return Math.max(0, at - now); }
    public void set(int type, long at, PendingIntent op) { mHandler.postDelayed(() -> { try { op.send(); } catch (PendingIntent.CanceledException e) {} }, delay(type, at)); }
    public void set(int type, long at, String tag, OnAlarmListener l, android.os.Handler h) { mHandler.postDelayed(l::onAlarm, delay(type, at)); }
    public void setExact(int type, long at, PendingIntent op) { set(type, at, op); }
    public void setExact(int type, long at, String tag, OnAlarmListener l, android.os.Handler h) { set(type, at, tag, l, h); }
    public void setExactAndAllowWhileIdle(int type, long at, PendingIntent op) { set(type, at, op); }
    public void setAndAllowWhileIdle(int type, long at, PendingIntent op) { set(type, at, op); }
    public void setWindow(int type, long start, long len, PendingIntent op) { set(type, start, op); }
    public void setRepeating(int type, long at, long interval, PendingIntent op) { set(type, at, op); }
    public void setInexactRepeating(int type, long at, long interval, PendingIntent op) { set(type, at, op); }
    public void setAlarmClock(AlarmClockInfo i, PendingIntent op) {}
    public void cancel(PendingIntent op) {}
    public void cancel(OnAlarmListener l) {}
    public void cancelAll() {}
    public boolean canScheduleExactAlarms() { return true; }
    public AlarmClockInfo getNextAlarmClock() { return null; }
    public void setTimeZone(String tz) {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final long ENABLE_USE_EXACT_ALARM = 218533173L;
    public static final long ENFORCE_MINIMUM_WINDOW_ON_INEXACT_ALARMS = 185199076L;
    public static final long EXACT_LISTENER_ALARMS_DROPPED_ON_CACHED = 265195908L;
    public static final int FLAG_ALLOW_WHILE_IDLE = 4;
    public static final int FLAG_ALLOW_WHILE_IDLE_COMPAT = 32;
    public static final int FLAG_ALLOW_WHILE_IDLE_UNRESTRICTED = 8;
    public static final int FLAG_IDLE_UNTIL = 16;
    public static final int FLAG_PRIORITIZE = 64;
    public static final int FLAG_STANDALONE = 1;
    public static final int FLAG_WAKE_FROM_IDLE = 2;
    public static final long REQUIRE_EXACT_ALARM_PERMISSION = 171306433L;
    public static final long SCHEDULE_EXACT_ALARM_DENIED_BY_DEFAULT = 226439802L;
    public static final long SCHEDULE_EXACT_ALARM_DOES_NOT_ELEVATE_BUCKET = 262645982L;
    public static final long WINDOW_EXACT = 0L;
    public static final long WINDOW_HEURISTIC = -1L;
    public android.app.AlarmManager.AlarmClockInfo getNextAlarmClock(int p0) { return null; }
    public long getNextWakeFromIdleTime() { return 0L; }
    public boolean hasScheduleExactAlarm(java.lang.String p0, int p1) { return false; }
    public void set(int p0, long p1, long p2, long p3, android.app.AlarmManager.OnAlarmListener p4, android.os.Handler p5, android.os.WorkSource p6) {}
    public void set(int p0, long p1, long p2, long p3, android.app.PendingIntent p4, android.os.WorkSource p5) {}
    public void set(int p0, long p1, long p2, long p3, java.lang.String p4, android.app.AlarmManager.OnAlarmListener p5, android.os.Handler p6, android.os.WorkSource p7) {}
    public void setExact(int p0, long p1, java.lang.String p2, java.util.concurrent.Executor p3, android.os.WorkSource p4, android.app.AlarmManager.OnAlarmListener p5) {}
    public void setExactAndAllowWhileIdle(int p0, long p1, java.lang.String p2, java.util.concurrent.Executor p3, android.os.WorkSource p4, android.app.AlarmManager.OnAlarmListener p5) {}
    public void setIdleUntil(int p0, long p1, java.lang.String p2, android.app.AlarmManager.OnAlarmListener p3, android.os.Handler p4) {}
    public void setPrioritized(int p0, long p1, long p2, java.lang.String p3, java.util.concurrent.Executor p4, android.app.AlarmManager.OnAlarmListener p5) {}
    public void setTime(long p0) {}
    public void setWindow(int p0, long p1, long p2, java.lang.String p3, android.app.AlarmManager.OnAlarmListener p4, android.os.Handler p5) {}
    public void setWindow(int p0, long p1, long p2, java.lang.String p3, java.util.concurrent.Executor p4, android.app.AlarmManager.OnAlarmListener p5) {}
    public void setWindow(int p0, long p1, long p2, java.lang.String p3, java.util.concurrent.Executor p4, android.os.WorkSource p5, android.app.AlarmManager.OnAlarmListener p6) {}
    // ---- end of generated members
}
