package android.app;
public final class NotificationChannel implements android.os.Parcelable {
    public static final String DEFAULT_CHANNEL_ID = "miscellaneous";
    private final String mId; private CharSequence mName; private int mImportance; private String mDesc, mGroup;
    public NotificationChannel(String id, CharSequence name, int importance) { mId = id; mName = name; mImportance = importance; }
    public String getId() { return mId; } public CharSequence getName() { return mName; } public void setName(CharSequence n) { mName = n; }
    public int getImportance() { return mImportance; } public void setImportance(int i) { mImportance = i; }
    public String getDescription() { return mDesc; } public void setDescription(String d) { mDesc = d; }
    public String getGroup() { return mGroup; } public void setGroup(String g) { mGroup = g; }
    public void setShowBadge(boolean b) {} public void setSound(android.net.Uri u, android.media.AudioAttributes a) {} public void enableLights(boolean b) {} public void setLightColor(int c) {}
    public void enableVibration(boolean b) {} public void setVibrationPattern(long[] p) {} public void setLockscreenVisibility(int v) {} public void setBypassDnd(boolean b) {}
    public boolean canShowBadge() { return true; } public android.net.Uri getSound() { return null; } public boolean shouldVibrate() { return false; } public int getLockscreenVisibility() { return 0; }
    public void setAllowBubbles(boolean b) {} public void setBlockable(boolean b) {} public void setConversationId(String p, String c) {}
    public int describeContents() { return 0; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final int ALLOW_BUBBLE_OFF = 0;
    public static final int ALLOW_BUBBLE_ON = 1;
    public static android.os.Parcelable.Creator CREATOR;
    public static final int DEFAULT_ALLOW_BUBBLE = -1;
    public static final java.lang.String EDIT_CONVERSATION = "conversation";
    public static final java.lang.String EDIT_IMPORTANCE = "importance";
    public static final java.lang.String EDIT_LAUNCHER = "launcher";
    public static final java.lang.String EDIT_LOCKED_DEVICE = "locked";
    public static final java.lang.String EDIT_SOUND = "sound";
    public static final java.lang.String EDIT_VIBRATION = "vibration";
    public static final java.lang.String EDIT_ZEN = "zen";
    public static int[] LOCKABLE_FIELDS;
    public static final int MAX_SERIALIZED_VIBRATION_LENGTH = 32768;
    public static final int MAX_TEXT_LENGTH = 1000;
    public static final int MAX_VIBRATION_LENGTH = 500;
    public static final java.lang.String NEWS_ID = "android.app.news";
    public static final java.lang.String OLD_CONVERSATION_CHANNEL_ID_FORMAT = "%1$s : %2$s";
    public static final java.lang.String PLACEHOLDER_CONVERSATION_ID = ":placeholder_id";
    public static final java.lang.String PROMOTIONS_ID = "android.app.promotions";
    public static final java.lang.String RECS_ID = "android.app.recs";
    public static final java.lang.String SOCIAL_MEDIA_ID = "android.app.social";
    public static java.util.ArrayList SYSTEM_RESERVED_IDS;
    public static final int USER_LOCKED_ALLOW_BUBBLE = 256;
    public static final int USER_LOCKED_IMPORTANCE = 4;
    public static final int USER_LOCKED_LIGHTS = 8;
    public static final int USER_LOCKED_PRIORITY = 1;
    public static final int USER_LOCKED_SHOW_BADGE = 128;
    public static final int USER_LOCKED_SOUND = 32;
    public static final int USER_LOCKED_VIBRATION = 16;
    public static final int USER_LOCKED_VISIBILITY = 2;
    public static java.lang.String getChannelIdForBundleType(int p0) { return null; }
    public boolean canBubble() { return false; }
    public boolean canBypassDnd() { return false; }
    public android.app.NotificationChannel copy() { return this; }
    public void dump(java.io.PrintWriter p0, java.lang.String p1, boolean p2) {}
    public void dumpDebug(android.util.proto.ProtoOutputStream p0, long p1) {}
    public int getAllowBubbles() { return (huskFill.get("AllowBubbles") instanceof Integer ? (Integer) huskFill.get("AllowBubbles") : 0); }
    public android.media.AudioAttributes getAudioAttributes() { return null; }
    public java.lang.String getConversationId() { return null; }
    public long getDeletedTimeMs() { return (huskFill.get("DeletedTimeMs") instanceof Long ? (Long) huskFill.get("DeletedTimeMs") : 0L); }
    public long getLastNotificationUpdateTimeMs() { return (huskFill.get("LastNotificationUpdateTimeMs") instanceof Long ? (Long) huskFill.get("LastNotificationUpdateTimeMs") : 0L); }
    public int getLightColor() { return 0; }
    public int getOriginalImportance() { return (huskFill.get("OriginalImportance") instanceof Integer ? (Integer) huskFill.get("OriginalImportance") : 0); }
    public java.lang.String getParentChannelId() { return null; }
    public int getUserLockedFields() { return 0; }
    public android.os.VibrationEffect getVibrationEffect() { return (android.os.VibrationEffect) huskFill.get("VibrationEffect"); }
    public long[] getVibrationPattern() { return null; }
    public boolean hasUserSetImportance() { return false; }
    public boolean hasUserSetSound() { return false; }
    public boolean isBlockable() { return false; }
    public boolean isConversation() { return false; }
    public boolean isDeleted() { return (huskFill.get("Deleted") instanceof Boolean ? (Boolean) huskFill.get("Deleted") : false); }
    public boolean isDemoted() { return (huskFill.get("Demoted") instanceof Boolean ? (Boolean) huskFill.get("Demoted") : false); }
    public boolean isImportanceLockedByCriticalDeviceFunction() { return (huskFill.get("ImportanceLockedByCriticalDeviceFunction") instanceof Boolean ? (Boolean) huskFill.get("ImportanceLockedByCriticalDeviceFunction") : false); }
    public boolean isImportantConversation() { return (huskFill.get("ImportantConversation") instanceof Boolean ? (Boolean) huskFill.get("ImportantConversation") : false); }
    public boolean isSoundRestored() { return false; }
    public boolean isUserVisibleTaskShown() { return (huskFill.get("UserVisibleTaskShown") instanceof Boolean ? (Boolean) huskFill.get("UserVisibleTaskShown") : false); }
    public void lockFields(int p0) {}
    public void populateFromXml(org.xmlpull.v1.XmlPullParser p0) {}
    public void populateFromXmlForRestore(org.xmlpull.v1.XmlPullParser p0, boolean p1, android.content.Context p2) {}
    public android.net.Uri restoreSoundUri(android.content.Context p0, android.net.Uri p1, boolean p2, int p3) { return null; }
    public void setAllowBubbles(int p0) { huskFill.put("AllowBubbles", Integer.valueOf(p0)); }
    public void setDeleted(boolean p0) { huskFill.put("Deleted", Boolean.valueOf(p0)); }
    public void setDeletedTimeMs(long p0) { huskFill.put("DeletedTimeMs", Long.valueOf(p0)); }
    public void setDemoted(boolean p0) { huskFill.put("Demoted", Boolean.valueOf(p0)); }
    public void setId(java.lang.String p0) {}
    public void setImportanceLockedByCriticalDeviceFunction(boolean p0) { huskFill.put("ImportanceLockedByCriticalDeviceFunction", Boolean.valueOf(p0)); }
    public void setImportantConversation(boolean p0) { huskFill.put("ImportantConversation", Boolean.valueOf(p0)); }
    public void setLastNotificationUpdateTimeMs(long p0) { huskFill.put("LastNotificationUpdateTimeMs", Long.valueOf(p0)); }
    public void setOriginalImportance(int p0) { huskFill.put("OriginalImportance", Integer.valueOf(p0)); }
    public void setUserVisibleTaskShown(boolean p0) { huskFill.put("UserVisibleTaskShown", Boolean.valueOf(p0)); }
    public void setVibrationEffect(android.os.VibrationEffect p0) { huskFill.put("VibrationEffect", p0); }
    public boolean shouldShowLights() { return false; }
    public org.json.JSONObject toJson() { return null; }
    public void unlockFields(int p0) {}
    public void writeXml(org.xmlpull.v1.XmlSerializer p0) {}
    public void writeXmlForBackup(org.xmlpull.v1.XmlSerializer p0, android.content.Context p1) {}
    // ---- end of generated members
}
