package android.os;

public class Build {
    public static final String MODEL = "Pixel 8", MANUFACTURER = "Google", BRAND = "google", DEVICE = "shiba", PRODUCT = "shiba";
    public static final String HARDWARE = "husk", BOARD = "shiba", DISPLAY = "AP1A", ID = "AP1A", TAGS = "release-keys", TYPE = "user";
    public static final String FINGERPRINT = "google/shiba/shiba:14/AP1A/1:user/release-keys", HOST = "husk", USER = "husk";
    public static final String SERIAL = "unknown", BOOTLOADER = "unknown", RADIO = "unknown";
    public static final String CPU_ABI = "arm64-v8a", CPU_ABI2 = "";
    public static final String[] SUPPORTED_ABIS = { "arm64-v8a" }, SUPPORTED_64_BIT_ABIS = { "arm64-v8a" }, SUPPORTED_32_BIT_ABIS = {};
    public static final long TIME = 0;
    public static String getSerial() { return SERIAL; }
    public static class VERSION {
        public static final int SDK_INT = 34, PREVIEW_SDK_INT = 0;
        public static final String RELEASE = "14", CODENAME = "REL", INCREMENTAL = "1", SDK = "34", SECURITY_PATCH = "2024-01-01";
        public static final String BASE_OS = "";
        // ---- generated by tools/compat/fillmembers.py (VERSION): the platform's members this class does not write (signatures only)
        public static java.lang.String[] ACTIVE_CODENAMES;
        public static int DEVICE_INITIAL_SDK_INT;
        public static java.util.Set KNOWN_CODENAMES;
        public static int MEDIA_PERFORMANCE_CLASS;
        public static int MIN_SUPPORTED_TARGET_SDK_INT;
        public static java.lang.String PREVIEW_SDK_FINGERPRINT;
        public static java.lang.String RELEASE_OR_CODENAME;
        public static java.lang.String RELEASE_OR_PREVIEW_DISPLAY;
        public static int RESOURCES_SDK_INT;
        public static int RESOURCES_SDK_INT_FULL;
        public static int SDK_INT_FULL;
        // ---- end of generated members (VERSION)
    }
    public static class VERSION_CODES {
        public static final int BASE = 1, CUPCAKE = 3, DONUT = 4, ECLAIR = 5, FROYO = 8, GINGERBREAD = 9, HONEYCOMB = 11,
            HONEYCOMB_MR1 = 12, HONEYCOMB_MR2 = 13, ICE_CREAM_SANDWICH = 14, JELLY_BEAN = 16, JELLY_BEAN_MR1 = 17, JELLY_BEAN_MR2 = 18,
            KITKAT = 19, KITKAT_WATCH = 20, LOLLIPOP = 21, LOLLIPOP_MR1 = 22, M = 23, N = 24, N_MR1 = 25, O = 26, O_MR1 = 27, P = 28,
            Q = 29, R = 30, S = 31, S_V2 = 32, TIRAMISU = 33, UPSIDE_DOWN_CAKE = 34, CUR_DEVELOPMENT = 10000;
        // ---- generated by tools/compat/fillmembers.py (VERSION_CODES): the platform's members this class does not write (signatures only)
        public static final int BAKLAVA = 36;
        public static final int BASE_1_1 = 2;
        public static final int ECLAIR_0_1 = 6;
        public static final int ECLAIR_MR1 = 7;
        public static final int GINGERBREAD_MR1 = 10;
        public static final int ICE_CREAM_SANDWICH_MR1 = 15;
        public static final int L = 21;
        public static final int VANILLA_ICE_CREAM = 35;
        // ---- end of generated members (VERSION_CODES)
    }
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static class Partition {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final java.lang.String PARTITION_NAME_BOOTIMAGE = "bootimage";
        public static final java.lang.String PARTITION_NAME_ODM = "odm";
        public static final java.lang.String PARTITION_NAME_OEM = "oem";
        public static final java.lang.String PARTITION_NAME_PRODUCT = "product";
        public static final java.lang.String PARTITION_NAME_SYSTEM = "system";
        public static final java.lang.String PARTITION_NAME_SYSTEM_EXT = "system_ext";
        public static final java.lang.String PARTITION_NAME_VENDOR = "vendor";
        public long getBuildTimeMillis() { return (huskProps.get("BuildTimeMillis") instanceof Long ? (Long) huskProps.get("BuildTimeMillis") : 0L); }
        public java.lang.String getFingerprint() { return (java.lang.String) huskProps.get("Fingerprint"); }
        public java.lang.String getName() { return (java.lang.String) huskProps.get("Name"); }
        protected Partition() {}
    }
    public static class VERSION_CODES_FULL {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int BAKLAVA = 3600000;
        public static final int BAKLAVA_1 = 3600001;
        public static final int BASE = 100000;
        public static final int BASE_1_1 = 200000;
        public static final int CUPCAKE = 300000;
        public static final int DONUT = 400000;
        public static final int ECLAIR = 500000;
        public static final int ECLAIR_0_1 = 600000;
        public static final int ECLAIR_MR1 = 700000;
        public static final int FROYO = 800000;
        public static final int GINGERBREAD = 900000;
        public static final int GINGERBREAD_MR1 = 1000000;
        public static final int HONEYCOMB = 1100000;
        public static final int HONEYCOMB_MR1 = 1200000;
        public static final int HONEYCOMB_MR2 = 1300000;
        public static final int ICE_CREAM_SANDWICH = 1400000;
        public static final int ICE_CREAM_SANDWICH_MR1 = 1500000;
        public static final int JELLY_BEAN = 1600000;
        public static final int JELLY_BEAN_MR1 = 1700000;
        public static final int JELLY_BEAN_MR2 = 1800000;
        public static final int KITKAT = 1900000;
        public static final int KITKAT_WATCH = 2000000;
        public static final int LOLLIPOP = 2100000;
        public static final int LOLLIPOP_MR1 = 2200000;
        public static final int M = 2300000;
        public static final int N = 2400000;
        public static final int N_MR1 = 2500000;
        public static final int O = 2600000;
        public static final int O_MR1 = 2700000;
        public static final int P = 2800000;
        public static final int Q = 2900000;
        public static final int R = 3000000;
        public static final int S = 3100000;
        public static final int S_V2 = 3200000;
        public static final int TIRAMISU = 3300000;
        public static final int UPSIDE_DOWN_CAKE = 3400000;
        public static final int VANILLA_ICE_CREAM = 3500000;
        protected VERSION_CODES_FULL() {}
    }
    // ---- end of generated nested classes
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final int BACKPORTED_FIX_STATUS_FIXED = 1;
    public static final int BACKPORTED_FIX_STATUS_NOT_APPLICABLE = 2;
    public static final int BACKPORTED_FIX_STATUS_NOT_FIXED = 3;
    public static final int BACKPORTED_FIX_STATUS_UNKNOWN = 0;
    public static java.lang.String BRAND_FOR_ATTESTATION;
    public static java.lang.String DEVICE_FOR_ATTESTATION;
    public static final int HW_TIMEOUT_MULTIPLIER = 0;
    public static final boolean IS_ARC = false;
    public static final boolean IS_DEBUGGABLE = false;
    public static final boolean IS_EMULATOR = false;
    public static final boolean IS_ENG = false;
    public static final boolean IS_USER = false;
    public static final boolean IS_USERDEBUG = false;
    public static java.lang.String MANUFACTURER_FOR_ATTESTATION;
    public static java.lang.String MODEL_FOR_ATTESTATION;
    public static java.lang.String ODM_SKU;
    public static final boolean PERMISSIONS_REVIEW_REQUIRED = true;
    public static java.lang.String PRODUCT_FOR_ATTESTATION;
    public static java.lang.String SKU;
    public static java.lang.String SOC_MANUFACTURER;
    public static java.lang.String SOC_MODEL;
    public static final java.lang.String UNKNOWN = "unknown";
    public static final int VENDOR_API_2024_Q2 = 202404;
    public static void ensureFingerprintProperty() {}
    public static java.lang.String fullVersionToString(int p0) { return null; }
    public static int getBackportedFixStatus(long p0) { return 0; }
    public static java.util.List getFingerprintedPartitions() { return new java.util.ArrayList(); }
    public static int getMajorSdkVersion(int p0) { return 0; }
    public static int getMinorSdkVersion(int p0) { return 0; }
    public static java.lang.String getRadioVersion() { return null; }
    public static boolean is64BitAbi(java.lang.String p0) { return false; }
    public static boolean isBuildConsistent() { return false; }
    public static boolean isDebuggable() { return false; }
    public static int parseFullVersion(java.lang.String p0) { return 0; }
    // ---- end of generated members
}
