package android.os;

import java.io.File;

public class Environment {
    public static final String MEDIA_MOUNTED = "mounted", MEDIA_MOUNTED_READ_ONLY = "mounted_ro";
    public static String DIRECTORY_DOWNLOADS = "Download", DIRECTORY_PICTURES = "Pictures", DIRECTORY_MUSIC = "Music", DIRECTORY_DOCUMENTS = "Documents";
    public static String DIRECTORY_ALARMS = "Alarms", DIRECTORY_AUDIOBOOKS = "Audiobooks", DIRECTORY_DCIM = "DCIM", DIRECTORY_MOVIES = "Movies",
        DIRECTORY_NOTIFICATIONS = "Notifications", DIRECTORY_PODCASTS = "Podcasts", DIRECTORY_RECORDINGS = "Recordings", DIRECTORY_RINGTONES = "Ringtones",
        DIRECTORY_SCREENSHOTS = "Screenshots";
    public static File getExternalStorageDirectory() { return new File(husk.Native.externalDir()); }
    public static File getExternalStoragePublicDirectory(String type) { return new File(husk.Native.externalDir(), type); }
    public static String getExternalStorageState() { return MEDIA_MOUNTED; }
    public static String getExternalStorageState(File f) { return MEDIA_MOUNTED; }
    public static File getDataDirectory() { return new File(husk.Native.dataDir()); }
    public static File getRootDirectory() { return new File("/system"); }
    public static File getDownloadCacheDirectory() { return new File(husk.Native.dataDir(), "cache"); }
    public static boolean isExternalStorageEmulated() { return true; }
    public static boolean isExternalStorageRemovable() { return false; }
    public static boolean isExternalStorageManager() { return true; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final java.lang.String DIRECTORY_ANDROID = "Android";
    public static final java.lang.String DIR_ANDROID = "Android";
    public static final java.lang.String DIR_USER_CE = "user";
    public static final java.lang.String DIR_USER_DE = "user_de";
    public static final int HAS_ALARMS = 8;
    public static final int HAS_ANDROID = 65536;
    public static final int HAS_AUDIOBOOKS = 1024;
    public static final int HAS_DCIM = 256;
    public static final int HAS_DOCUMENTS = 512;
    public static final int HAS_DOWNLOADS = 128;
    public static final int HAS_MOVIES = 64;
    public static final int HAS_MUSIC = 1;
    public static final int HAS_NOTIFICATIONS = 16;
    public static final int HAS_OTHER = 131072;
    public static final int HAS_PICTURES = 32;
    public static final int HAS_PODCASTS = 2;
    public static final int HAS_RECORDINGS = 2048;
    public static final int HAS_RINGTONES = 4;
    public static final java.lang.String MEDIA_BAD_REMOVAL = "bad_removal";
    public static final java.lang.String MEDIA_CHECKING = "checking";
    public static final java.lang.String MEDIA_EJECTING = "ejecting";
    public static final java.lang.String MEDIA_NOFS = "nofs";
    public static final java.lang.String MEDIA_REMOVED = "removed";
    public static final java.lang.String MEDIA_SHARED = "shared";
    public static final java.lang.String MEDIA_UNKNOWN = "unknown";
    public static final java.lang.String MEDIA_UNMOUNTABLE = "unmountable";
    public static final java.lang.String MEDIA_UNMOUNTED = "unmounted";
    public static java.lang.String[] STANDARD_DIRECTORIES;
    public static java.io.File buildPath(java.io.File p0, java.lang.String[] p1) { return null; }
    public static java.io.File[] buildPaths(java.io.File[] p0, java.lang.String[] p1) { return null; }
    public static int classifyExternalStorageDirectory(java.io.File p0) { return 0; }
    public static java.io.File getApexDirectory() { return null; }
    public static java.io.File getDataAppDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataCePackageDirectoryForUser(java.util.UUID p0, android.os.UserHandle p1, java.lang.String p2) { return null; }
    public static java.io.File getDataDePackageDirectoryForUser(java.util.UUID p0, android.os.UserHandle p1, java.lang.String p2) { return null; }
    public static java.io.File getDataDirectory(java.lang.String p0) { return null; }
    public static java.lang.String getDataDirectoryPath() { return null; }
    public static java.lang.String getDataDirectoryPath(java.lang.String p0) { return null; }
    public static java.io.File getDataMiscCeDirectory() { return null; }
    public static java.io.File getDataMiscCeDirectory(int p0) { return null; }
    public static java.io.File getDataMiscCeSharedSdkSandboxDirectory(java.lang.String p0, int p1, java.lang.String p2) { return null; }
    public static java.io.File getDataMiscDeDirectory(int p0) { return null; }
    public static java.io.File getDataMiscDeSharedSdkSandboxDirectory(java.lang.String p0, int p1, java.lang.String p2) { return null; }
    public static java.io.File getDataMiscDirectory() { return null; }
    public static java.io.File getDataPreloadsAppsDirectory() { return null; }
    public static java.io.File getDataPreloadsDemoDirectory() { return null; }
    public static java.io.File getDataPreloadsDirectory() { return null; }
    public static java.io.File getDataPreloadsFileCacheDirectory() { return null; }
    public static java.io.File getDataPreloadsFileCacheDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataPreloadsMediaDirectory() { return null; }
    public static java.io.File getDataProfilesDePackageDirectory(int p0, java.lang.String p1) { return null; }
    public static java.io.File getDataRefProfilesDePackageDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataStagingDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataSystemCeDirectory() { return null; }
    public static java.io.File getDataSystemCeDirectory(int p0) { return null; }
    public static java.io.File getDataSystemDeDirectory() { return null; }
    public static java.io.File getDataSystemDeDirectory(int p0) { return null; }
    public static java.io.File getDataSystemDeviceProtectedDirectory() { return null; }
    public static java.io.File getDataSystemDirectory() { return null; }
    public static java.io.File getDataUserCeDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataUserCeDirectory(java.lang.String p0, int p1) { return null; }
    public static java.io.File getDataUserCePackageDirectory(java.lang.String p0, int p1, java.lang.String p2) { return null; }
    public static java.io.File getDataUserDeDirectory(java.lang.String p0) { return null; }
    public static java.io.File getDataUserDeDirectory(java.lang.String p0, int p1) { return null; }
    public static java.io.File getDataUserDePackageDirectory(java.lang.String p0, int p1, java.lang.String p2) { return null; }
    public static java.io.File getDataVendorCeDirectory(int p0) { return null; }
    public static java.io.File getDataVendorDeDirectory(int p0) { return null; }
    public static java.io.File getExpandDirectory() { return null; }
    public static java.util.Collection getInternalMediaDirectories() { return new java.util.ArrayList(); }
    public static java.io.File getLegacyExternalStorageDirectory() { return null; }
    public static java.io.File getLegacyExternalStorageObbDirectory() { return null; }
    public static java.io.File getMetadataDirectory() { return null; }
    public static java.io.File getOdmDirectory() { return null; }
    public static java.io.File getOemDirectory() { return null; }
    public static java.io.File getPackageCacheDirectory() { return null; }
    public static java.io.File getProductDirectory() { return null; }
    public static java.io.File getProductServicesDirectory() { return null; }
    public static java.io.File getStorageDirectory() { return null; }
    public static java.lang.String getStorageState(java.io.File p0) { return null; }
    public static java.io.File getSystemExtDirectory() { return null; }
    public static java.io.File getUserConfigDirectory(int p0) { return null; }
    public static java.io.File getUserSystemDirectory(int p0) { return null; }
    public static java.io.File getVendorDirectory() { return null; }
    public static void initForCurrentUser() {}
    public static boolean isExternalStorageEmulated(java.io.File p0) { return false; }
    public static boolean isExternalStorageLegacy() { return false; }
    public static boolean isExternalStorageLegacy(java.io.File p0) { return false; }
    public static boolean isExternalStorageManager(java.io.File p0) { return false; }
    public static boolean isExternalStorageRemovable(java.io.File p0) { return false; }
    public static boolean isStandardDirectory(java.lang.String p0) { return false; }
    public static java.io.File maybeTranslateEmulatedPathToInternal(java.io.File p0) { return null; }
    public static void setUserRequired(boolean p0) {}
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static class UserEnvironment {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public UserEnvironment(int p0) {}
        public java.io.File[] buildExternalStorageAndroidDataDirs() { return null; }
        public java.io.File[] buildExternalStorageAndroidObbDirs() { return null; }
        public java.io.File[] buildExternalStorageAppCacheDirs(java.lang.String p0) { return null; }
        public java.io.File[] buildExternalStorageAppDataDirs(java.lang.String p0) { return null; }
        public java.io.File[] buildExternalStorageAppFilesDirs(java.lang.String p0) { return null; }
        public java.io.File[] buildExternalStorageAppMediaDirs(java.lang.String p0) { return null; }
        public java.io.File[] buildExternalStorageAppObbDirs(java.lang.String p0) { return null; }
        public java.io.File[] buildExternalStoragePublicDirs(java.lang.String p0) { return null; }
        public java.io.File[] getExternalDirs() { return (java.io.File[]) huskProps.get("ExternalDirs"); }
        public java.io.File getExternalStorageDirectory() { return (java.io.File) huskProps.get("ExternalStorageDirectory"); }
        public java.io.File getExternalStoragePublicDirectory(java.lang.String p0) { return null; }
        UserEnvironment() { this((int) 0); }
    }
    // ---- end of generated nested classes
}
