package android.os;

public class HandlerThread extends Thread {
    private Looper mLooper;
    public HandlerThread(String name) { super(name); }
    public HandlerThread(String name, int priority) { super(name); }
    protected void onLooperPrepared() {}
    @Override public void run() {
        Looper.prepare();
        synchronized (this) { mLooper = Looper.myLooper(); notifyAll(); }
        onLooperPrepared();
        Looper.loop();
    }
    public Looper getLooper() {
        synchronized (this) { while (mLooper == null) { try { wait(); } catch (InterruptedException e) { } } }
        return mLooper;
    }
    public boolean quit() { Looper l = getLooper(); if (l != null) l.quit(); return l != null; }
    public boolean quitSafely() { return quit(); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public java.util.concurrent.Executor getThreadExecutor() { return null; }
    public android.os.Handler getThreadHandler() { return null; }
    public int getThreadId() { return 0; }
    protected void onCreated() {}
    // ---- end of generated members
}
