package android.os;
public final class PersistableBundle extends BaseBundle implements Parcelable, Cloneable {
    public static final PersistableBundle EMPTY = new PersistableBundle();
    public PersistableBundle() {}
    public PersistableBundle(int capacity) {}
    public PersistableBundle(PersistableBundle b) { super(b); }
    public void putPersistableBundle(String k, PersistableBundle v) { map.put(k, v); }
    public PersistableBundle getPersistableBundle(String k) { Object v = map.get(k); return v instanceof PersistableBundle ? (PersistableBundle) v : null; }
    public int describeContents() { return 0; }
    public PersistableBundle deepCopy() { return new PersistableBundle(this); }
    @Override public Object clone() { return new PersistableBundle(this); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static android.os.Parcelable.Creator CREATOR;
    public PersistableBundle(android.os.Bundle p0) { this(); }
    public static android.os.PersistableBundle forPair(java.lang.String p0, java.lang.String p1) { return null; }
    public static boolean isValidType(java.lang.Object p0) { return false; }
    public static android.os.PersistableBundle readFromStream(java.io.InputStream p0) { return null; }
    public static android.os.PersistableBundle restoreFromXml(org.xmlpull.v1.XmlPullParser p0) { return null; }
    public void dumpDebug(android.util.proto.ProtoOutputStream p0, long p1) {}
    public boolean isBundleContentsWithinLengthLimit(int p0) { return false; }
    public void saveToXml(org.xmlpull.v1.XmlSerializer p0) {}
    public java.lang.String toShortString() { return null; }
    public void writeToStream(java.io.OutputStream p0) {}
    // ---- end of generated members
}
