package android.os;
public final class UserHandle implements Parcelable {
    private final int mHandle;
    public UserHandle(int h) { mHandle = h; }
    public static UserHandle getUserHandleForUid(int uid) { return new UserHandle(uid / 100000); }
    public static UserHandle of(int id) { return new UserHandle(id); }
    public static int myUserId() { return 0; }
    public int getIdentifier() { return mHandle; }
    public static int getUserId(int uid) { return uid / 100000; }
    public static boolean isApp(int uid) { return uid >= 10000; }
    public int describeContents() { return 0; }
    @Override public boolean equals(Object o) { return o instanceof UserHandle && ((UserHandle) o).mHandle == mHandle; }
    @Override public int hashCode() { return mHandle; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final int AID_APP_END = 19999;
    public static final int AID_APP_START = 10000;
    public static final int AID_CACHE_GID_START = 20000;
    public static final int AID_ROOT = 0;
    public static final int AID_SHARED_GID_START = 50000;
    public static android.os.UserHandle ALL;
    public static android.os.Parcelable.Creator CREATOR;
    public static android.os.UserHandle CURRENT;
    public static android.os.UserHandle CURRENT_OR_SELF;
    public static final int ERR_GID = -1;
    public static final int MAX_EXTRA_USER_HANDLE_CACHE_SIZE = 32;
    public static final int MAX_SECONDARY_USER_ID = 21473;
    public static final int MIN_SECONDARY_USER_ID = 10;
    public static final boolean MU_ENABLED = true;
    public static android.os.UserHandle OWNER;
    public static final int PER_USER_RANGE = 100000;
    public static android.os.UserHandle SYSTEM;
    public static final int USER_ALL = -1;
    public static final int USER_CURRENT = -2;
    public static final int USER_CURRENT_OR_SELF = -3;
    public static final int USER_NULL = -10000;
    public static int USER_OWNER;
    public static int USER_SERIAL_SYSTEM;
    public static int USER_SYSTEM;
    public static android.util.SparseArray sExtraUserHandleCache;
    public static java.lang.String formatUid(int p0) { return null; }
    public static void formatUid(java.io.PrintWriter p0, int p1) {}
    public static void formatUid(java.lang.StringBuilder p0, int p1) {}
    public static int[] fromUserHandles(java.util.List p0) { return null; }
    public static int getAppId(int p0) { return 0; }
    public static int getAppIdFromSharedAppGid(int p0) { return 0; }
    public static int getCacheAppGid(int p0) { return 0; }
    public static int getCacheAppGid(int p0, int p1) { return 0; }
    public static int getCallingAppId() { return 0; }
    public static int getCallingUserId() { return 0; }
    public static int getSharedAppGid(int p0) { return 0; }
    public static int getSharedAppGid(int p0, int p1) { return 0; }
    public static int getUid(int p0, int p1) { return 0; }
    public static int getUserGid(int p0) { return 0; }
    public static android.os.UserHandle getUserHandleFromExtraCache(int p0) { return null; }
    public static boolean isCore(int p0) { return false; }
    public static boolean isIsolated(int p0) { return false; }
    public static boolean isSameApp(int p0, int p1) { return false; }
    public static boolean isSameUser(int p0, int p1) { return false; }
    public static boolean isSharedAppGid(int p0) { return false; }
    public static int parseUserArg(java.lang.String p0) { return 0; }
    public static android.os.UserHandle readFromParcel(android.os.Parcel p0) { return null; }
    public static java.util.List toUserHandles(int[] p0) { return new java.util.ArrayList(); }
    public static void writeToParcel(android.os.UserHandle p0, android.os.Parcel p1) {}
    public int getUid(int p0) { return 0; }
    public boolean isOwner() { return false; }
    public boolean isSystem() { return false; }
    // ---- end of generated members
}
