package android.os;
public class VibratorManager {
    private final Vibrator mV = new Vibrator();
    public int[] getVibratorIds() { return new int[] { 0 }; }
    public Vibrator getVibrator(int id) { return mV; }
    public Vibrator getDefaultVibrator() { return mV; }
    public void vibrate(CombinedVibration v) { mV.vibrate(40); }
    public void cancel() {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public VibratorManager() {}
    protected java.lang.String mPackageName;
    protected VibratorManager(android.content.Context p0) { this(); }
    public void cancel(int p0) {}
    public boolean hasCapabilities(int p0) { return false; }
    public void performHapticFeedback(int p0, int p1, java.lang.String p2, int p3, int p4) {}
    public void performHapticFeedbackForInputDevice(int p0, int p1, int p2, java.lang.String p3, int p4, int p5) {}
    public boolean setAlwaysOnEffect(int p0, java.lang.String p1, int p2, android.os.CombinedVibration p3, android.os.VibrationAttributes p4) { return false; }
    public void vibrate(int p0, java.lang.String p1, android.os.CombinedVibration p2, java.lang.String p3, android.os.VibrationAttributes p4) {}
    public void vibrate(android.os.CombinedVibration p0, android.os.VibrationAttributes p1) {}
    // ---- end of generated members
}
