// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.appsearch;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AppSearchSchema extends android.app.appsearch.safeparcel.AbstractSafeParcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public java.lang.String getDescription() { return (java.lang.String) huskProps.get("Description"); }
    public java.util.List getParentTypes() { return (huskProps.get("ParentTypes") != null ? (java.util.List) huskProps.get("ParentTypes") : new java.util.ArrayList()); }
    public java.util.List getProperties() { return (huskProps.get("Properties") != null ? (java.util.List) huskProps.get("Properties") : new java.util.ArrayList()); }
    public java.lang.String getSchemaType() { return (java.lang.String) huskProps.get("SchemaType"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected AppSearchSchema() { super(); }
    public static final class BlobHandlePropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected BlobHandlePropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.BlobHandlePropertyConfig build() { return new android.app.appsearch.AppSearchSchema.BlobHandlePropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.BlobHandlePropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.BlobHandlePropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static final class BooleanPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public boolean isScoringEnabled() { return (huskProps.get("ScoringEnabled") instanceof Boolean ? (Boolean) huskProps.get("ScoringEnabled") : false); }
        protected BooleanPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.BooleanPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.BooleanPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.BooleanPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.BooleanPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.BooleanPropertyConfig.Builder setScoringEnabled(boolean p0) { huskProps.put("ScoringEnabled", Boolean.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.app.appsearch.AppSearchSchema p0) {}
        public Builder(java.lang.String p0) {}
        public android.app.appsearch.AppSearchSchema.Builder addParentType(java.lang.String p0) { return this; }
        public android.app.appsearch.AppSearchSchema.Builder addProperty(android.app.appsearch.AppSearchSchema.PropertyConfig p0) { return this; }
        public android.app.appsearch.AppSearchSchema build() { return null; }
        public android.app.appsearch.AppSearchSchema.Builder clearParentTypes() { return this; }
        public android.app.appsearch.AppSearchSchema.Builder clearProperties() { return this; }
        public android.app.appsearch.AppSearchSchema.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
        public android.app.appsearch.AppSearchSchema.Builder setSchemaType(java.lang.String p0) { huskProps.put("SchemaType", p0); return this; }
        Builder() { this((android.app.appsearch.AppSearchSchema) null); }
    }
    public static final class BytesPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected BytesPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.BytesPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.BytesPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.BytesPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.BytesPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static final class DocumentPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.util.List getIndexableNestedProperties() { return (huskProps.get("IndexableNestedProperties") != null ? (java.util.List) huskProps.get("IndexableNestedProperties") : new java.util.ArrayList()); }
        public java.lang.String getSchemaType() { return (java.lang.String) huskProps.get("SchemaType"); }
        public boolean shouldIndexNestedProperties() { return false; }
        protected DocumentPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0, java.lang.String p1) {}
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder addIndexableNestedProperties(java.util.Collection p0) { return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder addIndexableNestedProperties(java.lang.String[] p0) { return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder addIndexableNestedPropertyPaths(java.util.Collection p0) { return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder addIndexableNestedPropertyPaths(android.app.appsearch.PropertyPath[] p0) { return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.DocumentPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.DocumentPropertyConfig.Builder setShouldIndexNestedProperties(boolean p0) { huskProps.put("ShouldIndexNestedProperties", Boolean.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null, (java.lang.String) null); }
        }
    }
    public static final class DoublePropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public boolean isScoringEnabled() { return (huskProps.get("ScoringEnabled") instanceof Boolean ? (Boolean) huskProps.get("ScoringEnabled") : false); }
        protected DoublePropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.DoublePropertyConfig build() { return new android.app.appsearch.AppSearchSchema.DoublePropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.DoublePropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.DoublePropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.DoublePropertyConfig.Builder setScoringEnabled(boolean p0) { huskProps.put("ScoringEnabled", Boolean.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static final class EmbeddingPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int INDEXING_TYPE_NONE = 0;
        public static final int INDEXING_TYPE_SIMILARITY = 1;
        public static final int QUANTIZATION_TYPE_8_BIT = 1;
        public static int QUANTIZATION_TYPE_NONE;
        public int getIndexingType() { return (huskProps.get("IndexingType") instanceof Integer ? (Integer) huskProps.get("IndexingType") : 0); }
        public int getQuantizationType() { return (huskProps.get("QuantizationType") instanceof Integer ? (Integer) huskProps.get("QuantizationType") : 0); }
        protected EmbeddingPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig.Builder setIndexingType(int p0) { huskProps.put("IndexingType", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.EmbeddingPropertyConfig.Builder setQuantizationType(int p0) { huskProps.put("QuantizationType", Integer.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static final class LongPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int INDEXING_TYPE_NONE = 0;
        public static final int INDEXING_TYPE_RANGE = 1;
        public int getIndexingType() { return (huskProps.get("IndexingType") instanceof Integer ? (Integer) huskProps.get("IndexingType") : 0); }
        public boolean isScoringEnabled() { return (huskProps.get("ScoringEnabled") instanceof Boolean ? (Boolean) huskProps.get("ScoringEnabled") : false); }
        protected LongPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.LongPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.LongPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.LongPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.LongPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.LongPropertyConfig.Builder setIndexingType(int p0) { huskProps.put("IndexingType", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.LongPropertyConfig.Builder setScoringEnabled(boolean p0) { huskProps.put("ScoringEnabled", Boolean.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
    public static abstract class PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int CARDINALITY_OPTIONAL = 2;
        public static final int CARDINALITY_REPEATED = 1;
        public static final int CARDINALITY_REQUIRED = 3;
        public static final int DATA_TYPE_BLOB_HANDLE = 8;
        public static final int DATA_TYPE_BOOLEAN = 4;
        public static final int DATA_TYPE_BYTES = 5;
        public static final int DATA_TYPE_DOCUMENT = 6;
        public static final int DATA_TYPE_DOUBLE = 3;
        public static final int DATA_TYPE_EMBEDDING = 7;
        public static final int DATA_TYPE_LONG = 2;
        public static final int DATA_TYPE_STRING = 1;
        public static android.app.appsearch.AppSearchSchema.PropertyConfig fromParcel(android.app.appsearch.safeparcel.PropertyConfigParcel p0) { return null; }
        public int getCardinality() { return (huskProps.get("Cardinality") instanceof Integer ? (Integer) huskProps.get("Cardinality") : 0); }
        public int getDataType() { return (huskProps.get("DataType") instanceof Integer ? (Integer) huskProps.get("DataType") : 0); }
        public java.lang.String getDescription() { return (java.lang.String) huskProps.get("Description"); }
        public java.lang.String getName() { return (java.lang.String) huskProps.get("Name"); }
        protected PropertyConfig() {}
    }
    public static final class StringPropertyConfig extends android.app.appsearch.AppSearchSchema.PropertyConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int DELETE_PROPAGATION_TYPE_NONE = 0;
        public static final int DELETE_PROPAGATION_TYPE_PROPAGATE_FROM = 1;
        public static final int INDEXING_TYPE_EXACT_TERMS = 1;
        public static final int INDEXING_TYPE_NONE = 0;
        public static final int INDEXING_TYPE_PREFIXES = 2;
        public static final int JOINABLE_VALUE_TYPE_NONE = 0;
        public static final int JOINABLE_VALUE_TYPE_QUALIFIED_ID = 1;
        public static final int TOKENIZER_TYPE_NONE = 0;
        public static final int TOKENIZER_TYPE_PLAIN = 1;
        public static final int TOKENIZER_TYPE_RFC822 = 3;
        public static final int TOKENIZER_TYPE_VERBATIM = 2;
        public int getDeletePropagationType() { return (huskProps.get("DeletePropagationType") instanceof Integer ? (Integer) huskProps.get("DeletePropagationType") : 0); }
        public int getIndexingType() { return (huskProps.get("IndexingType") instanceof Integer ? (Integer) huskProps.get("IndexingType") : 0); }
        public int getJoinableValueType() { return (huskProps.get("JoinableValueType") instanceof Integer ? (Integer) huskProps.get("JoinableValueType") : 0); }
        public int getTokenizerType() { return (huskProps.get("TokenizerType") instanceof Integer ? (Integer) huskProps.get("TokenizerType") : 0); }
        protected StringPropertyConfig() { super(); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(java.lang.String p0) {}
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig build() { return new android.app.appsearch.AppSearchSchema.StringPropertyConfig(); }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setCardinality(int p0) { huskProps.put("Cardinality", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setDeletePropagationType(int p0) { huskProps.put("DeletePropagationType", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setDescription(java.lang.String p0) { huskProps.put("Description", p0); return this; }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setIndexingType(int p0) { huskProps.put("IndexingType", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setJoinableValueType(int p0) { huskProps.put("JoinableValueType", Integer.valueOf(p0)); return this; }
            public android.app.appsearch.AppSearchSchema.StringPropertyConfig.Builder setTokenizerType(int p0) { huskProps.put("TokenizerType", Integer.valueOf(p0)); return this; }
            Builder() { this((java.lang.String) null); }
        }
    }
}
