// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class AuthenticationRequiredException extends java.lang.SecurityException implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public AuthenticationRequiredException(android.os.Parcel p0) { super(); }
    public AuthenticationRequiredException(java.lang.Throwable p0, android.app.PendingIntent p1) { super(); }
    public int describeContents() { return 0; }
    public android.app.PendingIntent getUserAction() { return (android.app.PendingIntent) huskProps.get("UserAction"); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
