// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class FragmentController {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.app.FragmentController createController(android.app.FragmentHostCallback p0) { return new FragmentController(); }
    public void attachHost(android.app.Fragment p0) {}
    public void dispatchActivityCreated() {}
    public void dispatchConfigurationChanged(android.content.res.Configuration p0) {}
    public boolean dispatchContextItemSelected(android.view.MenuItem p0) { return false; }
    public void dispatchCreate() {}
    public boolean dispatchCreateOptionsMenu(android.view.Menu p0, android.view.MenuInflater p1) { return false; }
    public void dispatchDestroy() {}
    public void dispatchDestroyView() {}
    public void dispatchLowMemory() {}
    public void dispatchMultiWindowModeChanged(boolean p0) {}
    public void dispatchMultiWindowModeChanged(boolean p0, android.content.res.Configuration p1) {}
    public boolean dispatchOptionsItemSelected(android.view.MenuItem p0) { return false; }
    public void dispatchOptionsMenuClosed(android.view.Menu p0) {}
    public void dispatchPause() {}
    public void dispatchPictureInPictureModeChanged(boolean p0) {}
    public void dispatchPictureInPictureModeChanged(boolean p0, android.content.res.Configuration p1) {}
    public boolean dispatchPrepareOptionsMenu(android.view.Menu p0) { return false; }
    public void dispatchResume() {}
    public void dispatchStart() {}
    public void dispatchStop() {}
    public void dispatchTrimMemory(int p0) {}
    public void doLoaderDestroy() {}
    public void doLoaderStart() {}
    public void doLoaderStop(boolean p0) {}
    public void dumpLoaders(java.lang.String p0, java.io.FileDescriptor p1, java.io.PrintWriter p2, java.lang.String[] p3) {}
    public boolean execPendingActions() { return false; }
    public android.app.Fragment findFragmentByWho(java.lang.String p0) { return null; }
    public android.app.FragmentManager getFragmentManager() { return (android.app.FragmentManager) huskProps.get("FragmentManager"); }
    public android.app.LoaderManager getLoaderManager() { return (android.app.LoaderManager) huskProps.get("LoaderManager"); }
    public void noteStateNotSaved() {}
    public android.view.View onCreateView(android.view.View p0, java.lang.String p1, android.content.Context p2, android.util.AttributeSet p3) { return null; }
    public void reportLoaderStart() {}
    public void restoreAllState(android.os.Parcelable p0, android.app.FragmentManagerNonConfig p1) {}
    public void restoreAllState(android.os.Parcelable p0, java.util.List p1) {}
    public void restoreLoaderNonConfig(android.util.ArrayMap p0) {}
    public android.util.ArrayMap retainLoaderNonConfig() { return null; }
    public android.app.FragmentManagerNonConfig retainNestedNonConfig() { return null; }
    public java.util.List retainNonConfig() { return new java.util.ArrayList(); }
    public android.os.Parcelable saveAllState() { return null; }
    protected FragmentController() {}
}
