// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class UiAutomation {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static java.util.Set ALL_PERMISSIONS;
    public static final int FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES = 1;
    public static final int FLAG_DONT_USE_ACCESSIBILITY = 2;
    public static final int FLAG_NOT_ACCESSIBILITY_TOOL = 4;
    public static final int ROTATION_FREEZE_0 = 0;
    public static final int ROTATION_FREEZE_180 = 2;
    public static final int ROTATION_FREEZE_270 = 3;
    public static final int ROTATION_FREEZE_90 = 1;
    public static final int ROTATION_FREEZE_CURRENT = -1;
    public static final int ROTATION_UNFREEZE = -2;
    public UiAutomation(android.content.Context p0, android.app.IUiAutomationConnection p1) {}
    public UiAutomation(android.os.Looper p0, android.app.IUiAutomationConnection p1) {}
    public void addOverridePermissionState(int p0, java.lang.String p1, int p2) {}
    public void adoptShellPermissionIdentity() {}
    public void adoptShellPermissionIdentity(java.lang.String[] p0) {}
    public void clearAllOverridePermissionStates() {}
    public boolean clearCache() { return false; }
    public void clearOverridePermissionStates(int p0) {}
    public void clearWindowAnimationFrameStats() {}
    public boolean clearWindowContentFrameStats(int p0) { return false; }
    public void connect() {}
    public void connect(int p0) {}
    public void connectWithTimeout(int p0, long p1) {}
    public void destroy() {}
    public void disconnect() {}
    public void dropShellPermissionIdentity() {}
    public android.view.accessibility.AccessibilityEvent executeAndWaitForEvent(java.lang.Runnable p0, android.app.UiAutomation.AccessibilityEventFilter p1, long p2) { return null; }
    public android.os.ParcelFileDescriptor executeShellCommand(java.lang.String p0) { return null; }
    public android.os.ParcelFileDescriptor[] executeShellCommandRw(java.lang.String p0) { return null; }
    public android.os.ParcelFileDescriptor[] executeShellCommandRwe(java.lang.String p0) { return null; }
    public android.view.accessibility.AccessibilityNodeInfo findFocus(int p0) { return null; }
    public java.util.Set getAdoptedShellPermissions() { return (huskProps.get("AdoptedShellPermissions") != null ? (java.util.Set) huskProps.get("AdoptedShellPermissions") : new java.util.HashSet()); }
    public android.view.accessibility.AccessibilityCache getCache() { return (android.view.accessibility.AccessibilityCache) huskProps.get("Cache"); }
    public int getConnectionId() { return (huskProps.get("ConnectionId") instanceof Integer ? (Integer) huskProps.get("ConnectionId") : 0); }
    public int getDisplayId() { return (huskProps.get("DisplayId") instanceof Integer ? (Integer) huskProps.get("DisplayId") : 0); }
    public int getFlags() { return (huskProps.get("Flags") instanceof Integer ? (Integer) huskProps.get("Flags") : 0); }
    public android.view.accessibility.AccessibilityNodeInfo getRootInActiveWindow() { return (android.view.accessibility.AccessibilityNodeInfo) huskProps.get("RootInActiveWindow"); }
    public android.view.accessibility.AccessibilityNodeInfo getRootInActiveWindow(int p0) { return null; }
    public android.accessibilityservice.AccessibilityServiceInfo getServiceInfo() { return (android.accessibilityservice.AccessibilityServiceInfo) huskProps.get("ServiceInfo"); }
    public android.view.WindowAnimationFrameStats getWindowAnimationFrameStats() { return (android.view.WindowAnimationFrameStats) huskProps.get("WindowAnimationFrameStats"); }
    public android.view.WindowContentFrameStats getWindowContentFrameStats(int p0) { return null; }
    public java.util.List getWindows() { return (huskProps.get("Windows") != null ? (java.util.List) huskProps.get("Windows") : new java.util.ArrayList()); }
    public android.util.SparseArray getWindowsOnAllDisplays() { return (android.util.SparseArray) huskProps.get("WindowsOnAllDisplays"); }
    public void grantRuntimePermission(java.lang.String p0, java.lang.String p1) {}
    public boolean grantRuntimePermission(java.lang.String p0, java.lang.String p1, android.os.UserHandle p2) { return false; }
    public void grantRuntimePermissionAsUser(java.lang.String p0, java.lang.String p1, android.os.UserHandle p2) {}
    public boolean injectInputEvent(android.view.InputEvent p0, boolean p1) { return false; }
    public boolean injectInputEvent(android.view.InputEvent p0, boolean p1, boolean p2) { return false; }
    public void injectInputEventToInputFilter(android.view.InputEvent p0) {}
    public boolean isDestroyed() { return (huskProps.get("Destroyed") instanceof Boolean ? (Boolean) huskProps.get("Destroyed") : false); }
    public boolean isNodeInCache(android.view.accessibility.AccessibilityNodeInfo p0) { return false; }
    public boolean performGlobalAction(int p0) { return false; }
    public void removeOverridePermissionState(int p0, java.lang.String p1) {}
    public void revokeRuntimePermission(java.lang.String p0, java.lang.String p1) {}
    public boolean revokeRuntimePermission(java.lang.String p0, java.lang.String p1, android.os.UserHandle p2) { return false; }
    public void revokeRuntimePermissionAsUser(java.lang.String p0, java.lang.String p1, android.os.UserHandle p2) {}
    public void setAnimationScale(float p0) { huskProps.put("AnimationScale", Float.valueOf(p0)); }
    public void setOnAccessibilityEventListener(android.app.UiAutomation.OnAccessibilityEventListener p0) { huskProps.put("OnAccessibilityEventListener", p0); }
    public boolean setRotation(int p0) { return false; }
    public void setRunAsMonkey(boolean p0) { huskProps.put("RunAsMonkey", Boolean.valueOf(p0)); }
    public void setServiceInfo(android.accessibilityservice.AccessibilityServiceInfo p0) { huskProps.put("ServiceInfo", p0); }
    public void syncInputTransactions() {}
    public void syncInputTransactions(boolean p0) {}
    public android.graphics.Bitmap takeScreenshot() { return null; }
    public android.graphics.Bitmap takeScreenshot(int p0) { return null; }
    public android.graphics.Bitmap takeScreenshot(android.view.Window p0) { return null; }
    public void waitForIdle(long p0, long p1) {}
    public interface AccessibilityEventFilter {
        boolean accept(android.view.accessibility.AccessibilityEvent p0);
    }
    public interface OnAccessibilityEventListener {
        void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0);
    }
}
