// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class MediaCasException extends java.lang.Exception {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    protected MediaCasException() { super(); }
    public static final class DeniedByServerException extends android.media.MediaCasException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public DeniedByServerException(java.lang.String p0) { super(); }
    }
    public static final class InsufficientResourceException extends android.media.MediaCasException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public InsufficientResourceException(java.lang.String p0) { super(); }
    }
    public static final class NotProvisionedException extends android.media.MediaCasException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public NotProvisionedException(java.lang.String p0) { super(); }
    }
    public static final class ResourceBusyException extends android.media.MediaCasException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ResourceBusyException(java.lang.String p0) { super(); }
    }
    public static final class UnsupportedCasException extends android.media.MediaCasException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public UnsupportedCasException(java.lang.String p0) { super(); }
    }
}
