// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.companion;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ActionRequest implements android.os.Parcelable {
    protected ActionRequest() {}
}
