// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.companion;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface ICompanionDeviceManager extends android.os.IInterface {
}
