// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi.p2p.nsd;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class WifiP2pDnsSdServiceInfo extends android.net.wifi.p2p.nsd.WifiP2pServiceInfo {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int DNS_TYPE_PTR = 12;
    public static final int DNS_TYPE_TXT = 16;
    public static final int VERSION_1 = 1;
    public static android.net.wifi.p2p.nsd.WifiP2pDnsSdServiceInfo newInstance(java.lang.String p0, java.lang.String p1, java.util.Map p2) { return new WifiP2pDnsSdServiceInfo(); }
    protected WifiP2pDnsSdServiceInfo() { super((android.net.wifi.p2p.nsd.WifiP2pUsdBasedServiceConfig) null); }
}
