// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.os.strictmode;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class Violation extends java.lang.Throwable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public java.lang.Throwable fillInStackTrace() { return null; }
    public java.lang.Throwable initCause(java.lang.Throwable p0) { return null; }
    public void setStackTrace(java.lang.StackTraceElement[] p0) { huskProps.put("StackTrace", p0); }
    protected Violation() { super(); }
}
