// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.ipsec.ike;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class IkeSessionParams {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int AUTH_DIRECTION_BOTH = 3;
    public static final int AUTH_DIRECTION_LOCAL = 1;
    public static final int AUTH_DIRECTION_REMOTE = 2;
    public static android.util.SparseArray ENCAP_TYPE_TO_STR;
    public static final int ESP_ENCAP_TYPE_AUTO = 0;
    public static final int ESP_ENCAP_TYPE_NONE = -1;
    public static final int ESP_ENCAP_TYPE_UDP = 17;
    public static final int ESP_IP_VERSION_AUTO = 0;
    public static final int ESP_IP_VERSION_IPV4 = 4;
    public static final int ESP_IP_VERSION_IPV6 = 6;
    public static final int IKE_AUTH_METHOD_EAP = 3;
    public static final int IKE_AUTH_METHOD_PSK = 1;
    public static final int IKE_AUTH_METHOD_PUB_KEY_SIGNATURE = 2;
    public static final int IKE_DPD_DELAY_SEC_DISABLED = 2147483647;
    public static final int IKE_NATT_KEEPALIVE_DELAY_SEC_MAX = 3600;
    public static final int IKE_NATT_KEEPALIVE_DELAY_SEC_MIN = 10;
    public static final int IKE_OPTION_ACCEPT_ANY_REMOTE_ID = 0;
    public static final int IKE_OPTION_AUTOMATIC_ADDRESS_FAMILY_SELECTION = 6;
    public static final int IKE_OPTION_AUTOMATIC_KEEPALIVE_ON_OFF = 8;
    public static final int IKE_OPTION_AUTOMATIC_NATT_KEEPALIVES = 7;
    public static final int IKE_OPTION_EAP_ONLY_AUTH = 1;
    public static final int IKE_OPTION_FORCE_DNS_RESOLUTION = 9;
    public static final int IKE_OPTION_FORCE_PORT_4500 = 3;
    public static final int IKE_OPTION_INITIAL_CONTACT = 4;
    public static final int IKE_OPTION_MOBIKE = 2;
    public static final int IKE_OPTION_REKEY_MOBILITY = 5;
    public static android.util.SparseArray IP_VERSION_TO_STR;
    public static final int NATT_KEEPALIVE_INTERVAL_AUTO = -1;
    public static android.net.ipsec.ike.IkeSessionParams fromPersistableBundle(android.os.PersistableBundle p0) { return new IkeSessionParams(); }
    public void dump(java.io.PrintWriter p0, java.lang.String p1) {}
    public java.util.List getConfigurationRequests() { return (huskProps.get("ConfigurationRequests") != null ? (java.util.List) huskProps.get("ConfigurationRequests") : new java.util.ArrayList()); }
    public android.net.Network getConfiguredNetwork() { return (android.net.Network) huskProps.get("ConfiguredNetwork"); }
    public int getDpdDelaySeconds() { return (huskProps.get("DpdDelaySeconds") instanceof Integer ? (Integer) huskProps.get("DpdDelaySeconds") : 0); }
    public int getDscp() { return (huskProps.get("Dscp") instanceof Integer ? (Integer) huskProps.get("Dscp") : 0); }
    public int getEncapType() { return (huskProps.get("EncapType") instanceof Integer ? (Integer) huskProps.get("EncapType") : 0); }
    public long getHardLifetimeMsInternal() { return (huskProps.get("HardLifetimeMsInternal") instanceof Long ? (Long) huskProps.get("HardLifetimeMsInternal") : 0L); }
    public int getHardLifetimeSeconds() { return (huskProps.get("HardLifetimeSeconds") instanceof Integer ? (Integer) huskProps.get("HardLifetimeSeconds") : 0); }
    public android.net.ipsec.ike.ike3gpp.Ike3gppExtension getIke3gppExtension() { return (android.net.ipsec.ike.ike3gpp.Ike3gppExtension) huskProps.get("Ike3gppExtension"); }
    public java.util.Set getIkeOptions() { return (huskProps.get("IkeOptions") != null ? (java.util.Set) huskProps.get("IkeOptions") : new java.util.HashSet()); }
    public java.util.List getIkeSaProposals() { return (huskProps.get("IkeSaProposals") != null ? (java.util.List) huskProps.get("IkeSaProposals") : new java.util.ArrayList()); }
    public int getIpVersion() { return (huskProps.get("IpVersion") instanceof Integer ? (Integer) huskProps.get("IpVersion") : 0); }
    public int[] getLivenessRetransmissionTimeoutsMillis() { return (int[]) huskProps.get("LivenessRetransmissionTimeoutsMillis"); }
    public android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig getLocalAuthConfig() { return (android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig) huskProps.get("LocalAuthConfig"); }
    public android.net.ipsec.ike.IkeIdentification getLocalIdentification() { return (android.net.ipsec.ike.IkeIdentification) huskProps.get("LocalIdentification"); }
    public int getNattKeepAliveDelaySeconds() { return (huskProps.get("NattKeepAliveDelaySeconds") instanceof Integer ? (Integer) huskProps.get("NattKeepAliveDelaySeconds") : 0); }
    public android.net.Network getNetwork() { return (android.net.Network) huskProps.get("Network"); }
    public android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig getRemoteAuthConfig() { return (android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig) huskProps.get("RemoteAuthConfig"); }
    public android.net.ipsec.ike.IkeIdentification getRemoteIdentification() { return (android.net.ipsec.ike.IkeIdentification) huskProps.get("RemoteIdentification"); }
    public int[] getRetransmissionTimeoutsMillis() { return (int[]) huskProps.get("RetransmissionTimeoutsMillis"); }
    public java.util.List getSaProposals() { return (huskProps.get("SaProposals") != null ? (java.util.List) huskProps.get("SaProposals") : new java.util.ArrayList()); }
    public android.net.ipsec.ike.IkeSaProposal[] getSaProposalsInternal() { return (android.net.ipsec.ike.IkeSaProposal[]) huskProps.get("SaProposalsInternal"); }
    public java.lang.String getServerHostname() { return (java.lang.String) huskProps.get("ServerHostname"); }
    public long getSoftLifetimeMsInternal() { return (huskProps.get("SoftLifetimeMsInternal") instanceof Long ? (Long) huskProps.get("SoftLifetimeMsInternal") : 0L); }
    public int getSoftLifetimeSeconds() { return (huskProps.get("SoftLifetimeSeconds") instanceof Integer ? (Integer) huskProps.get("SoftLifetimeSeconds") : 0); }
    public boolean hasIkeOption(int p0) { return false; }
    public boolean isIkeFragmentationSupported() { return (huskProps.get("IkeFragmentationSupported") instanceof Boolean ? (Boolean) huskProps.get("IkeFragmentationSupported") : false); }
    public android.os.PersistableBundle toPersistableBundle() { return null; }
    protected IkeSessionParams() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public Builder(android.content.Context p0) {}
        public Builder(android.net.ConnectivityManager p0) {}
        public Builder(android.net.ipsec.ike.IkeSessionParams p0) {}
        public android.net.ipsec.ike.IkeSessionParams.Builder addIkeOption(int p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder addIkeOptionInternal(int p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder addIkeSaProposal(android.net.ipsec.ike.IkeSaProposal p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder addPcscfServerRequest(int p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder addPcscfServerRequest(java.net.InetAddress p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder addSaProposal(android.net.ipsec.ike.IkeSaProposal p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams build() { return new android.net.ipsec.ike.IkeSessionParams(); }
        public android.net.ipsec.ike.IkeSessionParams.Builder removeIkeOption(int p0) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setAuthDigitalSignature(java.security.cert.X509Certificate p0, java.security.cert.X509Certificate p1, java.security.PrivateKey p2) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setAuthDigitalSignature(java.security.cert.X509Certificate p0, java.security.cert.X509Certificate p1, java.util.List p2, java.security.PrivateKey p3) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setAuthEap(java.security.cert.X509Certificate p0, android.net.eap.EapSessionConfig p1) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setAuthPsk(byte[] p0) { huskProps.put("AuthPsk", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setDpdDelaySeconds(int p0) { huskProps.put("DpdDelaySeconds", Integer.valueOf(p0)); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setDscp(int p0) { huskProps.put("Dscp", Integer.valueOf(p0)); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setEncapType(int p0) { huskProps.put("EncapType", Integer.valueOf(p0)); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setIke3gppExtension(android.net.ipsec.ike.ike3gpp.Ike3gppExtension p0) { huskProps.put("Ike3gppExtension", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setIpVersion(int p0) { huskProps.put("IpVersion", Integer.valueOf(p0)); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setLifetimeSeconds(int p0, int p1) { return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setLivenessRetransmissionTimeoutsMillis(int[] p0) { huskProps.put("LivenessRetransmissionTimeoutsMillis", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setLocalIdentification(android.net.ipsec.ike.IkeIdentification p0) { huskProps.put("LocalIdentification", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setNattKeepAliveDelaySeconds(int p0) { huskProps.put("NattKeepAliveDelaySeconds", Integer.valueOf(p0)); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setNetwork(android.net.Network p0) { huskProps.put("Network", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setRemoteIdentification(android.net.ipsec.ike.IkeIdentification p0) { huskProps.put("RemoteIdentification", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setRetransmissionTimeoutsMillis(int[] p0) { huskProps.put("RetransmissionTimeoutsMillis", p0); return this; }
        public android.net.ipsec.ike.IkeSessionParams.Builder setServerHostname(java.lang.String p0) { huskProps.put("ServerHostname", p0); return this; }
    }
    public interface ConfigRequestIpv4PcscfServer extends android.net.ipsec.ike.IkeSessionParams.IkeConfigRequest {
        java.net.Inet4Address getAddress();
    }
    public interface ConfigRequestIpv6PcscfServer extends android.net.ipsec.ike.IkeSessionParams.IkeConfigRequest {
        java.net.Inet6Address getAddress();
    }
    public static abstract class IkeAuthConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int mAuthDirection;
        public int mAuthMethod;
        public static android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig fromPersistableBundle(android.os.PersistableBundle p0) { return null; }
        protected android.os.PersistableBundle toPersistableBundle() { return null; }
        protected IkeAuthConfig() {}
    }
    public static class IkeAuthDigitalSignLocalConfig extends android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.security.cert.X509Certificate mEndCert;
        public java.util.List mIntermediateCerts;
        public java.security.PrivateKey mPrivateKey;
        public static android.net.ipsec.ike.IkeSessionParams.IkeAuthDigitalSignLocalConfig fromPersistableBundle(android.os.PersistableBundle p0) { return new IkeAuthDigitalSignLocalConfig(); }
        public java.security.cert.X509Certificate getClientEndCertificate() { return (java.security.cert.X509Certificate) huskProps.get("ClientEndCertificate"); }
        public java.util.List getIntermediateCertificates() { return (huskProps.get("IntermediateCertificates") != null ? (java.util.List) huskProps.get("IntermediateCertificates") : new java.util.ArrayList()); }
        public java.security.PrivateKey getPrivateKey() { return (java.security.PrivateKey) huskProps.get("PrivateKey"); }
        public android.os.PersistableBundle toPersistableBundle() { return null; }
        protected IkeAuthDigitalSignLocalConfig() { super(); }
    }
    public static class IkeAuthDigitalSignRemoteConfig extends android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.security.cert.TrustAnchor mTrustAnchor;
        public static android.net.ipsec.ike.IkeSessionParams.IkeAuthDigitalSignRemoteConfig fromPersistableBundle(android.os.PersistableBundle p0) { return new IkeAuthDigitalSignRemoteConfig(); }
        public java.security.cert.X509Certificate getRemoteCaCert() { return (java.security.cert.X509Certificate) huskProps.get("RemoteCaCert"); }
        public android.os.PersistableBundle toPersistableBundle() { return null; }
        protected IkeAuthDigitalSignRemoteConfig() { super(); }
    }
    public static class IkeAuthEapConfig extends android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public android.net.eap.EapSessionConfig mEapConfig;
        public static android.net.ipsec.ike.IkeSessionParams.IkeAuthEapConfig fromPersistableBundle(android.os.PersistableBundle p0) { return new IkeAuthEapConfig(); }
        public android.net.eap.EapSessionConfig getEapConfig() { return (android.net.eap.EapSessionConfig) huskProps.get("EapConfig"); }
        public android.os.PersistableBundle toPersistableBundle() { return null; }
        protected IkeAuthEapConfig() { super(); }
    }
    public static class IkeAuthPskConfig extends android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public byte[] mPsk;
        public static android.net.ipsec.ike.IkeSessionParams.IkeAuthPskConfig fromPersistableBundle(android.os.PersistableBundle p0) { return new IkeAuthPskConfig(); }
        public byte[] getPsk() { return (byte[]) huskProps.get("Psk"); }
        public android.os.PersistableBundle toPersistableBundle() { return null; }
        protected IkeAuthPskConfig() { super(); }
    }
    public interface IkeConfigRequest {
    }
}
