// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.ipsec.ike;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class IkeSessionConfiguration {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int EXTENSION_TYPE_FRAGMENTATION = 1;
    public static final int EXTENSION_TYPE_MOBIKE = 2;
    public android.net.eap.EapInfo getEapInfo() { return (android.net.eap.EapInfo) huskProps.get("EapInfo"); }
    public android.net.ipsec.ike.IkeSessionConnectionInfo getIkeSessionConnectionInfo() { return (android.net.ipsec.ike.IkeSessionConnectionInfo) huskProps.get("IkeSessionConnectionInfo"); }
    public java.util.List getPcscfServers() { return (huskProps.get("PcscfServers") != null ? (java.util.List) huskProps.get("PcscfServers") : new java.util.ArrayList()); }
    public java.lang.String getRemoteApplicationVersion() { return (java.lang.String) huskProps.get("RemoteApplicationVersion"); }
    public java.util.List getRemoteVendorIds() { return (huskProps.get("RemoteVendorIds") != null ? (java.util.List) huskProps.get("RemoteVendorIds") : new java.util.ArrayList()); }
    public boolean isIkeExtensionEnabled(int p0) { return false; }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.net.ipsec.ike.IkeSessionConnectionInfo p0) {}
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder addIkeExtension(int p0) { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder addPcscfServer(java.net.InetAddress p0) { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder addRemoteVendorId(byte[] p0) { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration build() { return new android.net.ipsec.ike.IkeSessionConfiguration(); }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder clearIkeExtensions() { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder clearPcscfServers() { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder clearRemoteApplicationVersion() { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder clearRemoteVendorIds() { return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder setEapInfo(android.net.eap.EapInfo p0) { huskProps.put("EapInfo", p0); return this; }
        public android.net.ipsec.ike.IkeSessionConfiguration.Builder setRemoteApplicationVersion(java.lang.String p0) { huskProps.put("RemoteApplicationVersion", p0); return this; }
        Builder() { this((android.net.ipsec.ike.IkeSessionConnectionInfo) null); }
    }
}
