// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class AggregateRecordsResponse {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AggregateRecordsResponse(java.util.Map p0) {}
    public static java.util.Set getDataOriginsInternal(android.health.connect.datatypes.AggregationType p0, java.util.Map p1) { return new java.util.HashSet(); }
    public static java.lang.Object getInternal(android.health.connect.datatypes.AggregationType p0, java.util.Map p1) { return null; }
    public static java.time.ZoneOffset getZoneOffsetInternal(android.health.connect.datatypes.AggregationType p0, java.util.Map p1) { return null; }
    public java.lang.Object get(android.health.connect.datatypes.AggregationType p0) { return null; }
    public java.util.Map getAggregateResults() { return (huskProps.get("AggregateResults") != null ? (java.util.Map) huskProps.get("AggregateResults") : new java.util.HashMap()); }
    public java.util.Set getDataOrigins(android.health.connect.datatypes.AggregationType p0) { return new java.util.HashSet(); }
    public java.time.ZoneOffset getFirstZoneOffset() { return (java.time.ZoneOffset) huskProps.get("FirstZoneOffset"); }
    public java.time.ZoneOffset getZoneOffset(android.health.connect.datatypes.AggregationType p0) { return null; }
    AggregateRecordsResponse() { this((java.util.Map) null); }
}
