// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.system.keystore2;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class KeyDescriptor implements android.os.Parcelable {
    protected KeyDescriptor() {}
}
