// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect.datatypes;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DistanceRecord extends android.health.connect.datatypes.IntervalRecord {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.health.connect.datatypes.AggregationType DISTANCE_TOTAL;
    public android.health.connect.datatypes.units.Length getDistance() { return (android.health.connect.datatypes.units.Length) huskProps.get("Distance"); }
    public android.health.connect.internal.datatypes.DistanceRecordInternal toRecordInternal() { return null; }
    protected DistanceRecord() { super(); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.health.connect.datatypes.Metadata p0, java.time.Instant p1, java.time.Instant p2, android.health.connect.datatypes.units.Length p3) {}
        public android.health.connect.datatypes.DistanceRecord build() { return new android.health.connect.datatypes.DistanceRecord(); }
        public android.health.connect.datatypes.DistanceRecord buildWithoutValidation() { return null; }
        public android.health.connect.datatypes.DistanceRecord.Builder clearEndZoneOffset() { return this; }
        public android.health.connect.datatypes.DistanceRecord.Builder clearStartZoneOffset() { return this; }
        public android.health.connect.datatypes.DistanceRecord.Builder setEndZoneOffset(java.time.ZoneOffset p0) { huskProps.put("EndZoneOffset", p0); return this; }
        public android.health.connect.datatypes.DistanceRecord.Builder setStartZoneOffset(java.time.ZoneOffset p0) { huskProps.put("StartZoneOffset", p0); return this; }
        Builder() { this((android.health.connect.datatypes.Metadata) null, (java.time.Instant) null, (java.time.Instant) null, (android.health.connect.datatypes.units.Length) null); }
    }
}
