// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect.datatypes;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class HeightRecord extends android.health.connect.datatypes.InstantRecord {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.health.connect.datatypes.AggregationType HEIGHT_AVG;
    public static android.health.connect.datatypes.AggregationType HEIGHT_MAX;
    public static android.health.connect.datatypes.AggregationType HEIGHT_MIN;
    public android.health.connect.datatypes.units.Length getHeight() { return (android.health.connect.datatypes.units.Length) huskProps.get("Height"); }
    public android.health.connect.internal.datatypes.HeightRecordInternal toRecordInternal() { return null; }
    protected HeightRecord() { super(); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.health.connect.datatypes.Metadata p0, java.time.Instant p1, android.health.connect.datatypes.units.Length p2) {}
        public android.health.connect.datatypes.HeightRecord build() { android.health.connect.datatypes.HeightRecord x = new android.health.connect.datatypes.HeightRecord(); x.huskProps.putAll(huskProps); return x; }
        public android.health.connect.datatypes.HeightRecord buildWithoutValidation() { return null; }
        public android.health.connect.datatypes.HeightRecord.Builder clearZoneOffset() { return this; }
        public android.health.connect.datatypes.HeightRecord.Builder setZoneOffset(java.time.ZoneOffset p0) { huskProps.put("ZoneOffset", p0); return this; }
        Builder() { this((android.health.connect.datatypes.Metadata) null, (java.time.Instant) null, (android.health.connect.datatypes.units.Length) null); }
    }
}
