// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect.datatypes;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class HydrationRecord extends android.health.connect.datatypes.IntervalRecord {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.health.connect.datatypes.AggregationType VOLUME_TOTAL;
    public android.health.connect.datatypes.units.Volume getVolume() { return (android.health.connect.datatypes.units.Volume) huskProps.get("Volume"); }
    public android.health.connect.internal.datatypes.HydrationRecordInternal toRecordInternal() { return null; }
    protected HydrationRecord() { super(); }
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.health.connect.datatypes.Metadata p0, java.time.Instant p1, java.time.Instant p2, android.health.connect.datatypes.units.Volume p3) {}
        public android.health.connect.datatypes.HydrationRecord build() { return new android.health.connect.datatypes.HydrationRecord(); }
        public android.health.connect.datatypes.HydrationRecord buildWithoutValidation() { return null; }
        public android.health.connect.datatypes.HydrationRecord.Builder clearEndZoneOffset() { return this; }
        public android.health.connect.datatypes.HydrationRecord.Builder clearStartZoneOffset() { return this; }
        public android.health.connect.datatypes.HydrationRecord.Builder setEndZoneOffset(java.time.ZoneOffset p0) { huskProps.put("EndZoneOffset", p0); return this; }
        public android.health.connect.datatypes.HydrationRecord.Builder setStartZoneOffset(java.time.ZoneOffset p0) { huskProps.put("StartZoneOffset", p0); return this; }
        Builder() { this((android.health.connect.datatypes.Metadata) null, (java.time.Instant) null, (java.time.Instant) null, (android.health.connect.datatypes.units.Volume) null); }
    }
}
