// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.health.connect.datatypes;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class Record {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public android.health.connect.datatypes.Metadata getMetadata() { return (android.health.connect.datatypes.Metadata) huskProps.get("Metadata"); }
    public int getRecordType() { return (huskProps.get("RecordType") instanceof Integer ? (Integer) huskProps.get("RecordType") : 0); }
    public abstract android.health.connect.internal.datatypes.RecordInternal toRecordInternal();
    protected Record() {}
}
