package android.os.storage;
public final class StorageVolume implements android.os.Parcelable {
    public java.io.File getDirectory() { return new java.io.File(husk.Native.externalDir()); }
    public boolean isPrimary() { return true; } public boolean isRemovable() { return false; } public boolean isEmulated() { return true; }
    public String getState() { return "mounted"; } public String getUuid() { return null; } public String getDescription(android.content.Context c) { return "Internal storage"; }
    public int describeContents() { return 0; }
    /* the hidden ones file managers reach by reflection */
    public String getPath() { return husk.Native.externalDir(); }
    public java.io.File getPathFile() { return getDirectory(); }
    public String getId() { return "emulated;0"; }
    public String getMediaStoreVolumeName() { return "external_primary"; }
    public java.io.File getInternalPath() { return getDirectory(); }
    public String getUserLabel() { return "Internal storage"; }
    public boolean isVisible() { return true; }
    public boolean allowMassStorage() { return false; }
    public long getMaxFileSize() { return 0; }
    public android.os.UserHandle getOwner() { return android.os.UserHandle.getUserHandleForUid(android.os.Process.myUid()); }
    public android.content.Intent createOpenDocumentTreeIntent() { return new android.content.Intent("android.intent.action.OPEN_DOCUMENT_TREE"); }
    public android.content.Intent createAccessIntent(String directoryName) { return null; }
    @Override public boolean equals(Object o) { return o instanceof StorageVolume; }
    @Override public int hashCode() { return 1; }
    @Override public String toString() { return "StorageVolume: Internal storage"; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public StorageVolume() {}
    public static android.os.Parcelable.Creator CREATOR;
    public static final java.lang.String EXTRA_DIRECTORY_NAME = "android.os.storage.extra.DIRECTORY_NAME";
    public static final java.lang.String EXTRA_STORAGE_VOLUME = "android.os.storage.extra.STORAGE_VOLUME";
    public static final int STORAGE_ID_INVALID = 0;
    public static final int STORAGE_ID_PRIMARY = 65537;
    public StorageVolume(java.lang.String p0, java.io.File p1, java.io.File p2, java.lang.String p3, boolean p4, boolean p5, boolean p6, boolean p7, boolean p8, long p9, android.os.UserHandle p10, java.util.UUID p11, java.lang.String p12, java.lang.String p13) { this(); }
    public static java.lang.String normalizeUuid(java.lang.String p0) { return null; }
    public java.lang.String dump() { return null; }
    public int getFatVolumeId() { return 0; }
    public java.lang.String getNormalizedUuid() { return null; }
    public java.util.UUID getStorageUuid() { return null; }
    public boolean isExternallyManaged() { return false; }
    // ---- end of generated members
}
