// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ActionMenuPresenter implements android.view.ActionProvider.SubUiVisibilityListener {
    protected ActionMenuPresenter() {}
}
