// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CursorFilter extends android.widget.Filter {
    protected CursorFilter() { super(); }
    public interface CursorFilterClient {
    }
}
