// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ScanResult implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int BAND_24_GHZ_END_FREQ_MHZ = 2484;
    public static final int BAND_24_GHZ_FIRST_CH_NUM = 1;
    public static final int BAND_24_GHZ_LAST_CH_NUM = 14;
    public static final int BAND_24_GHZ_START_FREQ_MHZ = 2412;
    public static final int BAND_5_GHZ_END_FREQ_MHZ = 5885;
    public static final int BAND_5_GHZ_FIRST_CH_NUM = 32;
    public static final int BAND_5_GHZ_HIGH_LOWEST_FREQ_MHZ = 5500;
    public static final int BAND_5_GHZ_LAST_CH_NUM = 177;
    public static final int BAND_5_GHZ_LOW_HIGHEST_FREQ_MHZ = 5320;
    public static final int BAND_5_GHZ_START_FREQ_MHZ = 5160;
    public static final int BAND_60_GHZ_END_FREQ_MHZ = 70200;
    public static final int BAND_60_GHZ_FIRST_CH_NUM = 1;
    public static final int BAND_60_GHZ_LAST_CH_NUM = 6;
    public static final int BAND_60_GHZ_START_FREQ_MHZ = 58320;
    public static final int BAND_6_GHZ_END_FREQ_MHZ = 7115;
    public static final int BAND_6_GHZ_FIRST_CH_NUM = 1;
    public static final int BAND_6_GHZ_LAST_CH_NUM = 233;
    public static final int BAND_6_GHZ_OP_CLASS_136_CH_2_FREQ_MHZ = 5935;
    public static final int BAND_6_GHZ_PSC_START_MHZ = 5975;
    public static final int BAND_6_GHZ_PSC_STEP_SIZE_MHZ = 80;
    public static final int BAND_6_GHZ_START_FREQ_MHZ = 5955;
    public static final int CHANNEL_WIDTH_160MHZ = 3;
    public static final int CHANNEL_WIDTH_20MHZ = 0;
    public static final int CHANNEL_WIDTH_320MHZ = 5;
    public static final int CHANNEL_WIDTH_40MHZ = 1;
    public static final int CHANNEL_WIDTH_80MHZ = 2;
    public static final int CHANNEL_WIDTH_80MHZ_PLUS_MHZ = 4;
    public static final int CIPHER_BIP_CMAC_256 = 9;
    public static final int CIPHER_BIP_GMAC_128 = 7;
    public static final int CIPHER_BIP_GMAC_256 = 8;
    public static final int CIPHER_CCMP = 3;
    public static final int CIPHER_CCMP_256 = 10;
    public static final int CIPHER_GCMP_128 = 6;
    public static final int CIPHER_GCMP_256 = 4;
    public static final int CIPHER_NONE = 0;
    public static final int CIPHER_NO_GROUP_ADDRESSED = 1;
    public static final int CIPHER_SMS4 = 5;
    public static final int CIPHER_TKIP = 2;
    public static android.os.Parcelable.Creator CREATOR;
    public static final long FLAG_80211az_NTB_RESPONDER = 4L;
    public static final long FLAG_80211mc_RESPONDER = 2L;
    public static final long FLAG_PASSPOINT_NETWORK = 1L;
    public static final long FLAG_RANGING_FRAME_PROTECTION_REQUIRED = 32L;
    public static final long FLAG_SECURE_HE_LTF_SUPPORTED = 16L;
    public static final long FLAG_TWT_RESPONDER = 8L;
    public static final int KEY_MGMT_DPP = 17;
    public static final int KEY_MGMT_EAP = 2;
    public static final int KEY_MGMT_EAP_FT_SHA384 = 21;
    public static final int KEY_MGMT_EAP_SHA256 = 6;
    public static final int KEY_MGMT_EAP_SUITE_B_192 = 10;
    public static final int KEY_MGMT_FILS_SHA256 = 15;
    public static final int KEY_MGMT_FILS_SHA384 = 16;
    public static final int KEY_MGMT_FT_EAP = 4;
    public static final int KEY_MGMT_FT_PSK = 3;
    public static final int KEY_MGMT_FT_PSK_SHA384 = 22;
    public static final int KEY_MGMT_FT_SAE = 11;
    public static final int KEY_MGMT_FT_SAE_EXT_KEY = 19;
    public static final int KEY_MGMT_NONE = 0;
    public static final int KEY_MGMT_OSEN = 7;
    public static final int KEY_MGMT_OWE = 9;
    public static final int KEY_MGMT_OWE_TRANSITION = 12;
    public static final int KEY_MGMT_PASN = 20;
    public static final int KEY_MGMT_PSK = 1;
    public static final int KEY_MGMT_PSK_SHA256 = 5;
    public static final int KEY_MGMT_SAE = 8;
    public static final int KEY_MGMT_SAE_EXT_KEY = 18;
    public static final int KEY_MGMT_UNKNOWN = 23;
    public static final int KEY_MGMT_WAPI_CERT = 14;
    public static final int KEY_MGMT_WAPI_PSK = 13;
    public static final int PREAMBLE_EHT = 4;
    public static final int PREAMBLE_HE = 3;
    public static final int PREAMBLE_HT = 1;
    public static final int PREAMBLE_LEGACY = 0;
    public static final int PREAMBLE_VHT = 2;
    public static final int PROTOCOL_NONE = 0;
    public static final int PROTOCOL_OSEN = 3;
    public static final int PROTOCOL_RSN = 2;
    public static final int PROTOCOL_WAPI = 4;
    public static final int PROTOCOL_WPA = 1;
    public static final int UNSPECIFIED = -1;
    public static final int WIFI_BAND_24_GHZ = 1;
    public static final int WIFI_BAND_5_GHZ = 2;
    public static final int WIFI_BAND_5_GHZ_HIGH = 1073741824;
    public static final int WIFI_BAND_5_GHZ_LOW = 536870912;
    public static final int WIFI_BAND_60_GHZ = 16;
    public static final int WIFI_BAND_6_GHZ = 8;
    public static final int WIFI_STANDARD_11AC = 5;
    public static final int WIFI_STANDARD_11AD = 7;
    public static final int WIFI_STANDARD_11AX = 6;
    public static final int WIFI_STANDARD_11BE = 8;
    public static final int WIFI_STANDARD_11N = 4;
    public static final int WIFI_STANDARD_LEGACY = 1;
    public static int WIFI_STANDARD_UNKNOWN;
    public java.lang.String BSSID;
    public java.lang.String SSID;
    public int anqpDomainId;
    public android.net.wifi.AnqpInformationElement[] anqpElements;
    public java.util.List anqpLines;
    public java.lang.String capabilities;
    public int centerFreq0;
    public int centerFreq1;
    public int channelWidth;
    public int distanceCm;
    public int distanceSdCm;
    public long flags;
    public int frequency;
    public long hessid;
    public java.lang.String ifaceName;
    public android.net.wifi.ScanResult.InformationElement[] informationElements;
    public boolean is80211McRTTResponder;
    public int level;
    public int numUsage;
    public java.lang.CharSequence operatorFriendlyName;
    public android.net.wifi.ScanResult.RadioChainInfo[] radioChainInfos;
    public long seen;
    public long timestamp;
    public boolean untrusted;
    public java.lang.CharSequence venueName;
    public android.net.wifi.WifiSsid wifiSsid;
    public ScanResult() {}
    public ScanResult(android.net.wifi.ScanResult p0) {}
    public ScanResult(android.net.wifi.WifiSsid p0, java.lang.String p1, long p2, int p3, byte[] p4, java.lang.String p5, int p6, int p7, long p8) {}
    public ScanResult(android.net.wifi.WifiSsid p0, java.lang.String p1, java.lang.String p2, int p3, int p4, long p5, int p6, int p7) {}
    public ScanResult(android.net.wifi.WifiSsid p0, java.lang.String p1, java.lang.String p2, long p3, int p4, java.lang.String p5, int p6, int p7, long p8, int p9, int p10, int p11, int p12, int p13, boolean p14) {}
    public ScanResult(java.lang.String p0, java.lang.String p1, long p2, int p3, java.lang.String p4, int p5, int p6, long p7, int p8, int p9, int p10, int p11, int p12, boolean p13) {}
    public static int convertChannelToFrequencyMhzIfSupported(int p0, int p1) { return 0; }
    public static int convertFrequencyMhzToChannelIfSupported(int p0) { return 0; }
    public static int getBandFromOpClass(int p0, int p1) { return 0; }
    public static boolean is24GHz(int p0) { return false; }
    public static boolean is5GHz(int p0) { return false; }
    public static boolean is60GHz(int p0) { return false; }
    public static boolean is6GHz(int p0) { return false; }
    public static boolean is6GHzPsc(int p0) { return false; }
    public static boolean isValidCombinedBandForDual5GHz(int p0, int p1) { return false; }
    public static int toBand(int p0) { return 0; }
    public static java.lang.String wifiStandardToString(int p0) { return null; }
    public void clearFlag(long p0) {}
    public int describeContents() { return 0; }
    public java.util.List getAffiliatedMloLinks() { return (huskProps.get("AffiliatedMloLinks") != null ? (java.util.List) huskProps.get("AffiliatedMloLinks") : new java.util.ArrayList()); }
    public android.net.MacAddress getApMldMacAddress() { return (android.net.MacAddress) huskProps.get("ApMldMacAddress"); }
    public int getApMloLinkId() { return (huskProps.get("ApMloLinkId") instanceof Integer ? (Integer) huskProps.get("ApMloLinkId") : 0); }
    public int getBand() { return (huskProps.get("Band") instanceof Integer ? (Integer) huskProps.get("Band") : 0); }
    public java.util.List getInformationElements() { return (huskProps.get("InformationElements") != null ? (java.util.List) huskProps.get("InformationElements") : new java.util.ArrayList()); }
    public int[] getSecurityTypes() { return (int[]) huskProps.get("SecurityTypes"); }
    public android.net.wifi.WifiSsid getWifiSsid() { return (android.net.wifi.WifiSsid) huskProps.get("WifiSsid"); }
    public int getWifiStandard() { return (huskProps.get("WifiStandard") instanceof Integer ? (Integer) huskProps.get("WifiStandard") : 0); }
    public boolean is24GHz() { return (huskProps.get("24GHz") instanceof Boolean ? (Boolean) huskProps.get("24GHz") : false); }
    public boolean is5GHz() { return (huskProps.get("5GHz") instanceof Boolean ? (Boolean) huskProps.get("5GHz") : false); }
    public boolean is60GHz() { return (huskProps.get("60GHz") instanceof Boolean ? (Boolean) huskProps.get("60GHz") : false); }
    public boolean is6GHz() { return (huskProps.get("6GHz") instanceof Boolean ? (Boolean) huskProps.get("6GHz") : false); }
    public boolean is6GhzPsc() { return (huskProps.get("6GhzPsc") instanceof Boolean ? (Boolean) huskProps.get("6GhzPsc") : false); }
    public boolean is80211azNtbResponder() { return (huskProps.get("80211azNtbResponder") instanceof Boolean ? (Boolean) huskProps.get("80211azNtbResponder") : false); }
    public boolean is80211mcResponder() { return (huskProps.get("80211mcResponder") instanceof Boolean ? (Boolean) huskProps.get("80211mcResponder") : false); }
    public boolean isPasspointNetwork() { return (huskProps.get("PasspointNetwork") instanceof Boolean ? (Boolean) huskProps.get("PasspointNetwork") : false); }
    public boolean isRangingFrameProtectionRequired() { return (huskProps.get("RangingFrameProtectionRequired") instanceof Boolean ? (Boolean) huskProps.get("RangingFrameProtectionRequired") : false); }
    public boolean isSecureHeLtfSupported() { return (huskProps.get("SecureHeLtfSupported") instanceof Boolean ? (Boolean) huskProps.get("SecureHeLtfSupported") : false); }
    public boolean isTwtResponder() { return (huskProps.get("TwtResponder") instanceof Boolean ? (Boolean) huskProps.get("TwtResponder") : false); }
    public void setAffiliatedMloLinks(java.util.List p0) { huskProps.put("AffiliatedMloLinks", p0); }
    public void setApMldMacAddress(android.net.MacAddress p0) { huskProps.put("ApMldMacAddress", p0); }
    public void setApMloLinkId(int p0) { huskProps.put("ApMloLinkId", Integer.valueOf(p0)); }
    public void setFlag(long p0) { huskProps.put("Flag", Long.valueOf(p0)); }
    public void setWifiSsid(android.net.wifi.WifiSsid p0) { huskProps.put("WifiSsid", p0); }
    public void setWifiStandard(int p0) { huskProps.put("WifiStandard", Integer.valueOf(p0)); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public Builder(android.net.wifi.WifiSsid p0, java.lang.String p1) {}
        public android.net.wifi.ScanResult build() { return new android.net.wifi.ScanResult(); }
        public void clear() {}
        public android.net.wifi.ScanResult.Builder setAnqpDomainId(int p0) { huskProps.put("AnqpDomainId", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setBssid(java.lang.String p0) { huskProps.put("Bssid", p0); return this; }
        public android.net.wifi.ScanResult.Builder setCaps(java.lang.String p0) { huskProps.put("Caps", p0); return this; }
        public android.net.wifi.ScanResult.Builder setCenterFreq0(int p0) { huskProps.put("CenterFreq0", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setCenterFreq1(int p0) { huskProps.put("CenterFreq1", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setChannelWidth(int p0) { huskProps.put("ChannelWidth", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setDistanceCm(int p0) { huskProps.put("DistanceCm", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setDistanceSdCm(int p0) { huskProps.put("DistanceSdCm", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setFrequency(int p0) { huskProps.put("Frequency", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setHessid(long p0) { huskProps.put("Hessid", Long.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setIs80211McRTTResponder(boolean p0) { huskProps.put("Is80211McRTTResponder", Boolean.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setIs80211azNtbRTTResponder(boolean p0) { huskProps.put("Is80211azNtbRTTResponder", Boolean.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setIsTwtResponder(boolean p0) { huskProps.put("IsTwtResponder", Boolean.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setOsuProviders(byte[] p0) { huskProps.put("OsuProviders", p0); return this; }
        public android.net.wifi.ScanResult.Builder setRangingFrameProtectionRequired(boolean p0) { huskProps.put("RangingFrameProtectionRequired", Boolean.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setRssi(int p0) { huskProps.put("Rssi", Integer.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setSecureHeLtfSupported(boolean p0) { huskProps.put("SecureHeLtfSupported", Boolean.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setTsf(long p0) { huskProps.put("Tsf", Long.valueOf(p0)); return this; }
        public android.net.wifi.ScanResult.Builder setWifiSsid(android.net.wifi.WifiSsid p0) { huskProps.put("WifiSsid", p0); return this; }
    }
    public static class InformationElement implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public static final int EID_BSS_LOAD = 11;
        public static final int EID_COUNTRY = 7;
        public static final int EID_ERP = 42;
        public static final int EID_EXTENDED_CAPS = 127;
        public static final int EID_EXTENDED_SUPPORTED_RATES = 50;
        public static final int EID_EXTENSION_PRESENT = 255;
        public static final int EID_EXT_EHT_CAPABILITIES = 108;
        public static final int EID_EXT_EHT_OPERATION = 106;
        public static final int EID_EXT_HE_CAPABILITIES = 35;
        public static final int EID_EXT_HE_OPERATION = 36;
        public static final int EID_EXT_MULTI_LINK = 107;
        public static final int EID_FRAGMENT_SUB_ELEMENT_MULTI_LINK = 254;
        public static final int EID_HT_CAPABILITIES = 45;
        public static final int EID_HT_OPERATION = 61;
        public static final int EID_INTERWORKING = 107;
        public static final int EID_RNR = 201;
        public static final int EID_ROAMING_CONSORTIUM = 111;
        public static final int EID_RSN = 48;
        public static final int EID_RSN_EXTENSION = 244;
        public static final int EID_SSID = 0;
        public static final int EID_SUPPORTED_RATES = 1;
        public static final int EID_TIM = 5;
        public static final int EID_VHT_CAPABILITIES = 191;
        public static final int EID_VHT_OPERATION = 192;
        public static final int EID_VSA = 221;
        public byte[] bytes;
        public int id;
        public int idExt;
        public InformationElement() {}
        public InformationElement(int p0, int p1, byte[] p2) {}
        public InformationElement(android.net.wifi.ScanResult.InformationElement p0) {}
        public int describeContents() { return 0; }
        public java.nio.ByteBuffer getBytes() { return (java.nio.ByteBuffer) huskProps.get("Bytes"); }
        public int getId() { return (huskProps.get("Id") instanceof Integer ? (Integer) huskProps.get("Id") : 0); }
        public int getIdExt() { return (huskProps.get("IdExt") instanceof Integer ? (Integer) huskProps.get("IdExt") : 0); }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
    }
    public static class RadioChainInfo {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int id;
        public int level;
        public RadioChainInfo() {}
    }
}
