// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.net.wifi;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public enum SupplicantState implements android.os.Parcelable {
    ASSOCIATED, ASSOCIATING, AUTHENTICATING, COMPLETED, DISCONNECTED, DORMANT, FOUR_WAY_HANDSHAKE, GROUP_HANDSHAKE, INACTIVE, INTERFACE_DISABLED, INVALID, SCANNING, UNINITIALIZED;
    public static android.os.Parcelable.Creator CREATOR;
    public static boolean isConnecting(android.net.wifi.SupplicantState p0) { return false; }
    public static boolean isDriverActive(android.net.wifi.SupplicantState p0) { return false; }
    public static boolean isHandshakeState(android.net.wifi.SupplicantState p0) { return false; }
    public static boolean isValidState(android.net.wifi.SupplicantState p0) { return false; }
    public int describeContents() { return 0; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
