// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view.translation;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class UiTranslationManager {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_PACKAGE_NAME = "package_name";
    public static final java.lang.String EXTRA_SOURCE_LOCALE = "source_locale";
    public static final java.lang.String EXTRA_STATE = "state";
    public static final java.lang.String EXTRA_TARGET_LOCALE = "target_locale";
    public static final java.lang.String LOG_TAG = "UiTranslation";
    public static final int STATE_UI_TRANSLATION_FINISHED = 3;
    public static final int STATE_UI_TRANSLATION_PAUSED = 1;
    public static final int STATE_UI_TRANSLATION_RESUMED = 2;
    public static final int STATE_UI_TRANSLATION_STARTED = 0;
    public UiTranslationManager(android.content.Context p0, android.view.translation.ITranslationManager p1) {}
    public void finishTranslation(android.app.assist.ActivityId p0) {}
    public void onTranslationFinished(boolean p0, android.app.assist.ActivityId p1, android.content.ComponentName p2) {}
    public void pauseTranslation(android.app.assist.ActivityId p0) {}
    public void registerUiTranslationStateCallback(java.util.concurrent.Executor p0, android.view.translation.UiTranslationStateCallback p1) {}
    public void resumeTranslation(android.app.assist.ActivityId p0) {}
    public void startTranslation(android.view.translation.TranslationSpec p0, android.view.translation.TranslationSpec p1, java.util.List p2, android.app.assist.ActivityId p3) {}
    public void startTranslation(android.view.translation.TranslationSpec p0, android.view.translation.TranslationSpec p1, java.util.List p2, android.app.assist.ActivityId p3, android.view.translation.UiTranslationSpec p4) {}
    public void unregisterUiTranslationStateCallback(android.view.translation.UiTranslationStateCallback p0) {}
}
