// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.view.translation;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface ViewTranslationCallback {
    default void enableContentPadding() {}
    boolean onClearTranslation(android.view.View p0);
    boolean onHideTranslation(android.view.View p0);
    boolean onShowTranslation(android.view.View p0);
    default void setAnimationDurationMillis(int p0) {}
}
