// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.hardware;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class HardwareBuffer implements android.os.Parcelable, java.lang.AutoCloseable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int BGRA_1010102 = 67;
    public static final int BGRX_1010102 = 68;
    public static final int BLOB = 33;
    public static android.os.Parcelable.Creator CREATOR;
    public static final int DS_24UI8 = 50;
    public static final int DS_FP32UI8 = 52;
    public static final int D_16 = 48;
    public static final int D_24 = 49;
    public static final int D_FP32 = 51;
    public static final int RGBA_10101010 = 59;
    public static final int RGBA_1010102 = 43;
    public static final int RGBA_12121212 = 65;
    public static final int RGBA_14141414 = 66;
    public static final int RGBA_8888 = 1;
    public static final int RGBA_FP16 = 22;
    public static final int RGBX_8888 = 2;
    public static final int RGB_565 = 4;
    public static final int RGB_888 = 3;
    public static final int RG_1212 = 63;
    public static final int RG_1414 = 64;
    public static final int RG_1616 = 58;
    public static final int R_12 = 61;
    public static final int R_14 = 62;
    public static final int R_16 = 57;
    public static final int R_8 = 56;
    public static final int S_UI8 = 53;
    public static final long USAGE_COMPOSER_OVERLAY = 2048L;
    public static final long USAGE_CPU_READ_OFTEN = 3L;
    public static final long USAGE_CPU_READ_RARELY = 2L;
    public static final long USAGE_CPU_WRITE_OFTEN = 48L;
    public static final long USAGE_CPU_WRITE_RARELY = 32L;
    public static final long USAGE_FRONT_BUFFER = 4294967296L;
    public static final long USAGE_GPU_COLOR_OUTPUT = 512L;
    public static final long USAGE_GPU_CUBE_MAP = 33554432L;
    public static final long USAGE_GPU_DATA_BUFFER = 16777216L;
    public static final long USAGE_GPU_MIPMAP_COMPLETE = 67108864L;
    public static final long USAGE_GPU_SAMPLED_IMAGE = 256L;
    public static final long USAGE_PROTECTED_CONTENT = 16384L;
    public static final long USAGE_SENSOR_DIRECT_DATA = 8388608L;
    public static final long USAGE_VIDEO_ENCODE = 65536L;
    public static final int YCBCR_420_888 = 35;
    public static final int YCBCR_P010 = 54;
    public static final int YCBCR_P210 = 60;
    public static android.hardware.HardwareBuffer create(int p0, int p1, int p2, int p3, long p4) { return new HardwareBuffer(); }
    public static android.hardware.HardwareBuffer createFromGraphicBuffer(android.graphics.GraphicBuffer p0) { return new HardwareBuffer(); }
    public static boolean isSupported(int p0, int p1, int p2, int p3, long p4) { return false; }
    public void close() {}
    public int describeContents() { return 0; }
    protected void finalize() {}
    public int getFormat() { return (huskProps.get("Format") instanceof Integer ? (Integer) huskProps.get("Format") : 0); }
    public int getHeight() { return (huskProps.get("Height") instanceof Integer ? (Integer) huskProps.get("Height") : 0); }
    public long getId() { return (huskProps.get("Id") instanceof Long ? (Long) huskProps.get("Id") : 0L); }
    public int getLayers() { return (huskProps.get("Layers") instanceof Integer ? (Integer) huskProps.get("Layers") : 0); }
    public long getUsage() { return (huskProps.get("Usage") instanceof Long ? (Long) huskProps.get("Usage") : 0L); }
    public int getWidth() { return (huskProps.get("Width") instanceof Integer ? (Integer) huskProps.get("Width") : 0); }
    public boolean isClosed() { return (huskProps.get("Closed") instanceof Boolean ? (Boolean) huskProps.get("Closed") : false); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected HardwareBuffer() {}
}
