// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.hardware;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class SensorAdditionalInfo {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int TYPE_CUSTOM_INFO = 268435456;
    public static final int TYPE_DEBUG_INFO = 1073741824;
    public static final int TYPE_DOCK_STATE = 196610;
    public static final int TYPE_FRAME_BEGIN = 0;
    public static final int TYPE_FRAME_END = 1;
    public static final int TYPE_HIGH_PERFORMANCE_MODE = 196611;
    public static final int TYPE_INTERNAL_TEMPERATURE = 65537;
    public static final int TYPE_LOCAL_GEOMAGNETIC_FIELD = 196608;
    public static final int TYPE_LOCAL_GRAVITY = 196609;
    public static final int TYPE_MAGNETIC_FIELD_CALIBRATION = 196612;
    public static final int TYPE_SAMPLING = 65540;
    public static final int TYPE_SENSOR_PLACEMENT = 65539;
    public static final int TYPE_UNTRACKED_DELAY = 65536;
    public static final int TYPE_VEC3_CALIBRATION = 65538;
    public float[] floatValues;
    public int[] intValues;
    public android.hardware.Sensor sensor;
    public int serial;
    public int type;
    public static android.hardware.SensorAdditionalInfo createCustomInfo(android.hardware.Sensor p0, int p1, float[] p2) { return new SensorAdditionalInfo(); }
    public static android.hardware.SensorAdditionalInfo createLocalGeomagneticField(float p0, float p1, float p2) { return new SensorAdditionalInfo(); }
    protected SensorAdditionalInfo() {}
}
