// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.assist;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AssistStructure implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public AssistStructure() {}
    public AssistStructure(android.app.Activity p0, boolean p1, int p2) {}
    public AssistStructure(android.os.Parcel p0) {}
    public void clearSendChannel() {}
    public int describeContents() { return 0; }
    public void dump(boolean p0) {}
    public void ensureData() {}
    public void ensureDataForAutofill() {}
    public long getAcquisitionEndTime() { return (huskProps.get("AcquisitionEndTime") instanceof Long ? (Long) huskProps.get("AcquisitionEndTime") : 0L); }
    public long getAcquisitionStartTime() { return (huskProps.get("AcquisitionStartTime") instanceof Long ? (Long) huskProps.get("AcquisitionStartTime") : 0L); }
    public android.content.ComponentName getActivityComponent() { return (android.content.ComponentName) huskProps.get("ActivityComponent"); }
    public int getFlags() { return (huskProps.get("Flags") instanceof Integer ? (Integer) huskProps.get("Flags") : 0); }
    public int getTaskId() { return (huskProps.get("TaskId") instanceof Integer ? (Integer) huskProps.get("TaskId") : 0); }
    public android.app.assist.AssistStructure.WindowNode getWindowNodeAt(int p0) { return null; }
    public int getWindowNodeCount() { return (huskProps.get("WindowNodeCount") instanceof Integer ? (Integer) huskProps.get("WindowNodeCount") : 0); }
    public boolean isHomeActivity() { return (huskProps.get("HomeActivity") instanceof Boolean ? (Boolean) huskProps.get("HomeActivity") : false); }
    public void sanitizeForParceling(boolean p0) {}
    public void setAcquisitionEndTime(long p0) { huskProps.put("AcquisitionEndTime", Long.valueOf(p0)); }
    public void setAcquisitionStartTime(long p0) { huskProps.put("AcquisitionStartTime", Long.valueOf(p0)); }
    public void setActivityComponent(android.content.ComponentName p0) { huskProps.put("ActivityComponent", p0); }
    public void setHomeActivity(boolean p0) { huskProps.put("HomeActivity", Boolean.valueOf(p0)); }
    public void setTaskId(int p0) { huskProps.put("TaskId", Integer.valueOf(p0)); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    public static class AutofillOverlay {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public boolean focused;
        public android.view.autofill.AutofillValue value;
        public AutofillOverlay() {}
    }
    public static class ViewNode {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int TEXT_COLOR_UNDEFINED = 1;
        public static final int TEXT_STYLE_BOLD = 1;
        public static final int TEXT_STYLE_ITALIC = 2;
        public static final int TEXT_STYLE_STRIKE_THRU = 8;
        public static final int TEXT_STYLE_UNDERLINE = 4;
        public ViewNode() {}
        public float getAlpha() { return (huskProps.get("Alpha") instanceof Float ? (Float) huskProps.get("Alpha") : 0f); }
        public java.lang.String[] getAutofillHints() { return (java.lang.String[]) huskProps.get("AutofillHints"); }
        public android.view.autofill.AutofillId getAutofillId() { return (android.view.autofill.AutofillId) huskProps.get("AutofillId"); }
        public java.lang.CharSequence[] getAutofillOptions() { return (java.lang.CharSequence[]) huskProps.get("AutofillOptions"); }
        public int getAutofillType() { return (huskProps.get("AutofillType") instanceof Integer ? (Integer) huskProps.get("AutofillType") : 0); }
        public android.view.autofill.AutofillValue getAutofillValue() { return (android.view.autofill.AutofillValue) huskProps.get("AutofillValue"); }
        public android.app.assist.AssistStructure.ViewNode getChildAt(int p0) { return this; }
        public int getChildCount() { return (huskProps.get("ChildCount") instanceof Integer ? (Integer) huskProps.get("ChildCount") : 0); }
        public java.lang.String getClassName() { return (java.lang.String) huskProps.get("ClassName"); }
        public java.lang.CharSequence getContentDescription() { return (java.lang.CharSequence) huskProps.get("ContentDescription"); }
        public float getElevation() { return (huskProps.get("Elevation") instanceof Float ? (Float) huskProps.get("Elevation") : 0f); }
        public android.os.Bundle getExtras() { return (android.os.Bundle) huskProps.get("Extras"); }
        public int getHeight() { return (huskProps.get("Height") instanceof Integer ? (Integer) huskProps.get("Height") : 0); }
        public java.lang.String getHint() { return (java.lang.String) huskProps.get("Hint"); }
        public java.lang.String getHintIdEntry() { return (java.lang.String) huskProps.get("HintIdEntry"); }
        public android.view.ViewStructure.HtmlInfo getHtmlInfo() { return (android.view.ViewStructure.HtmlInfo) huskProps.get("HtmlInfo"); }
        public int getId() { return (huskProps.get("Id") instanceof Integer ? (Integer) huskProps.get("Id") : 0); }
        public java.lang.String getIdEntry() { return (java.lang.String) huskProps.get("IdEntry"); }
        public java.lang.String getIdPackage() { return (java.lang.String) huskProps.get("IdPackage"); }
        public java.lang.String getIdType() { return (java.lang.String) huskProps.get("IdType"); }
        public int getImportantForAutofill() { return (huskProps.get("ImportantForAutofill") instanceof Integer ? (Integer) huskProps.get("ImportantForAutofill") : 0); }
        public int getInputType() { return (huskProps.get("InputType") instanceof Integer ? (Integer) huskProps.get("InputType") : 0); }
        public int getLeft() { return (huskProps.get("Left") instanceof Integer ? (Integer) huskProps.get("Left") : 0); }
        public android.os.LocaleList getLocaleList() { return (android.os.LocaleList) huskProps.get("LocaleList"); }
        public int getMaxTextEms() { return (huskProps.get("MaxTextEms") instanceof Integer ? (Integer) huskProps.get("MaxTextEms") : 0); }
        public int getMaxTextLength() { return (huskProps.get("MaxTextLength") instanceof Integer ? (Integer) huskProps.get("MaxTextLength") : 0); }
        public int getMinTextEms() { return (huskProps.get("MinTextEms") instanceof Integer ? (Integer) huskProps.get("MinTextEms") : 0); }
        public android.os.ResultReceiver getPendingCredentialCallback() { return (android.os.ResultReceiver) huskProps.get("PendingCredentialCallback"); }
        public android.credentials.GetCredentialRequest getPendingCredentialRequest() { return (android.credentials.GetCredentialRequest) huskProps.get("PendingCredentialRequest"); }
        public java.lang.String[] getReceiveContentMimeTypes() { return (java.lang.String[]) huskProps.get("ReceiveContentMimeTypes"); }
        public int getScrollX() { return (huskProps.get("ScrollX") instanceof Integer ? (Integer) huskProps.get("ScrollX") : 0); }
        public int getScrollY() { return (huskProps.get("ScrollY") instanceof Integer ? (Integer) huskProps.get("ScrollY") : 0); }
        public java.lang.CharSequence getText() { return (java.lang.CharSequence) huskProps.get("Text"); }
        public int getTextBackgroundColor() { return (huskProps.get("TextBackgroundColor") instanceof Integer ? (Integer) huskProps.get("TextBackgroundColor") : 0); }
        public int getTextColor() { return (huskProps.get("TextColor") instanceof Integer ? (Integer) huskProps.get("TextColor") : 0); }
        public java.lang.String getTextIdEntry() { return (java.lang.String) huskProps.get("TextIdEntry"); }
        public int[] getTextLineBaselines() { return (int[]) huskProps.get("TextLineBaselines"); }
        public int[] getTextLineCharOffsets() { return (int[]) huskProps.get("TextLineCharOffsets"); }
        public int getTextSelectionEnd() { return (huskProps.get("TextSelectionEnd") instanceof Integer ? (Integer) huskProps.get("TextSelectionEnd") : 0); }
        public int getTextSelectionStart() { return (huskProps.get("TextSelectionStart") instanceof Integer ? (Integer) huskProps.get("TextSelectionStart") : 0); }
        public float getTextSize() { return (huskProps.get("TextSize") instanceof Float ? (Float) huskProps.get("TextSize") : 0f); }
        public int getTextStyle() { return (huskProps.get("TextStyle") instanceof Integer ? (Integer) huskProps.get("TextStyle") : 0); }
        public int getTop() { return (huskProps.get("Top") instanceof Integer ? (Integer) huskProps.get("Top") : 0); }
        public android.graphics.Matrix getTransformation() { return (android.graphics.Matrix) huskProps.get("Transformation"); }
        public int getVisibility() { return (huskProps.get("Visibility") instanceof Integer ? (Integer) huskProps.get("Visibility") : 0); }
        public java.lang.String getWebDomain() { return (java.lang.String) huskProps.get("WebDomain"); }
        public java.lang.String getWebScheme() { return (java.lang.String) huskProps.get("WebScheme"); }
        public int getWidth() { return (huskProps.get("Width") instanceof Integer ? (Integer) huskProps.get("Width") : 0); }
        public boolean isAccessibilityFocused() { return (huskProps.get("AccessibilityFocused") instanceof Boolean ? (Boolean) huskProps.get("AccessibilityFocused") : false); }
        public boolean isActivated() { return (huskProps.get("Activated") instanceof Boolean ? (Boolean) huskProps.get("Activated") : false); }
        public boolean isAssistBlocked() { return (huskProps.get("AssistBlocked") instanceof Boolean ? (Boolean) huskProps.get("AssistBlocked") : false); }
        public boolean isCheckable() { return (huskProps.get("Checkable") instanceof Boolean ? (Boolean) huskProps.get("Checkable") : false); }
        public boolean isChecked() { return (huskProps.get("Checked") instanceof Boolean ? (Boolean) huskProps.get("Checked") : false); }
        public boolean isClickable() { return (huskProps.get("Clickable") instanceof Boolean ? (Boolean) huskProps.get("Clickable") : false); }
        public boolean isContextClickable() { return (huskProps.get("ContextClickable") instanceof Boolean ? (Boolean) huskProps.get("ContextClickable") : false); }
        public boolean isCredential() { return (huskProps.get("Credential") instanceof Boolean ? (Boolean) huskProps.get("Credential") : false); }
        public boolean isEnabled() { return (huskProps.get("Enabled") instanceof Boolean ? (Boolean) huskProps.get("Enabled") : false); }
        public boolean isFocusable() { return (huskProps.get("Focusable") instanceof Boolean ? (Boolean) huskProps.get("Focusable") : false); }
        public boolean isFocused() { return (huskProps.get("Focused") instanceof Boolean ? (Boolean) huskProps.get("Focused") : false); }
        public boolean isLongClickable() { return (huskProps.get("LongClickable") instanceof Boolean ? (Boolean) huskProps.get("LongClickable") : false); }
        public boolean isOpaque() { return (huskProps.get("Opaque") instanceof Boolean ? (Boolean) huskProps.get("Opaque") : false); }
        public boolean isSanitized() { return (huskProps.get("Sanitized") instanceof Boolean ? (Boolean) huskProps.get("Sanitized") : false); }
        public boolean isSelected() { return (huskProps.get("Selected") instanceof Boolean ? (Boolean) huskProps.get("Selected") : false); }
        public void setAutofillOverlay(android.app.assist.AssistStructure.AutofillOverlay p0) { huskProps.put("AutofillOverlay", p0); }
        public void setWebDomain(java.lang.String p0) { huskProps.put("WebDomain", p0); }
        public void updateAutofillValue(android.view.autofill.AutofillValue p0) {}
    }
    public static class ViewNodeBuilder extends android.view.ViewStructure {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ViewNodeBuilder() { super(); }
        public int addChildCount(int p0) { return 0; }
        public void asyncCommit() {}
        public android.view.ViewStructure asyncNewChild(int p0) { return null; }
        public android.view.autofill.AutofillId getAutofillId() { return (android.view.autofill.AutofillId) huskProps.get("AutofillId"); }
        public int getChildCount() { return (huskProps.get("ChildCount") instanceof Integer ? (Integer) huskProps.get("ChildCount") : 0); }
        public android.os.Bundle getExtras() { return (android.os.Bundle) huskProps.get("Extras"); }
        public java.lang.CharSequence getHint() { return (java.lang.CharSequence) huskProps.get("Hint"); }
        public android.os.OutcomeReceiver getPendingCredentialCallback() { return (android.os.OutcomeReceiver) huskProps.get("PendingCredentialCallback"); }
        public android.credentials.GetCredentialRequest getPendingCredentialRequest() { return (android.credentials.GetCredentialRequest) huskProps.get("PendingCredentialRequest"); }
        public android.graphics.Rect getTempRect() { return (android.graphics.Rect) huskProps.get("TempRect"); }
        public java.lang.CharSequence getText() { return (java.lang.CharSequence) huskProps.get("Text"); }
        public int getTextSelectionEnd() { return (huskProps.get("TextSelectionEnd") instanceof Integer ? (Integer) huskProps.get("TextSelectionEnd") : 0); }
        public int getTextSelectionStart() { return (huskProps.get("TextSelectionStart") instanceof Integer ? (Integer) huskProps.get("TextSelectionStart") : 0); }
        public android.app.assist.AssistStructure.ViewNode getViewNode() { return (android.app.assist.AssistStructure.ViewNode) huskProps.get("ViewNode"); }
        public boolean hasExtras() { return false; }
        public android.view.ViewStructure newChild(int p0) { return null; }
        public android.view.ViewStructure.HtmlInfo.Builder newHtmlInfoBuilder(java.lang.String p0) { return null; }
        public void setAccessibilityFocused(boolean p0) { huskProps.put("AccessibilityFocused", Boolean.valueOf(p0)); }
        public void setActivated(boolean p0) { huskProps.put("Activated", Boolean.valueOf(p0)); }
        public void setAlpha(float p0) { huskProps.put("Alpha", Float.valueOf(p0)); }
        public void setAssistBlocked(boolean p0) { huskProps.put("AssistBlocked", Boolean.valueOf(p0)); }
        public void setAutofillHints(java.lang.String[] p0) { huskProps.put("AutofillHints", p0); }
        public void setAutofillId(android.view.autofill.AutofillId p0) { huskProps.put("AutofillId", p0); }
        public void setAutofillId(android.view.autofill.AutofillId p0, int p1) {}
        public void setAutofillOptions(java.lang.CharSequence[] p0) { huskProps.put("AutofillOptions", p0); }
        public void setAutofillType(int p0) { huskProps.put("AutofillType", Integer.valueOf(p0)); }
        public void setAutofillValue(android.view.autofill.AutofillValue p0) { huskProps.put("AutofillValue", p0); }
        public void setCheckable(boolean p0) { huskProps.put("Checkable", Boolean.valueOf(p0)); }
        public void setChecked(boolean p0) { huskProps.put("Checked", Boolean.valueOf(p0)); }
        public void setChildCount(int p0) { huskProps.put("ChildCount", Integer.valueOf(p0)); }
        public void setClassName(java.lang.String p0) { huskProps.put("ClassName", p0); }
        public void setClickable(boolean p0) { huskProps.put("Clickable", Boolean.valueOf(p0)); }
        public void setContentDescription(java.lang.CharSequence p0) { huskProps.put("ContentDescription", p0); }
        public void setContextClickable(boolean p0) { huskProps.put("ContextClickable", Boolean.valueOf(p0)); }
        public void setDataIsSensitive(boolean p0) { huskProps.put("DataIsSensitive", Boolean.valueOf(p0)); }
        public void setDimens(int p0, int p1, int p2, int p3, int p4, int p5) {}
        public void setElevation(float p0) { huskProps.put("Elevation", Float.valueOf(p0)); }
        public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
        public void setFocusable(boolean p0) { huskProps.put("Focusable", Boolean.valueOf(p0)); }
        public void setFocused(boolean p0) { huskProps.put("Focused", Boolean.valueOf(p0)); }
        public void setHint(java.lang.CharSequence p0) { huskProps.put("Hint", p0); }
        public void setHintIdEntry(java.lang.String p0) { huskProps.put("HintIdEntry", p0); }
        public void setHtmlInfo(android.view.ViewStructure.HtmlInfo p0) { huskProps.put("HtmlInfo", p0); }
        public void setId(int p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) {}
        public void setImportantForAutofill(int p0) { huskProps.put("ImportantForAutofill", Integer.valueOf(p0)); }
        public void setInputType(int p0) { huskProps.put("InputType", Integer.valueOf(p0)); }
        public void setIsCredential(boolean p0) { huskProps.put("IsCredential", Boolean.valueOf(p0)); }
        public void setLocaleList(android.os.LocaleList p0) { huskProps.put("LocaleList", p0); }
        public void setLongClickable(boolean p0) { huskProps.put("LongClickable", Boolean.valueOf(p0)); }
        public void setMaxTextEms(int p0) { huskProps.put("MaxTextEms", Integer.valueOf(p0)); }
        public void setMaxTextLength(int p0) { huskProps.put("MaxTextLength", Integer.valueOf(p0)); }
        public void setMinTextEms(int p0) { huskProps.put("MinTextEms", Integer.valueOf(p0)); }
        public void setOpaque(boolean p0) { huskProps.put("Opaque", Boolean.valueOf(p0)); }
        public void setPendingCredentialRequest(android.credentials.GetCredentialRequest p0, android.os.OutcomeReceiver p1) {}
        public void setReceiveContentMimeTypes(java.lang.String[] p0) { huskProps.put("ReceiveContentMimeTypes", p0); }
        public void setSelected(boolean p0) { huskProps.put("Selected", Boolean.valueOf(p0)); }
        public void setText(java.lang.CharSequence p0) { huskProps.put("Text", p0); }
        public void setText(java.lang.CharSequence p0, int p1, int p2) {}
        public void setTextIdEntry(java.lang.String p0) { huskProps.put("TextIdEntry", p0); }
        public void setTextLines(int[] p0, int[] p1) {}
        public void setTextStyle(float p0, int p1, int p2, int p3) {}
        public void setTransformation(android.graphics.Matrix p0) { huskProps.put("Transformation", p0); }
        public void setVisibility(int p0) { huskProps.put("Visibility", Integer.valueOf(p0)); }
        public void setWebDomain(java.lang.String p0) { huskProps.put("WebDomain", p0); }
    }
    public static final class ViewNodeParcelable implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public ViewNodeParcelable(android.app.assist.AssistStructure.ViewNode p0) {}
        public ViewNodeParcelable(android.os.Parcel p0) {}
        public int describeContents() { return 0; }
        public android.app.assist.AssistStructure.ViewNode getViewNode() { return (android.app.assist.AssistStructure.ViewNode) huskProps.get("ViewNode"); }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        ViewNodeParcelable() { this((android.app.assist.AssistStructure.ViewNode) null); }
    }
    public static class WindowNode {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int getDisplayId() { return (huskProps.get("DisplayId") instanceof Integer ? (Integer) huskProps.get("DisplayId") : 0); }
        public int getHeight() { return (huskProps.get("Height") instanceof Integer ? (Integer) huskProps.get("Height") : 0); }
        public int getLeft() { return (huskProps.get("Left") instanceof Integer ? (Integer) huskProps.get("Left") : 0); }
        public android.app.assist.AssistStructure.ViewNode getRootViewNode() { return (android.app.assist.AssistStructure.ViewNode) huskProps.get("RootViewNode"); }
        public java.lang.CharSequence getTitle() { return (java.lang.CharSequence) huskProps.get("Title"); }
        public int getTop() { return (huskProps.get("Top") instanceof Integer ? (Integer) huskProps.get("Top") : 0); }
        public int getWidth() { return (huskProps.get("Width") instanceof Integer ? (Integer) huskProps.get("Width") : 0); }
        protected WindowNode() {}
    }
}
