// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.tv;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class TvInputInfo implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final java.lang.String EXTRA_INPUT_ID = "android.media.tv.extra.INPUT_ID";
    public static final int TYPE_COMPONENT = 1004;
    public static final int TYPE_COMPOSITE = 1001;
    public static final int TYPE_DISPLAY_PORT = 1008;
    public static final int TYPE_DVI = 1006;
    public static final int TYPE_HDMI = 1007;
    public static final int TYPE_OTHER = 1000;
    public static final int TYPE_SCART = 1003;
    public static final int TYPE_SVIDEO = 1002;
    public static final int TYPE_TUNER = 0;
    public static final int TYPE_VGA = 1005;
    public static android.media.tv.TvInputInfo createTvInputInfo(android.content.Context p0, android.content.pm.ResolveInfo p1, android.hardware.hdmi.HdmiDeviceInfo p2, java.lang.String p3, int p4, android.graphics.drawable.Icon p5) { return new TvInputInfo(); }
    public static android.media.tv.TvInputInfo createTvInputInfo(android.content.Context p0, android.content.pm.ResolveInfo p1, android.hardware.hdmi.HdmiDeviceInfo p2, java.lang.String p3, java.lang.String p4, android.net.Uri p5) { return new TvInputInfo(); }
    public static android.media.tv.TvInputInfo createTvInputInfo(android.content.Context p0, android.content.pm.ResolveInfo p1, android.media.tv.TvInputHardwareInfo p2, int p3, android.graphics.drawable.Icon p4) { return new TvInputInfo(); }
    public static android.media.tv.TvInputInfo createTvInputInfo(android.content.Context p0, android.content.pm.ResolveInfo p1, android.media.tv.TvInputHardwareInfo p2, java.lang.String p3, android.net.Uri p4) { return new TvInputInfo(); }
    public boolean canPauseRecording() { return false; }
    public boolean canRecord() { return false; }
    public android.content.Intent createSettingsIntent() { return null; }
    public android.content.Intent createSetupIntent() { return null; }
    public int describeContents() { return 0; }
    public android.content.ComponentName getComponent() { return (android.content.ComponentName) huskProps.get("Component"); }
    public android.os.Bundle getExtras() { return (android.os.Bundle) huskProps.get("Extras"); }
    public int getHdmiConnectionRelativePosition() { return (huskProps.get("HdmiConnectionRelativePosition") instanceof Integer ? (Integer) huskProps.get("HdmiConnectionRelativePosition") : 0); }
    public android.hardware.hdmi.HdmiDeviceInfo getHdmiDeviceInfo() { return (android.hardware.hdmi.HdmiDeviceInfo) huskProps.get("HdmiDeviceInfo"); }
    public java.lang.String getId() { return (java.lang.String) huskProps.get("Id"); }
    public java.lang.String getParentId() { return (java.lang.String) huskProps.get("ParentId"); }
    public android.content.pm.ServiceInfo getServiceInfo() { return (android.content.pm.ServiceInfo) huskProps.get("ServiceInfo"); }
    public int getTunerCount() { return (huskProps.get("TunerCount") instanceof Integer ? (Integer) huskProps.get("TunerCount") : 0); }
    public int getType() { return (huskProps.get("Type") instanceof Integer ? (Integer) huskProps.get("Type") : 0); }
    public boolean isConnectedToHdmiSwitch() { return (huskProps.get("ConnectedToHdmiSwitch") instanceof Boolean ? (Boolean) huskProps.get("ConnectedToHdmiSwitch") : false); }
    public boolean isHardwareInput() { return (huskProps.get("HardwareInput") instanceof Boolean ? (Boolean) huskProps.get("HardwareInput") : false); }
    public boolean isHidden(android.content.Context p0) { return false; }
    public boolean isPassthroughInput() { return (huskProps.get("PassthroughInput") instanceof Boolean ? (Boolean) huskProps.get("PassthroughInput") : false); }
    public java.lang.CharSequence loadCustomLabel(android.content.Context p0) { return null; }
    public android.graphics.drawable.Drawable loadIcon(android.content.Context p0) { return null; }
    public android.graphics.drawable.Drawable loadIcon(android.content.Context p0, int p1) { return null; }
    public java.lang.CharSequence loadLabel(android.content.Context p0) { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected TvInputInfo() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder(android.content.Context p0, android.content.ComponentName p1) {}
        public Builder(android.content.Context p0, android.content.pm.ResolveInfo p1) {}
        public android.media.tv.TvInputInfo build() { android.media.tv.TvInputInfo x = new android.media.tv.TvInputInfo(); x.huskProps.putAll(huskProps); return x; }
        public android.media.tv.TvInputInfo.Builder setCanPauseRecording(boolean p0) { huskProps.put("CanPauseRecording", Boolean.valueOf(p0)); return this; }
        public android.media.tv.TvInputInfo.Builder setCanRecord(boolean p0) { huskProps.put("CanRecord", Boolean.valueOf(p0)); return this; }
        public android.media.tv.TvInputInfo.Builder setExtras(android.os.Bundle p0) { huskProps.put("Extras", p0); return this; }
        public android.media.tv.TvInputInfo.Builder setHdmiDeviceInfo(android.hardware.hdmi.HdmiDeviceInfo p0) { huskProps.put("HdmiDeviceInfo", p0); return this; }
        public android.media.tv.TvInputInfo.Builder setIcon(android.graphics.drawable.Icon p0) { huskProps.put("Icon", p0); return this; }
        public android.media.tv.TvInputInfo.Builder setIcon(android.graphics.drawable.Icon p0, int p1) { return this; }
        public android.media.tv.TvInputInfo.Builder setLabel(int p0) { huskProps.put("Label", Integer.valueOf(p0)); return this; }
        public android.media.tv.TvInputInfo.Builder setLabel(java.lang.CharSequence p0) { huskProps.put("Label", p0); return this; }
        public android.media.tv.TvInputInfo.Builder setParentId(java.lang.String p0) { huskProps.put("ParentId", p0); return this; }
        public android.media.tv.TvInputInfo.Builder setTunerCount(int p0) { huskProps.put("TunerCount", Integer.valueOf(p0)); return this; }
        public android.media.tv.TvInputInfo.Builder setTvInputHardwareInfo(android.media.tv.TvInputHardwareInfo p0) { huskProps.put("TvInputHardwareInfo", p0); return this; }
        Builder() { this((android.content.Context) null, (android.content.ComponentName) null); }
    }
    public static final class TvInputSettings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static java.util.Map getCustomLabels(android.content.Context p0, int p1) { return new java.util.HashMap(); }
        public static java.util.Set getHiddenTvInputIds(android.content.Context p0, int p1) { return new java.util.HashSet(); }
        public static void putCustomLabels(android.content.Context p0, java.util.Map p1, int p2) {}
        public static void putHiddenTvInputs(android.content.Context p0, java.util.Set p1, int p2) {}
        protected TvInputSettings() {}
    }
}
