// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.admin;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DeviceAdminInfo implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final int HEADLESS_DEVICE_OWNER_MODE_AFFILIATED = 1;
    public static final int HEADLESS_DEVICE_OWNER_MODE_SINGLE_USER = 2;
    public static final int HEADLESS_DEVICE_OWNER_MODE_UNSUPPORTED = 0;
    public static final int USES_ENCRYPTED_STORAGE = 7;
    public static final int USES_POLICY_DISABLE_CAMERA = 8;
    public static final int USES_POLICY_DISABLE_KEYGUARD_FEATURES = 9;
    public static final int USES_POLICY_EXPIRE_PASSWORD = 6;
    public static final int USES_POLICY_FORCE_LOCK = 3;
    public static final int USES_POLICY_LIMIT_PASSWORD = 0;
    public static final int USES_POLICY_RESET_PASSWORD = 2;
    public static final int USES_POLICY_SETS_GLOBAL_PROXY = 5;
    public static final int USES_POLICY_WATCH_LOGIN = 1;
    public static final int USES_POLICY_WIPE_DATA = 4;
    public DeviceAdminInfo(android.content.Context p0, android.content.pm.ActivityInfo p1) {}
    public DeviceAdminInfo(android.content.Context p0, android.content.pm.ResolveInfo p1) {}
    public int describeContents() { return 0; }
    public void dump(android.util.Printer p0, java.lang.String p1) {}
    public android.content.pm.ActivityInfo getActivityInfo() { return (android.content.pm.ActivityInfo) huskProps.get("ActivityInfo"); }
    public android.content.ComponentName getComponent() { return (android.content.ComponentName) huskProps.get("Component"); }
    public int getHeadlessDeviceOwnerMode() { return (huskProps.get("HeadlessDeviceOwnerMode") instanceof Integer ? (Integer) huskProps.get("HeadlessDeviceOwnerMode") : 0); }
    public java.lang.String getPackageName() { return (java.lang.String) huskProps.get("PackageName"); }
    public java.lang.String getReceiverName() { return (java.lang.String) huskProps.get("ReceiverName"); }
    public java.lang.String getTagForPolicy(int p0) { return null; }
    public java.util.ArrayList getUsedPolicies() { return (huskProps.get("UsedPolicies") != null ? (java.util.ArrayList) huskProps.get("UsedPolicies") : new java.util.ArrayList()); }
    public boolean isVisible() { return (huskProps.get("Visible") instanceof Boolean ? (Boolean) huskProps.get("Visible") : false); }
    public java.lang.CharSequence loadDescription(android.content.pm.PackageManager p0) { return null; }
    public android.graphics.drawable.Drawable loadIcon(android.content.pm.PackageManager p0) { return null; }
    public java.lang.CharSequence loadLabel(android.content.pm.PackageManager p0) { return null; }
    public boolean supportsTransferOwnership() { return false; }
    public boolean usesPolicy(int p0) { return false; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    public static class PolicyInfo {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int description;
        public int descriptionForSecondaryUsers;
        public int ident;
        public int label;
        public int labelForSecondaryUsers;
        public java.lang.String tag;
        public PolicyInfo(int p0, java.lang.String p1, int p2, int p3) {}
        public PolicyInfo(int p0, java.lang.String p1, int p2, int p3, int p4, int p5) {}
    }
}
