// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.admin;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class FreezePeriod {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public FreezePeriod(java.time.MonthDay p0, java.time.MonthDay p1) {}
    public static int distanceWithoutLeapYear(java.time.LocalDate p0, java.time.LocalDate p1) { return 0; }
    public java.time.MonthDay getEnd() { return (java.time.MonthDay) huskProps.get("End"); }
    public java.time.MonthDay getStart() { return (java.time.MonthDay) huskProps.get("Start"); }
}
