// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.admin;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class PackagePolicy implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static final int PACKAGE_POLICY_ALLOWLIST = 3;
    public static final int PACKAGE_POLICY_ALLOWLIST_AND_SYSTEM = 2;
    public static final int PACKAGE_POLICY_BLOCKLIST = 1;
    public PackagePolicy(int p0) {}
    public PackagePolicy(int p0, java.util.Set p1) {}
    public int describeContents() { return 0; }
    public java.util.Set getPackageNames() { return (huskProps.get("PackageNames") != null ? (java.util.Set) huskProps.get("PackageNames") : new java.util.HashSet()); }
    public int getPolicyType() { return (huskProps.get("PolicyType") instanceof Integer ? (Integer) huskProps.get("PolicyType") : 0); }
    public boolean isPackageAllowed(java.lang.String p0, java.util.Set p1) { return false; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    PackagePolicy() { this((int) 0); }
}
