// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.admin;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class PreferentialNetworkServiceConfig implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public static android.app.admin.PreferentialNetworkServiceConfig DEFAULT;
    public static final int PREFERENTIAL_NETWORK_ID_1 = 1;
    public static final int PREFERENTIAL_NETWORK_ID_2 = 2;
    public static final int PREFERENTIAL_NETWORK_ID_3 = 3;
    public static final int PREFERENTIAL_NETWORK_ID_4 = 4;
    public static final int PREFERENTIAL_NETWORK_ID_5 = 5;
    public int describeContents() { return 0; }
    public void dump(android.util.IndentingPrintWriter p0) {}
    public int[] getExcludedUids() { return (int[]) huskProps.get("ExcludedUids"); }
    public int[] getIncludedUids() { return (int[]) huskProps.get("IncludedUids"); }
    public int getNetworkId() { return (huskProps.get("NetworkId") instanceof Integer ? (Integer) huskProps.get("NetworkId") : 0); }
    public boolean isEnabled() { return (huskProps.get("Enabled") instanceof Boolean ? (Boolean) huskProps.get("Enabled") : false); }
    public boolean isFallbackToDefaultConnectionAllowed() { return (huskProps.get("FallbackToDefaultConnectionAllowed") instanceof Boolean ? (Boolean) huskProps.get("FallbackToDefaultConnectionAllowed") : false); }
    public boolean shouldBlockNonMatchingNetworks() { return false; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    protected PreferentialNetworkServiceConfig() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.app.admin.PreferentialNetworkServiceConfig build() { android.app.admin.PreferentialNetworkServiceConfig x = new android.app.admin.PreferentialNetworkServiceConfig(); x.huskProps.putAll(huskProps); return x; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); return this; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setExcludedUids(int[] p0) { huskProps.put("ExcludedUids", p0); return this; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setFallbackToDefaultConnectionAllowed(boolean p0) { huskProps.put("FallbackToDefaultConnectionAllowed", Boolean.valueOf(p0)); return this; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setIncludedUids(int[] p0) { huskProps.put("IncludedUids", p0); return this; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setNetworkId(int p0) { huskProps.put("NetworkId", Integer.valueOf(p0)); return this; }
        public android.app.admin.PreferentialNetworkServiceConfig.Builder setShouldBlockNonMatchingNetworks(boolean p0) { huskProps.put("ShouldBlockNonMatchingNetworks", Boolean.valueOf(p0)); return this; }
    }
}
