// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.admin;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class UnsafeStateException extends java.lang.IllegalStateException implements android.os.Parcelable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.os.Parcelable.Creator CREATOR;
    public UnsafeStateException(int p0, int p1) { super(); }
    public int describeContents() { return 0; }
    public java.lang.String getMessage() { return (java.lang.String) huskProps.get("Message"); }
    public int getOperation() { return (huskProps.get("Operation") instanceof Integer ? (Integer) huskProps.get("Operation") : 0); }
    public java.util.List getReasons() { return (huskProps.get("Reasons") != null ? (java.util.List) huskProps.get("Reasons") : new java.util.ArrayList()); }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
}
