// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.projection;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class MediaProjectionInfo implements android.os.Parcelable {
    protected MediaProjectionInfo() {}
}
