// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.projection;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class MediaProjection {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public MediaProjection(android.content.Context p0, android.media.projection.IMediaProjection p1) {}
    public MediaProjection(android.content.Context p0, android.media.projection.IMediaProjection p1, android.hardware.display.DisplayManager p2) {}
    public android.hardware.display.VirtualDisplay createVirtualDisplay(android.hardware.display.VirtualDisplayConfig.Builder p0, android.hardware.display.VirtualDisplay.Callback p1, android.os.Handler p2) { return null; }
    public android.hardware.display.VirtualDisplay createVirtualDisplay(java.lang.String p0, int p1, int p2, int p3, int p4, android.view.Surface p5, android.hardware.display.VirtualDisplay.Callback p6, android.os.Handler p7) { return null; }
    public android.hardware.display.VirtualDisplay createVirtualDisplay(java.lang.String p0, int p1, int p2, int p3, boolean p4, android.view.Surface p5, android.hardware.display.VirtualDisplay.Callback p6, android.os.Handler p7) { return null; }
    public android.media.projection.IMediaProjection getProjection() { return (android.media.projection.IMediaProjection) huskProps.get("Projection"); }
    public void registerCallback(android.media.projection.MediaProjection.Callback p0, android.os.Handler p1) {}
    public void stop() {}
    public void stop(int p0) {}
    public void unregisterCallback(android.media.projection.MediaProjection.Callback p0) {}
    MediaProjection() { this((android.content.Context) null, (android.media.projection.IMediaProjection) null); }
    public static abstract class Callback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Callback() {}
        public void onCapturedContentResize(int p0, int p1) {}
        public void onCapturedContentVisibilityChanged(boolean p0) {}
        public void onStop() {}
    }
}
