package android.view.inputmethod;
public class CompletionInfo {
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public CompletionInfo() {}
    public static android.os.Parcelable.Creator CREATOR;
    public CompletionInfo(long p0, int p1, java.lang.CharSequence p2) { this(); }
    public CompletionInfo(long p0, int p1, java.lang.CharSequence p2, java.lang.CharSequence p3) { this(); }
    public int describeContents() { return 0; }
    public long getId() { return 0L; }
    public java.lang.CharSequence getLabel() { return null; }
    public int getPosition() { return 0; }
    public java.lang.CharSequence getText() { return null; }
    public void writeToParcel(android.os.Parcel p0, int p1) {}
    // ---- end of generated members
}
