package android.view.inputmethod;

import android.os.Bundle;
import android.view.KeyEvent;

public class InputConnectionWrapper implements InputConnection {
    private InputConnection mTarget;
    public InputConnectionWrapper(InputConnection target, boolean mutable) { mTarget = target; }
    public void setTarget(InputConnection t) { mTarget = t; }
    public CharSequence getTextBeforeCursor(int n, int f) { return mTarget.getTextBeforeCursor(n, f); }
    public CharSequence getTextAfterCursor(int n, int f) { return mTarget.getTextAfterCursor(n, f); }
    public CharSequence getSelectedText(int f) { return mTarget.getSelectedText(f); }
    public int getCursorCapsMode(int r) { return mTarget.getCursorCapsMode(r); }
    public ExtractedText getExtractedText(ExtractedTextRequest r, int f) { return mTarget.getExtractedText(r, f); }
    public boolean deleteSurroundingText(int b, int a) { return mTarget.deleteSurroundingText(b, a); }
    public boolean deleteSurroundingTextInCodePoints(int b, int a) { return mTarget.deleteSurroundingTextInCodePoints(b, a); }
    public boolean setComposingText(CharSequence t, int p) { return mTarget.setComposingText(t, p); }
    public boolean setComposingRegion(int s, int e) { return mTarget.setComposingRegion(s, e); }
    public boolean finishComposingText() { return mTarget.finishComposingText(); }
    public boolean commitText(CharSequence t, int p) { return mTarget.commitText(t, p); }
    public boolean commitCompletion(CompletionInfo t) { return mTarget.commitCompletion(t); }
    public boolean commitCorrection(CorrectionInfo i) { return mTarget.commitCorrection(i); }
    public boolean setSelection(int s, int e) { return mTarget.setSelection(s, e); }
    public boolean performEditorAction(int a) { return mTarget.performEditorAction(a); }
    public boolean performContextMenuAction(int id) { return mTarget.performContextMenuAction(id); }
    public boolean beginBatchEdit() { return mTarget.beginBatchEdit(); }
    public boolean endBatchEdit() { return mTarget.endBatchEdit(); }
    public boolean sendKeyEvent(KeyEvent e) { return mTarget.sendKeyEvent(e); }
    public boolean clearMetaKeyStates(int s) { return mTarget.clearMetaKeyStates(s); }
    public boolean reportFullscreenMode(boolean e) { return mTarget.reportFullscreenMode(e); }
    public boolean performPrivateCommand(String a, Bundle d) { return mTarget.performPrivateCommand(a, d); }
    public boolean requestCursorUpdates(int m) { return mTarget.requestCursorUpdates(m); }
    public android.os.Handler getHandler() { return mTarget.getHandler(); }
    public void closeConnection() { mTarget.closeConnection(); }
    public boolean commitContent(InputContentInfo i, int f, Bundle o) { return mTarget.commitContent(i, f, o); }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public boolean commitText(java.lang.CharSequence p0, int p1, android.view.inputmethod.TextAttribute p2) { return false; }
    public void performHandwritingGesture(android.view.inputmethod.HandwritingGesture p0, java.util.concurrent.Executor p1, java.util.function.IntConsumer p2) {}
    public boolean performSpellCheck() { return false; }
    public boolean previewHandwritingGesture(android.view.inputmethod.PreviewableHandwritingGesture p0, android.os.CancellationSignal p1) { return false; }
    public boolean replaceText(int p0, int p1, java.lang.CharSequence p2, int p3, android.view.inputmethod.TextAttribute p4) { return false; }
    public boolean requestCursorUpdates(int p0, int p1) { return false; }
    public void requestTextBoundsInfo(android.graphics.RectF p0, java.util.concurrent.Executor p1, java.util.function.Consumer p2) {}
    public boolean setComposingRegion(int p0, int p1, android.view.inputmethod.TextAttribute p2) { return false; }
    public boolean setComposingText(java.lang.CharSequence p0, int p1, android.view.inputmethod.TextAttribute p2) { return false; }
    // ---- end of generated members
}
