package android.view.inputmethod;

import android.view.View;

/** The keyboard: the iPhone's, shown for the focused text view and typing into its input connection (husk.InputMethods). */
public final class InputMethodManager {
    public static final int SHOW_IMPLICIT = 1, SHOW_FORCED = 2, HIDE_IMPLICIT_ONLY = 1, HIDE_NOT_ALWAYS = 2, RESULT_UNCHANGED_SHOWN = 0, RESULT_UNCHANGED_HIDDEN = 1,
        RESULT_SHOWN = 2, RESULT_HIDDEN = 3;
    public boolean showSoftInput(View v, int flags) { return husk.InputMethods.show(v); }
    public boolean showSoftInput(View v, int flags, android.os.ResultReceiver r) { boolean s = husk.InputMethods.show(v); if (r != null) r.send(s ? RESULT_SHOWN : RESULT_UNCHANGED_SHOWN, null); return s; }
    public boolean hideSoftInputFromWindow(android.os.IBinder token, int flags) { return husk.InputMethods.hide(); }
    public boolean hideSoftInputFromWindow(android.os.IBinder token, int flags, android.os.ResultReceiver r) { boolean h = husk.InputMethods.hide(); if (r != null) r.send(h ? RESULT_HIDDEN : RESULT_UNCHANGED_HIDDEN, null); return h; }
    public void toggleSoftInput(int show, int hide) { if (husk.InputMethods.shown()) husk.InputMethods.hide(); else husk.InputMethods.show(husk.InputMethods.focused()); }
    public void toggleSoftInputFromWindow(android.os.IBinder token, int show, int hide) { toggleSoftInput(show, hide); }
    public boolean isActive() { return husk.InputMethods.focused() != null; }
    public boolean isActive(View v) { return husk.InputMethods.focused() == v; }
    public boolean isAcceptingText() { return husk.InputMethods.shown(); }
    public boolean isFullscreenMode() { return false; }
    public void restartInput(View v) { husk.InputMethods.restart(v); }
    public void updateSelection(View v, int ss, int se, int cs, int ce) {}
    public void updateCursorAnchorInfo(View v, CursorAnchorInfo info) {}
    public void updateExtractedText(View v, int token, ExtractedText t) {}
    public void displayCompletions(View v, CompletionInfo[] c) {}
    public void viewClicked(View v) {}
    public void sendAppPrivateCommand(View v, String action, android.os.Bundle data) {}
    public java.util.List<InputMethodInfo> getInputMethodList() { return new java.util.ArrayList<>(); }
    public java.util.List<InputMethodInfo> getEnabledInputMethodList() { return new java.util.ArrayList<>(); }
    public InputMethodSubtype getCurrentInputMethodSubtype() { return null; }
    public void showInputMethodPicker() {}
    public boolean isInputMethodSuppressingSpellChecker() { return false; }
    public void startStylusHandwriting(View v) {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public static final int DISPATCH_HANDLED = 1;
    public static final int DISPATCH_IN_PROGRESS = -1;
    public static final int DISPATCH_NOT_HANDLED = 0;
    public static final int HANDWRITING_DELEGATE_FLAG_HOME_DELEGATOR_ALLOWED = 1;
    public static final int SHOW_IM_PICKER_MODE_AUTO = 0;
    public static final int SHOW_IM_PICKER_MODE_EXCLUDE_AUXILIARY_SUBTYPES = 2;
    public static final int SHOW_IM_PICKER_MODE_INCLUDE_AUXILIARY_SUBTYPES = 1;
    public static void ensureDefaultInstanceForDefaultDisplayIfNecessary() {}
    public static android.view.inputmethod.InputMethodManager forContext(android.content.Context p0) { return null; }
    public static android.view.inputmethod.InputMethodManager getInstance() { return null; }
    public static void invalidateLocalConnectionlessStylusHandwritingAvailabilityCaches() {}
    public static void invalidateLocalStylusHandwritingAvailabilityCaches() {}
    public static android.view.inputmethod.InputMethodManager peekInstance() { return null; }
    public void acceptStylusHandwritingDelegation(android.view.View p0, java.lang.String p1, int p2, java.util.concurrent.Executor p3, java.util.function.Consumer p4) {}
    public void acceptStylusHandwritingDelegation(android.view.View p0, java.lang.String p1, java.util.concurrent.Executor p2, java.util.function.Consumer p3) {}
    public boolean acceptStylusHandwritingDelegation(android.view.View p0) { return false; }
    public boolean acceptStylusHandwritingDelegation(android.view.View p0, java.lang.String p1) { return false; }
    public void addVirtualStylusIdForTestSession() {}
    public void checkFocus() {}
    public void dispatchKeyEventFromInputMethod(android.view.View p0, android.view.KeyEvent p1) {}
    public void dumpDebug(android.util.proto.ProtoOutputStream p0, byte[] p1) {}
    public void finishTrackingPendingRequests() {}
    public android.view.inputmethod.InputMethodInfo getCurrentInputMethodInfo() { return null; }
    public android.view.inputmethod.InputMethodInfo getCurrentInputMethodInfoAsUser(android.os.UserHandle p0) { return null; }
    public int getDisplayId() { return 0; }
    public java.util.List getEnabledInputMethodListAsUser(android.os.UserHandle p0) { return new java.util.ArrayList(); }
    public java.util.List getEnabledInputMethodSubtypeList(android.view.inputmethod.InputMethodInfo p0, boolean p1) { return new java.util.ArrayList(); }
    public java.util.List getEnabledInputMethodSubtypeListAsUser(java.lang.String p0, boolean p1, android.os.UserHandle p2) { return new java.util.ArrayList(); }
    public java.util.List getInputMethodListAsUser(int p0) { return new java.util.ArrayList(); }
    public java.util.List getInputMethodListAsUser(int p0, int p1) { return new java.util.ArrayList(); }
    public int getInputMethodWindowVisibleHeight() { return 0; }
    public android.view.inputmethod.InputMethodSubtype getLastInputMethodSubtype() { return null; }
    public java.util.Map getShortcutInputMethodsAndSubtypes() { return new java.util.HashMap(); }
    public boolean hasActiveInputConnection(android.view.View p0) { return false; }
    public void hideSoftInputFromInputMethod(android.os.IBinder p0, int p1) {}
    public void hideSoftInputFromServerForTest() {}
    public boolean hideSoftInputFromView(android.view.View p0, int p1) { return false; }
    public void hideStatusIcon(android.os.IBinder p0) {}
    public void invalidateInput(android.view.View p0) {}
    public boolean isConnectionlessStylusHandwritingAvailable() { return false; }
    public boolean isCurrentRootView(android.view.View p0) { return false; }
    public boolean isCursorAnchorInfoEnabled() { return false; }
    public boolean isInputMethodPickerShown() { return false; }
    public boolean isStylusHandwritingAvailable() { return false; }
    public boolean isStylusHandwritingAvailableAsUser(android.os.UserHandle p0) { return false; }
    public boolean isWatchingCursor(android.view.View p0) { return false; }
    public void notifySuggestionPicked(android.text.style.SuggestionSpan p0, java.lang.String p1, int p2) {}
    public void notifyUserAction() {}
    public void onImeSwitchButtonClickFromSystem(int p0) {}
    public void prepareStylusHandwritingDelegation(android.view.View p0) {}
    public void prepareStylusHandwritingDelegation(android.view.View p0, java.lang.String p1) {}
    public void registerSuggestionSpansForNotification(android.text.style.SuggestionSpan[] p0) {}
    public void removeImeSurfaceFromWindow(android.os.IBinder p0) {}
    public void reportPerceptible(android.os.IBinder p0, boolean p1) {}
    public void setAdditionalInputMethodSubtypes(java.lang.String p0, android.view.inputmethod.InputMethodSubtype[] p1) {}
    public void setAllowedImesByPolicyForTest(java.util.List p0) {}
    public boolean setCurrentInputMethodSubtype(android.view.inputmethod.InputMethodSubtype p0) { return false; }
    public void setExplicitlyEnabledInputMethodSubtypes(java.lang.String p0, int[] p1) {}
    public void setInputMethod(android.os.IBinder p0, java.lang.String p1) {}
    public void setInputMethodAndSubtype(android.os.IBinder p0, java.lang.String p1, android.view.inputmethod.InputMethodSubtype p2) {}
    public void setStylusWindowIdleTimeoutForTest(long p0) {}
    public void setUpdateCursorAnchorInfoMode(int p0) {}
    public boolean shouldOfferSwitchingToNextInputMethod(android.os.IBinder p0) { return false; }
    public boolean shouldShowImeSwitcherButtonForTest() { return false; }
    public void showInputMethodAndSubtypeEnabler(java.lang.String p0) {}
    public void showInputMethodPickerFromSystem(boolean p0, int p1) {}
    public void showSoftInputFromInputMethod(android.os.IBinder p0, int p1) {}
    public void showSoftInputUnchecked(int p0, android.os.ResultReceiver p1) {}
    public void showStatusIcon(android.os.IBinder p0, java.lang.String p1, int p2) {}
    public void startConnectionlessStylusHandwriting(android.view.View p0, android.view.inputmethod.CursorAnchorInfo p1, java.util.concurrent.Executor p2, android.view.inputmethod.ConnectionlessHandwritingCallback p3) {}
    public void startConnectionlessStylusHandwritingForDelegation(android.view.View p0, android.view.inputmethod.CursorAnchorInfo p1, java.lang.String p2, java.util.concurrent.Executor p3, android.view.inputmethod.ConnectionlessHandwritingCallback p4) {}
    public void startConnectionlessStylusHandwritingForDelegation(android.view.View p0, android.view.inputmethod.CursorAnchorInfo p1, java.util.concurrent.Executor p2, android.view.inputmethod.ConnectionlessHandwritingCallback p3) {}
    public boolean switchToLastInputMethod(android.os.IBinder p0) { return false; }
    public boolean switchToNextInputMethod(android.os.IBinder p0, boolean p1) { return false; }
    public void updateCursor(android.view.View p0, int p1, int p2, int p3, int p4) {}
    public void waitUntilNoPendingRequests(long p0) {}
    public void windowDismissed(android.os.IBinder p0) {}
    // ---- end of generated members
}
