// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.security.identity;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class CredentialDataRequest {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public java.util.Map getDeviceSignedEntriesToRequest() { return (huskProps.get("DeviceSignedEntriesToRequest") != null ? (java.util.Map) huskProps.get("DeviceSignedEntriesToRequest") : new java.util.HashMap()); }
    public java.util.Map getIssuerSignedEntriesToRequest() { return (huskProps.get("IssuerSignedEntriesToRequest") != null ? (java.util.Map) huskProps.get("IssuerSignedEntriesToRequest") : new java.util.HashMap()); }
    public byte[] getReaderSignature() { return (byte[]) huskProps.get("ReaderSignature"); }
    public byte[] getRequestMessage() { return (byte[]) huskProps.get("RequestMessage"); }
    public boolean isAllowUsingExhaustedKeys() { return (huskProps.get("AllowUsingExhaustedKeys") instanceof Boolean ? (Boolean) huskProps.get("AllowUsingExhaustedKeys") : false); }
    public boolean isAllowUsingExpiredKeys() { return (huskProps.get("AllowUsingExpiredKeys") instanceof Boolean ? (Boolean) huskProps.get("AllowUsingExpiredKeys") : false); }
    public boolean isIncrementUseCount() { return (huskProps.get("IncrementUseCount") instanceof Boolean ? (Boolean) huskProps.get("IncrementUseCount") : false); }
    protected CredentialDataRequest() {}
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public android.security.identity.CredentialDataRequest build() { android.security.identity.CredentialDataRequest x = new android.security.identity.CredentialDataRequest(); x.huskProps.putAll(huskProps); return x; }
        public android.security.identity.CredentialDataRequest.Builder setAllowUsingExhaustedKeys(boolean p0) { huskProps.put("AllowUsingExhaustedKeys", Boolean.valueOf(p0)); return this; }
        public android.security.identity.CredentialDataRequest.Builder setAllowUsingExpiredKeys(boolean p0) { huskProps.put("AllowUsingExpiredKeys", Boolean.valueOf(p0)); return this; }
        public android.security.identity.CredentialDataRequest.Builder setDeviceSignedEntriesToRequest(java.util.Map p0) { huskProps.put("DeviceSignedEntriesToRequest", p0); return this; }
        public android.security.identity.CredentialDataRequest.Builder setIncrementUseCount(boolean p0) { huskProps.put("IncrementUseCount", Boolean.valueOf(p0)); return this; }
        public android.security.identity.CredentialDataRequest.Builder setIssuerSignedEntriesToRequest(java.util.Map p0) { huskProps.put("IssuerSignedEntriesToRequest", p0); return this; }
        public android.security.identity.CredentialDataRequest.Builder setReaderSignature(byte[] p0) { huskProps.put("ReaderSignature", p0); return this; }
        public android.security.identity.CredentialDataRequest.Builder setRequestMessage(byte[] p0) { huskProps.put("RequestMessage", p0); return this; }
    }
}
