// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.provider;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Browser {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.net.Uri BOOKMARKS_URI = android.net.Uri.parse("content://browser/bookmarks");
    public static final java.lang.String EXTRA_APPLICATION_ID = "com.android.browser.application_id";
    public static final java.lang.String EXTRA_CREATE_NEW_TAB = "create_new_tab";
    public static final java.lang.String EXTRA_HEADERS = "com.android.browser.headers";
    public static final java.lang.String EXTRA_SHARE_FAVICON = "share_favicon";
    public static final java.lang.String EXTRA_SHARE_SCREENSHOT = "share_screenshot";
    public static java.lang.String[] HISTORY_PROJECTION;
    public static final int HISTORY_PROJECTION_BOOKMARK_INDEX = 4;
    public static final int HISTORY_PROJECTION_DATE_INDEX = 3;
    public static final int HISTORY_PROJECTION_FAVICON_INDEX = 6;
    public static final int HISTORY_PROJECTION_ID_INDEX = 0;
    public static final int HISTORY_PROJECTION_THUMBNAIL_INDEX = 7;
    public static final int HISTORY_PROJECTION_TITLE_INDEX = 5;
    public static final int HISTORY_PROJECTION_TOUCH_ICON_INDEX = 8;
    public static final int HISTORY_PROJECTION_URL_INDEX = 1;
    public static final int HISTORY_PROJECTION_VISITS_INDEX = 2;
    public static final java.lang.String INITIAL_ZOOM_LEVEL = "browser.initialZoomLevel";
    public static java.lang.String[] SEARCHES_PROJECTION;
    public static final int SEARCHES_PROJECTION_DATE_INDEX = 2;
    public static final int SEARCHES_PROJECTION_SEARCH_INDEX = 1;
    public static android.net.Uri SEARCHES_URI = android.net.Uri.parse("content://browser/searches");
    public static java.lang.String[] TRUNCATE_HISTORY_PROJECTION;
    public static final int TRUNCATE_HISTORY_PROJECTION_ID_INDEX = 0;
    public static final int TRUNCATE_N_OLDEST = 5;
    public Browser() {}
    public static void addSearchUrl(android.content.ContentResolver p0, java.lang.String p1) {}
    public static boolean canClearHistory(android.content.ContentResolver p0) { return false; }
    public static void clearHistory(android.content.ContentResolver p0) {}
    public static void clearSearches(android.content.ContentResolver p0) {}
    public static void deleteFromHistory(android.content.ContentResolver p0, java.lang.String p1) {}
    public static void deleteHistoryTimeFrame(android.content.ContentResolver p0, long p1, long p2) {}
    public static android.database.Cursor getAllBookmarks(android.content.ContentResolver p0) { return null; }
    public static android.database.Cursor getAllVisitedUrls(android.content.ContentResolver p0) { return null; }
    public static java.lang.String[] getVisitedHistory(android.content.ContentResolver p0) { return null; }
    public static void requestAllIcons(android.content.ContentResolver p0, java.lang.String p1, android.webkit.WebIconDatabase.IconListener p2) {}
    public static void saveBookmark(android.content.Context p0, java.lang.String p1, java.lang.String p2) {}
    public static void sendString(android.content.Context p0, java.lang.String p1) {}
    public static void sendString(android.content.Context p0, java.lang.String p1, java.lang.String p2) {}
    public static void truncateHistory(android.content.ContentResolver p0) {}
    public static void updateVisitedHistory(android.content.ContentResolver p0, java.lang.String p1, boolean p2) {}
    public static class BookmarkColumns implements android.provider.BaseColumns {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final java.lang.String BOOKMARK = "bookmark";
        public static final java.lang.String CREATED = "created";
        public static final java.lang.String DATE = "date";
        public static final java.lang.String FAVICON = "favicon";
        public static final java.lang.String THUMBNAIL = "thumbnail";
        public static final java.lang.String TITLE = "title";
        public static final java.lang.String TOUCH_ICON = "touch_icon";
        public static final java.lang.String URL = "url";
        public static final java.lang.String USER_ENTERED = "user_entered";
        public static final java.lang.String VISITS = "visits";
        public BookmarkColumns() {}
    }
    public static class SearchColumns implements android.provider.BaseColumns {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final java.lang.String DATE = "date";
        public static final java.lang.String SEARCH = "search";
        public static final java.lang.String URL = "url";
        public SearchColumns() {}
    }
}
